### PR TITLE
Revert "Operators reloading info"

### PR DESCRIPTION
**Pull request by EquipableMC**
Reverts SkriptLang/Skript#6780

Reverts this pull request as there is message issues that went unnoticed.
**Ingame:**
image
**CONSOLE**
image

### CODE REVIEW

**Comment by AyhamAl-Ali** [comment]
No need to revert the whole thing, just fix it 💅

**Comment by EquipableMC** [comment]
> No need to revert the whole thing, just fix it 💅

True, but this seems to be a bigger issue then I know with my experience in Java (RedirectingLogHandler). So I figured reverting it, then someone can make a new PR which implements it better with working messages

**Comment by sovdeeth** [comment]
It's on dev/feature, there's no rush and no need to revert it.

**Comment by EquipableMC** [comment]
> It's on dev/feature, there's no rush and no need to revert it.

True, should I open an issue instead?

**Comment by AyhamAl-Ali** [comment]
> It's on dev/feature, there's no rush and no need to revert it.

Adding to that it's not a breaking change and can be easily hot-fixed by removing the permission from recipients. Either open a new issue or open a new PR with a fix.

**Pull request closed without merging**
