### PR TITLE
Skript - fix error to run on MC 1.18

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
This PR aims to help Skript run on MC 1.18.
In 1.18, Spigot went and removed what seems like all Bukkit Mapped NMS methods. So here we are using the method
`MinecraftServer#isRunning` which is now just `MinecraftServer#v`

This may not be the sexiest fix, but it works for now. I am open to suggestions of how to do this better, as future versions may have a different obfuscated method, and this could get QUITE messy

Without this fix, Skript will not start on MC 1.18

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #4466

### CODE REVIEW

**Comment by ShaneBeee** [comment]
For some stupid reason, and I DONT know why, but `Skript.isRunningMinecraft` does NOT seem to work properly in tests
I get this error on tests running:
`Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.DedicatedServer.v()`

Clearly my code only uses `MinecraftServer#v` on 1.18+, but in the testing environment, the version check doesnt seem to work.
I've seen this issue happen before when using version checks within the tests

**Comment by AyhamAl-Ali** [comment]
> For some stupid reason, and I DONT know why, but `Skript.isRunningMinecraft` does NOT seem to work properly in tests I get this error on tests running: `Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.DedicatedServer.v()`
> 
> Clearly my code only uses `MinecraftServer#v` on 1.18+, but in the testing environment, the version check doesnt seem to work. I've seen this issue happen before when using version checks within the tests

I've had few issues before with `Skript#isRunningMinecraft` in my PRs due to its order but not sure if this is the reason in your case, could you test this PR on 1.12.2 on your local to actually see if this is only happens in the test environment?

**Comment by AyhamAl-Ali** [comment]
As you can see in this PR #3908 I've recoded version checking, after testing on 1.12.2 on your local if it fails try to merge this PR on your local and see if this fixes the issue

**Comment by ShaneBeee** [comment]
> As you can see in this PR #3908 I've recoded version checking, after testing on 1.12.2 on your local if it fails try to merge this PR on your local and see if this fixes the issue

ahh perfect thank you, I shall give that a try later today 👍

**Comment by ShaneBeee** [comment]
Going to merge this for now. If we dont like it, we can change it later, but this at least helps us get a working version of Skript out for MC 1.18.x

**Pull request merged**
