### PR TITLE
Switched repositories from HTTP to HTTPS.

### PR DESCRIPTION
**Pull request by BigBadE**
### Description

Switch to HTTPS for a more secure protocol, considered good practice for Gradle as HTTP is considered insecure for code that is being run.
---
**Target Minecraft Versions:**     
All
**Requirements:**     
None
**Related Issues:**     
None

### CODE REVIEW

**Comment by BigBadE** [comment]
I've not contributed to this project yet so if there is a better branch, tell me and I'll will switch it.

**Comment by JRoy** [comment]
Did you actually test this? `nexus.hc.to` doesn't even have an SSL certificate and `ci.emc.gs` uses Let's Encrypt as a CA which doesn't work well on some Java 8 installations. This is not needed at all as no logical attack vector is here.

**Comment by BigBadE** [comment]
`maven.sk89q.com` has a valid SSL certificate, if you're sticking with HTTP because there is no attack vector switch every website to HTTP and not just one.

**Comment by JRoy** [comment]
> `maven.sk89q.com` has a valid SSL certificate
Yes

In my last post, I said:
> `nexus.hc.to` doesn't even have an SSL certificate and `ci.emc.gs` uses Let's Encrypt as a CA which doesn't work well on some Java 8 installations.

Those are reasons why I said Skript **cannot** switch to https for gradle repos. I also mentioned that the attack vector for a man in the middle attack on a gradle repository is soo low. But that doesn't matter since Skript can't use https on those repos anyway.

**Comment by bensku** [comment]
@JRoy CI succeeded on Java 8, which seems to indicate that certificates are fine. It doesn't really matter if your *browser* accepts them, just that Gradle does. MITM against a Maven repo sounds pretty good to me, it allows worse things than what hijacking most websites would allow.

If Let's Encrypt does not work on some Java 8 installations, developers using those can update. Skript runs and can be developed on Java 11.

**Pull request closed without merging**
