### PR TITLE
Improve registering event values 

### PR DESCRIPTION
**Pull request by Efnilite**
### Description

- Deprecates Getter
- Makes registering an event value require a Converter instead of a Getter
- Adds method for registering an event value without having to specify the time

**Example**
Before
```java
EventValues.registerEventValue(WorldEvent.class, World.class, new Getter<World, WorldEvent>() {
		@Override
		@Nullable
		public World get(final WorldEvent e) {
			return e.getWorld();
		}
}, EventValues.TIME_NOW);
```

After
```java
EventValues.registerEventValue(WorldEvent.class, World.class, WorldEvent::getWorld);
```

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #5006

### CODE REVIEW

**Comment by sovdeeth** [comment]
related #5405

**Comment by Efnilite** [comment]
> I might like to see Getter deprecated, and perhaps you could have it extend Function and just change the existing method signatures

this PR was the beginning of my war against Getter. glad you agree :)

**Review by Burbulinis — APPROVED** [review]
love it need it like it very nice!

**Review by Moderocky — APPROVED** [review]

**Review by sovdeeth — COMMENTED** [review]
Do you intend to finish updating BukkitEventValues?

**Review by Moderocky — CHANGES_REQUESTED** [review]
Just to make sure this doesn't get merged before Sovde's comment gets a response.

**Comment by Efnilite** [comment]
> Do you intend to finish updating BukkitEventValues?

It was mostly for example purposes. Idm though, should I or is it too prone to merge conflicts?

**Review by Moderocky — APPROVED** [review]

**Pull request merged**
