### PR TITLE
Fix/number converters

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Adds more number converters, from the generic `java.lang.Number` type to specific subclasses.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #4445

### CODE REVIEW

**Review by AyhamAl-Ali — APPROVED** [review]

**Review by TheLimeGlass — CHANGES_REQUESTED** [review]
I suggest adding a test for every new Number converter. This may also cause issues with existing syntaxes due to the nature of using Number as the return type rather than it's actual type like Hunger of a player returning Double. Most syntaxes just return Number (Mainly addons, but Skript still has some old syntaxes that do this)

**Comment by TPGamesNL** [comment]
@TheLimeGlass How would you imagine writing such tests in a script? The only types scripts can use are number (java.lang.Number) and integer (java.lang.Long), and no syntaxes require a specific number type, all take %number%. This requirement would no longer be needed after this PR, as converters would take care of it. However, it would also not be worth changing, unless the syntax element requires the wrapper type instead of the primitive, which is not often.

I also don't see how it could cause issues, can you elaborate on that?

**Comment by TheLimeGlass** [comment]
> @TheLimeGlass How would you imagine writing such tests in a script? The only types scripts can use are number (java.lang.Number) and integer (java.lang.Long), and no syntaxes require a specific number type, all take %number%. This requirement would no longer be needed after this PR, as converters would take care of it. However, it would also not be worth changing, unless the syntax element requires the wrapper type instead of the primitive, which is not often.
> 
> I also don't see how it could cause issues, can you elaborate on that?

As discussed, JUnit tests are gonna be best for this solution.

**Review by TheLimeGlass — APPROVED** [review]
@TPGamesNL conflicts

**Pull request merged**
