### PR TITLE
Updated files lost in a previous commit

### PR DESCRIPTION
**Pull request by Efnilite**
This PR is for updating files lost/changed in a previous commit, as suggested by @Pikachu920 
(feel free to discuss the changes, but I have no idea why they needed to be changed)

### CODE REVIEW

**Comment by JRoy** [comment]
Why do you have tab characters in blank lines? That wastes space

**Comment by Pikachu920** [comment]
Convert space indentation to tabs and then I'll merge, thanks

**Comment by Nicofisi** [comment]
@Pikachu920 where do you mean, it does use tabs as far as I see

**Comment by Pikachu920** [comment]
maybe I'm crazy

**Comment by Pikachu920** [comment]
Merged manually (https://github.com/SkriptLang/Skript/commit/a0c3895caae8ccd9d8fc823478ac465eb9b0bbf6), thanks!

**Pull request closed without merging**
