### PR TITLE
Add Object -> String converter

### PR DESCRIPTION
**Pull request by Mr-Darth**
### Description
Added an object to string converter.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3164

### CODE REVIEW

**Review by APickledWalrus — APPROVED** [review]
As long as this works properly and doesn't cause any issues it should be okay? I assume this works in function arguments too, which is nice.

**Review by Pikachu920 — CHANGES_REQUESTED** [review]
in the past when we've messed with generic converters it has caused a slowdown in parsing and a lot of trouble with unexpected/unwanted behavior.

**Review by Pikachu920 — CHANGES_REQUESTED** [review]
if we want to implement #3164 the best way to do it is just making the send/broadcast effects take in objects instead

**Comment by Mr-Darth** [comment]
I'll close this PR and I will open a new one for adding object support to the broadcast & message effects

**Pull request closed without merging**
