### PR TITLE
Better '%number% times' improvements, fixing loop <= 1 times.

### PR DESCRIPTION
**Pull request by TheLimeGlass**
**Target Minecraft versions:** Any
**Related issues:** #1384 and #1356

**Description:** A better fix to issue #1356 with performance increase from original code.

### CODE REVIEW

**Comment by Snow-Pyon** [comment]
Can we have benchmarks on that claim?

**Comment by Nicofisi** [comment]
No, this is worse imho. 
1. Broken encoding
2. **The errors are runtime, not parse time**
3. It looks better when the expression is in a separate class imo
4. You deleted the last line break
5. No "once" nor "twice"

The only thing I sort of like is that you replaced the long `get` method of ExprNumbers with simply an iterator, which I can change too if others agree that it's a good change

**Comment by TheLimeGlass** [comment]
Broken encoding?

Iterators are faster and this has less execution, I can get a benchmark if you really want.

No one asked for "once", "twice" etc and once contradicts the code and won't even work since <= 1 -> null

They should be in the same class as they use the same code and are exactly the same.

**Comment by TheLimeGlass** [comment]
Oh and your once, twice etc thing, should be a literal anyways if it was to be added, which I really don't think it should for looping.

**Comment by Nicofisi** [comment]
@TheLimeGlass bensku approved the "once" and "twice" syntax. The main problem with your PR is that it doesn't display the errors on parse time. Also, Skript doesn't use runtime console errors, like you did here. In my opinion this expression isn't "exactly the same" at all, the only common thing is that both expressions return an array of numbers. But still, they are supposed to be used in entirely different situations.

Yep, you did clean up the ExprNumber class nicely by shortening that long method, but IMO splitting it into multiple files is still better

**Comment by TheLimeGlass** [comment]
I mean init erroring isn't even that hard to add.

**Comment by TheLimeGlass** [comment]
And the last line break shouldn't exist like the rest of Skript's classes

**Comment by Nicofisi** [comment]
> init erroring isn't even that hard to add.

Well, but you didn't add it, and I already have. Maybe consider simply suggesting me to improve my PR next time instead of making a completely differnet one, with design choices completely different to the ones that I have already discussed with the devs on Discord :)

I'm truly not trying to be mean and do not feel insulted, but this whole situation where you decided to make a competing PR instead of commenting on my one, or even PRing to it (that's a perfectly possible thing on GitHub) is a bit weird to me man :/

**Comment by TheLimeGlass** [comment]
I was already fixing it after I posted the issue stating I was going to fix it...

Why would you split it into two expressions when they execute the same code?

**Comment by Snow-Pyon** [comment]
Closed since #1384 seems to betterly reflect the desired behaviour. We appreciate the contribution either way.

**Pull request closed without merging**
