### PR TITLE
Add info command

### PR DESCRIPTION
**Pull request by Olyno**
### Description
Added a "info" command to show useful links as Skript website.

---
**Target Minecraft Versions:**    /
**Requirements:**     /
**Related Issues:**    #1825

### CODE REVIEW

**Comment by Wealthyturtle** [comment]
Please configure your line endings so we can actually see the differences in code...

**Comment by Olyno** [comment]
Any idea of resolve the line endings issue after a commit please?

**Comment by Olyno** [comment]
Should fix line endings issue

**Comment by Olyno** [comment]
> A link for downloads would be useful, too. But it can be added later.

There are Skript Website's link. In the new website, there are a download link, so users should be able to download Skript directly on it

**Comment by Nicofisi** [comment]
> There are Skript Website's link. In the new website, there are a download link, so users should be able to download Skript directly on it

Where is it? Wouldn't it suit better in the same place?

**Comment by Olyno** [comment]
> > There are Skript Website's link. In the new website, there are a download link, so users should be able to download Skript directly on it
> 
> Where is it? Wouldn't it suit better in the same place?

The current link is [here](https://olyno.github.io/skript-website/), but waiting @bensku informations about it.

**Comment by ShaneBeee** [comment]
Thank you for your contribution 👍

**Pull request merged**
