### PR TITLE
Add config option for player name regex

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Adds a config option for the player name regex pattern.

Also includes changes from #4367, thanks @AyhamAl-Ali for that!

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #4374, #4367

### CODE REVIEW

**Review by SaFiKiK — CHANGES_REQUESTED** [review]
Could you please change the min length from 1 to 3, since min. allowed nickname length is 3? It will make less unneeded Bukkit API calls if players make mistakes in commands

**Comment by TheLimeGlass** [comment]
There are still player names with 2 characters. Although extremely rare they'll join your server, there are a few accounts.

I believe Mojang confiscated the accounts that were inactive or compromised, but still allowed 2 letter account names that were active..

**Comment by TheBentoBox** [comment]
There are people with 1 letter names too. The person named "G" joined my server a handful of years ago. They were still active as of 2019 too, at which point they [swapped to a lowercase "g"](https://namemc.com/search?q=G). It should be left as 1 character min.

**Comment by TheLimeGlass** [comment]
If we want to be reducing Mojang API lookups, we can loop `Bukkit.getOfflinePlayers()` first, then use the Bukkit method. We can also cache OfflinePlayers that get returned, although I think the Bukkit server does this. I couldn't find any information if the server caches the results itself.

**Comment by TPGamesNL** [comment]
In that case I'll change it back to a minimum of 1 character (I'm just gonna assume Mojang did not allow a 0 character name).

**Review by TheLimeGlass — APPROVED** [review]

**Review by APickledWalrus — APPROVED** [review]

**Pull request merged**
