### PR TITLE
Add statistic support

### PR DESCRIPTION
**Pull request by Pikachu920**
Target Minecraft versions: Any
Requirements: None
Related issues: #444 (stats can be used to solve it)

Description:
**THIS PR IS NOT READY TO BE MERGED**. I am simply putting it up here to get input particularly on the EnumMapper class (for example, i'm considering using both enummapper and the lang file where the lang file takes priority over automatic mapping to prevent crappy stat names). I also plan to add support for getting the value of a stat, aswell as more event values or expressions for the stat increment event

### CODE REVIEW

**Comment by Blueyescat** [comment]
Statistics expression? Also a `on jump` event should be added to Skript that works with statistics. Not cancellable, but works exactly.

**Comment by bensku** [comment]
If jump event is added, we should use the one provided by Paper. Statistics are likely not a reliable way to detect when a player jumps.

**Comment by Blueyescat** [comment]
No, it is reliable. How do you think Paper will detect jumping?

**Comment by bensku** [comment]
Paper calls the event a bit before than statistic is changed, *at least* on 1.12. That is why I'd like not to use statistic for this. Making sure it works on all Minecraft versions that Skript supports would take a lot more time than just using API from Paper.

Not to mention the fact that you can cancel Paper's event.

**Comment by TheBentoBox** [comment]
I agree with @Blueyescat, actually. Last I heard jumping was controlled client-side and can't be truly canceled by the server in the traditional sense so Paper's cancelation method is probably a bit of a hack (unless I'm wrong about jumps being client-dictated). That's not to say we shouldn't support canceling the event regardless, but if possible we should support the jump event on all platforms and limit just the cancelation to Paper. 

Also. statistics should be a very stable way to register events: they're vanilla and they've been in the game for a very long time (since beta 1.5 and then they were made to be stored per-world in 1.7, which was almost five years ago). In both cases, it's supported far enough back to be safe -- we don't need to support 1.6.

**Comment by Pikachu920** [comment]
it's probably not very hacky. if you didn't know, the server stores all entities' locations a tick before. I bet paper uses that location to teleport the player to the location they were at the tick before they jumped

**Comment by TheBentoBox** [comment]
I'd personally say "canceling a jump" by just overriding it and teleporting them to where they were before the jump is hacky, not that it matters or that there's anything wrong with doing it that way if it's the only way to do so. If it works it works.

**Comment by Pikachu920** [comment]
regardless: the subject of this pr is not a jump event, i only mentioned it because its semi related

**Comment by bensku** [comment]
@Pikachu920 Please test and merge this yourself when you have time.

**Pull request closed without merging**
