### PR TITLE
Remove Air is Block Test

### PR DESCRIPTION
**Pull request by Wealthyturtle**
### Description
This should fix the Java CI glitching out and erroring on some PRs. @bensku 

---
**Target Minecraft Versions:**     Any
**Requirements:**     None
**Related Issues:**     None

### CODE REVIEW

**Comment by bensku** [comment]
I would be interested to learn why they're not blocks on 1.9 instead of just removing tests. Also, if removal is necessary, I'd just force them to run only on MC 1.10+.

**Comment by Wealthyturtle** [comment]
Honestly I have no clue... Could be that Spigot was hardcoding the materials in MC 1.9? Or something. I tried to Google it but couldn't find an answer.

**Comment by bensku** [comment]
I'm ok with just assuming it is 1.9 bug and enabling tests on 1.10+.

**Comment by Wealthyturtle** [comment]
This PR should be merged as soon as possible to prevent other PRs being submitted from being erroneously flagged as failing :P

**Comment by bensku** [comment]
I've been more busy than expected, and will continue to be for a while. Merging this anyway, hopefully nothing breaks.

**Pull request merged**
