### PR TITLE
Use HTTPS, link Java 8 docs instead of 6 and fix invalid links.

### PR DESCRIPTION
**Pull request by TheDGOfficial**
#### Changes:

build.gradle & EffExplosion.java & ExprGlidingState.java & ExprProtocolVersion.java: https
config.sk, lang/readme.txt, SkriptConfig.java: https + java 8 doc

GriefPreventionHook.java: https + njol bukkit skript page --> github SkriptLang page
ChatCode.java: https

DatabaseStorage.java: https + server-mods --> projects to fix 404

#### Explanation of why hard-code HTTPS when sites already redirect anyway:

HTTPS is an encrypted protocol while HTTP is unencrypted and prone to vulnerabilities.
Many sites support HTTPS thanks to Let's Encrypt & HTTPS Everywhere projects, and they redirect http:// to https://.

But in order to redirect http to https, the first request goes unencrypted if the redirect isn't
done on the client side, so an attacker probably remove redirection or do whatever.

Other than build.gradle, the changes are mostly text and for reference, but making every link
that supports https with https:// instead of http:// is better.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

### CODE REVIEW

**Review by WeeskyBDW — APPROVED** [review]

**Review by Skylyxx — APPROVED** [review]

**Comment by TheLimeGlass** [comment]
Gradle 7.0 will not compile in the future if we continue to use http. So this change is absolutely needed.

**Review by ShaneBeee — APPROVED** [review]
Looks good to me 👍

**Comment by LukasmanMHdude** [comment]
maybe add Closes #3785

**Comment by TheDGOfficial** [comment]
> maybe add Closes #3785

That issue is created after this PR is created & merged; and adding closes to the commit message after the merge is not possible, and that would not suit to the Skript's way of handling issues, too, since it would close the issue after merge otherwise automatically. In this repository issues are marked as completed and closed after a release implementing/fixing them is available (as far as I know)

I added it to the Related Issues though for reference, a repository admin can also add to the Linked Issues thing, following below tutorial:
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue

However that may close the issue as It clearly says "Successfully merging this pull request may close these issues.", don't know if it will still close after adding it when pull request is already merged, though.

**Pull request merged**
