### PR TITLE
fixed sql delete bug

### PR DESCRIPTION
**Pull request by Bingonymous**
```
command /e:
    trigger:
        set {a::b::1} to true

command /g:
    trigger:
        delete {a::*}
```
That here also deletes `{a::b::1}` - thing is it doest from the database:

/e results in:
```
Saving... a::b::1 - [B@44beb5d3 (boolean)
```
/g in:
```
Saving... a::b - null (null)
Saving... a::* - null (null)
```

The problem is that Skript locally deletes the data but not in the db, so the deletion is only temporary.

This PR fixes that bug

### CODE REVIEW

**Comment by Bingonymous** [comment]
With that you can also remove the recursion here: `Saving... a::b - null (null)` (as it removes all starting with "a::*")

**Comment by Bingonymous** [comment]
But I couldn't find that code in the sourcecode, so sorry

**Comment by TheLimeGlass** [comment]
If you're building off the enhancement/SQL target that.

**Comment by Bingonymous** [comment]
Hello lime, no I pushed for a reason to that here to fix that now for the old versions too.
And no my "base" is the current Skript main repo

**Comment by Bingonymous** [comment]
[Fixes issue that {test::%%} would be handeled the same like {test::*}.](https://github.com/SkriptLang/Skript/pull/6487/commits/556616feb92321cfe9228475594ea0b7e6d04c1f)

Thathere is because of the SQL Wildcards for LIKE

**Comment by Bingonymous** [comment]
Hello guys, where can I find the code that triggers the save() method?
`delete {var::*}` runs it multiple times, where can I find that

**Pull request closed without merging**
