### PR TITLE
Added armorstand pose expression and test

### PR DESCRIPTION
**Pull request by TFSMads**
### Description
Added armorstand pose expression and a test for the expression.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/6597

### CODE REVIEW

**Review by sovdeeth — CHANGES_REQUESTED** [review]
I'm not a big fan of how this is implemented. To my knowledge, converting an euler angle to a single directional vector loses the entire roll axis, which is pretty important to have. I would rather see this implemented with either 
a) a yaw, pitch, roll inputs
b) a direction + roll input

I'd prefer the first but i see how the second could be more versatile, and of course, both can also be useful.

**Comment by TFSMads** [comment]
I'm going on vacation tomorrow but i can implement support for roll when i get home.

**Comment by Pikachu920** [comment]
could you also seperate the pattern please? it makes it easier to read on the docs. you could probably group similar things like left/right arm still

**Comment by sovdeeth** [comment]
@TFSMads Do you intend to continue this PR?

**Comment by sovdeeth** [comment]
Closing due to inactivity

**Pull request closed without merging**
