### PR TITLE
on jump

### PR DESCRIPTION
**Pull request by 3meraldK**
Add on jump event

### CODE REVIEW

**Comment by ShaneBeee** [comment]
I’m not entirely sure what this is. But it sure isn’t a pr

**Comment by TPGamesNL** [comment]
> Add on jump event

I'm gonna assume this was a suggestion, not a PR. There already is a jump event: https://skriptlang.github.io/Skript/events.html#jump (Paper only).
If you want to create an issue next time, use [this](https://help.github.com/en/articles/creating-an-issue)

**Comment by 3meraldK** [comment]
> > Add on jump event
> 
> I'm gonna assume this was a suggestion, not a PR. There already is a jump event: https://skriptlang.github.io/Skript/events.html#jump (Paper only).
> If you want to create an issue next time, use [this](https://help.github.com/en/articles/creating-an-issue)
yes but add on jump event so you dont have to use paperspigot

**Comment by noftaly** [comment]
Then make an issue

**Comment by TPGamesNL** [comment]
> yes but add on jump event so you dont have to use paperspigot

That would be up to Spigot to add an event for it, Skript is only here to support the Spigot API, which doesn't have a jump event.

**Comment by Wealthyturtle** [comment]
> > yes but add on jump event so you dont have to use paperspigot
> 
> That would be up to Spigot to add an event for it, Skript is only here to support the Spigot API, which doesn't have a jump event.

Not necessarily true, Skript also supports Paper and has some Paper-only features. While Spigot doesn't have a jump event, Paper kinda does (see https://papermc.io/javadocs/paper/1.14/com/destroystokyo/paper/event/player/PlayerJumpEvent.html)

**Comment by TPGamesNL** [comment]
> > > yes but add on jump event so you dont have to use paperspigot
> > 
> > 
> > That would be up to Spigot to add an event for it, Skript is only here to support the Spigot API, which doesn't have a jump event.
> 
> Not necessarily true, Skript also supports Paper and has some Paper-only features. While Spigot doesn't have a jump event, Paper kinda does (see https://papermc.io/javadocs/paper/1.14/com/destroystokyo/paper/event/player/PlayerJumpEvent.html)

I'm aware, I should've said that Skript supported the Spigot API and Paper API. But, the question was for it to not need Paper, which is not up to Skript to handle, it's up to Spigot to add a jump event, if they wish, only then will it be added to Skript for non-Paper users.

**Comment by Wealthyturtle** [comment]
Agreed

**Pull request closed without merging**
