### PR TITLE
Rework function system

### PR DESCRIPTION
**Pull request by bensku**
### Description
This pull request contains a rework of Skript's function system.

* Reduced code duplication between Function and Signature
* Reworked function loading and unloading to work with namespaces
  * No visible changes to scripts
* Cleaned up and commented code

More testing will be needed before this can be merged.

---
**Target Minecraft Versions:**  any
**Requirements:** none
**Related Issues:** #2337, #2378 and potentially other function-related issues

### CODE REVIEW

**Comment by andrei923** [comment]
What about https://github.com/SkriptLang/Skript/issues/2188

**Comment by Matocolotoe** [comment]
Maybe you could change the error message to "none is given" instead of "but 0 are given" when the function doesn't have enough arguments.

**Comment by noftaly** [comment]
What about function overloading ? #1185 It would have been nice to add this

**Comment by Matocolotoe** [comment]
What about #2345 ?

**Comment by bensku** [comment]
#2188 is out of scope, but foundations for implementing it are done. Same goes for #1185, if we end up implementing it. I'll look at other issues.

**Pull request merged**
