### PR TITLE
Actually add inventory name change support

### PR DESCRIPTION
**Pull request by TheLimeGlass**
Target Minecraft versions: *any means 1.9+*
Related issues: https://github.com/SkriptLang/Skript/issues/1472

Description: Actually add inventory name change support, not "it's suppose to work"

#Pyon 

This whole class needs to be redone, it's actually horrible. Since the inventory name supports both display name and name the code has to be duplicated, this is the same with others, another reason why it's not the greatest expression class.

### CODE REVIEW

**Comment by Snow-Pyon** [comment]
I wasn't the one who added name change support, you can check the git history if you wish.

**Comment by TheLimeGlass** [comment]
> 
> 
> I wasn't the one who added name change support, you can check the git history if you wish.
> 
> Either way, if you keep being that way, I'll just deny the PR. We don't need PRs from someone who acts this way, it is just disrespectful.
You said in the related issue that it should work when there is no connection whatsoever to having any settable relation.

**Comment by Snow-Pyon** [comment]
Thanks for the contribution!

**Comment by Blueyescat** [comment]
**Note:** this didn't `actually add inventory name change support`.

**Pull request merged**
