### PR TITLE
Change uuid default

### PR DESCRIPTION
**Pull request by TheLimeGlass**
### Description
We're going to have to change this default setting at some point. So 2.8 should be the standard. We cannot start changing variables without them being uuid in the first place.

---
**Target Minecraft Versions:** 
**Requirements:** 
**Related Issues:** https://github.com/SkriptLang/Skript/issues/2987

### CODE REVIEW

**Comment by DelayedGaming** [comment]
Do we need a solution for the aftermath of this change? Existing and future variables which depend on `%player%` will be desynced due to different index.

**Comment by AyhamAl-Ali** [comment]
Breaking change?

**Comment by TheLimeGlass** [comment]
> Do we need a solution for the aftermath of this change? Existing and future variables which depend on `%player%` will be desynced due to different index.

We literally cannot fix existing variables. How are we supposed to differentiate a player name from a variable name. The only way is to start making it their UUID always.

**Review by sovdeeth — APPROVED** [review]

**Review by AyhamAl-Ali — APPROVED** [review]

**Comment by Pikachu920** [comment]
okay dont hate me because i totally want this to be the default too, but i'm worried about how breaking this is. can we maybe add some really annoying warnings in 2.8 and then in 2.9 (or even maybe earlier) change the default?

**Comment by sovdeeth** [comment]
I'm going to hate you pikachu, but that does sounds sensible.

**Comment by Pikachu920** [comment]
> I'm going to hate you pikachu, but that does sounds sensible.

image

**Comment by Pikachu920** [comment]
alsoooooo if we're technically targeting 2.8 for this, we could make 2.7 the version with said annoying warnings 😉

**Comment by AyhamAl-Ali** [comment]
> okay dont hate me because i totally want this to be the default too, but i'm worried about how breaking this is. can we maybe add some really annoying warnings in 2.8 and then in 2.9 (or even maybe earlier) change the default?

Could we provide to the user the correct way to migrate manually then? so that no one messes up anything

**Comment by sovdeeth** [comment]
Marked as 2.8 to ensure that we get the warnings into 2.8.

**Pull request merged**
