### PR TITLE
allow pufferfish as entitydata

### PR DESCRIPTION
**Pull request by sovdeeth**
### Description

allows `pufferfish` as entitydata instead of just `puffer fish`

related: https://github.com/SkriptLang/skript-aliases/pull/116

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

### CODE REVIEW

**Comment by Fusezion** [comment]
This doesn't conflict with the item correct? As I believe that's the reason it doesn't exist already

**Comment by sovdeeth** [comment]
> This doesn't conflict with the item correct? As I believe that's the reason it doesn't exist already

not in my testing

**Comment by TheLimeGlass** [comment]
> This doesn't conflict with the item correct? As I believe that's the reason it doesn't exist already

I fixed that, it will reparse if it's incorrect to get the required type.

**Review by TheLimeGlass — APPROVED** [review]

**Comment by sovdeeth** [comment]
> > This doesn't conflict with the item correct? As I believe that's the reason it doesn't exist already
> 
> I fixed that, it will reparse if it's incorrect to get the required type.

are you referring to #5504 ?

**Review by APickledWalrus — APPROVED** [review]

**Review by APickledWalrus — APPROVED** [review]

**Pull request merged**
