### PR TITLE
Remove legacy projectile code

### PR DESCRIPTION
**Pull request by TheDGOfficial**
### Description
Njol probably added them when the parameter type of setShooter method changed to support both old and new method signatures. However, this not necessary anymore and reflection is slower, so I made them direct method calls.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

### CODE REVIEW

**Review by WeeskyBDW — APPROVED** [review]

**Comment by ShaneBeee** [comment]
I feel like a discussion needs to be had here.

Based on this PR you are basically removing all code from these methods, which is great, but at the end of the day, this util class is then rendered useless. 
Personally I vote to just remove the class, and directly use the appropriate methods wherever these ones are used.

That said, there IS a chance it might break some addon that was abandoned 2+ years ago, where they are oddly using this class. 
Maybe its time to kill some old, abandoned addons?!?!

I can't image any addon using this, unless the addon was create before these methods were changed in Bukkit... I have no clue.

**Comment by TheDGOfficial** [comment]
Agree with that. Committed a new version that removes the class altogether. The commit can be reverted if the other way around is desired.

**Comment by ShaneBeee** [comment]
> Agree with that. Committed a new version that removes the class altogether. The commit can be reverted if the other way around is desired.

As long as no addons are using this class, there is no reason to keep it. So I think your change is for the best.

That said, if an addon IS using it, I have no clue why they would be relying on Skript for something like this.

**Review by ShaneBeee — DISMISSED** [review]
Im going to approve this, because I feel its a good change.
That said, Im not going to merge yet, going to give the other devs a chance to look/reply/etc.

**Review by WeeskyBDW — DISMISSED** [review]

**Review by APickledWalrus — DISMISSED** [review]

**Review by Wealthyturtle — APPROVED** [review]

**Pull request merged**
