### PR TITLE
Add newline literal

### PR DESCRIPTION
**Pull request by JRoy**
### Description
Adds a newline expression which has been missing in vanilla skript for way too long.

---
**Target Minecraft Versions:** N/A
**Requirements:** N/A
**Related Issues:** N/A

### CODE REVIEW

**Comment by Pikachu920** [comment]
In my opinion, this shouldn't be an expression (at least solely). It's essentially a formatting thing such as <bold> or <red>, so <new line> and <nl> seems nicer to me and others I've discussed this with

**Comment by FranKusmiruk** [comment]
@Pikachu920 I was personally going to implement this as a chat code, and have `<nl>`. The issue with that is, the chat code API isn't made to be used this way, I believe it should but since expanding it would take a considerable amount of time no one is going to spend on, I am fine with this being a literal for now.

Also, parsing `\n` in string literals could also be a good idea. Of course, that would require hardcoding it onto the string parsing code but we could add an API or at least a better way to do it internally later.

**Comment by bensku** [comment]
This has been discussed elsewhere in past. The main problem with adding this is that Minecraft may or may not like new line characters in many places where new lines *are* supported. For example, item lore is likely going to be problematic.

**Comment by JRoy** [comment]
Closing this because I deleted the repo this pull request was on, reopening with lore support in a bit.

**Pull request closed without merging**
