### PR TITLE
Add Hex Color Support

### LINKED ISSUE #3106: 'uncoloured message' doesn't remove §x
### Description
When trying to uncolour a message in the new hex colour code system, the opening §x is not removed from the result, making it difficult to work with hex coloured messages.

### Steps to Reproduce
```
on chat:
    send "%uncoloured message%"
```
Then send hex coloured message in chat
(See screenshot for resulting behaviour)

### Expected Behavior
§x should be treated as a colour code, and removed from 'uncoloured message'

### Errors / Screenshots
As you can see, the 'x' is left in
http://prntscr.com/tckvt7
(Giraffe was #FF0000, Cubed was &e)

### Server Information
* **Server version/platform:** Paper 1.16.1 (ver 73)
* **Skript version:** 2.5 Alpha 5

### PR DESCRIPTION
**Pull request by APickledWalrus**
### Description
This is a remake of #3078, which I had to close because the conflicts had gotten too complicated for me to fix.
This PR adds hex color support to Skript through a new "color" tag. I have updated the documentation appropriately. Unlike #3078, the tag *should* work everywhere now. I had to make some changes to EffActionBar for colors to work properly there.

This is kind of outside of this PR, but Skript doesn't allow you to do:
`
send title "<RED>Hello %player%!"
`
"RED" must be in lowercase. I'm not sure if this is intentional or not though.
The cause is: https://github.com/SkriptLang/Skript/blob/558e9c64a5024781427c36aa12d808b2cce8ea22/src/main/java/ch/njol/skript/util/Utils.java#L526 in that the string isn't converted to lowercase ("RED" doesn't exist in the map, but "red" does).

---
**Target Minecraft Versions:**     1.16+
**Requirements:**     1.16+
**Related Issues:**     Fixes #3106

### CODE REVIEW

**Comment by APickledWalrus** [comment]
Okay, so I removed the need to format it with "color/hex/c" so you can just write:
`
send "<#123456>Hey there %player%"
`

It *should* be working better now, however it doesn't currently work in tooltips. Not sure if that is something on my end or with Skript/Components

**Comment by APickledWalrus** [comment]
With that commit, tooltips are now properly colored and the linked issue has been fixed.

**Comment by APickledWalrus** [comment]
> 
> 
> LGTM but I believe we had an issue by using bungee chat API internally in some Spigot versions that didn't ship with it, are you sure this works all the way down 1.9.4?

That will need tested, but I would assume so since EffActionBar uses it.

**Comment by FranKusmiruk** [comment]
Further testing will be done by users in the future betas, thanks for the contribution.

**Comment by Thrasilias** [comment]
> Okay, so I removed the need to format it with "color/hex/c" so you can just write:
> `send "<#123456>Hey there %player%"`
> 
> It _should_ be working better now, however it doesn't currently work in tooltips. Not sure if that is something on my end or with Skript/Components
> 
> EDIT: Test failed, but it wasn't an issue with this PR.

stolen code fom my translator :omegaconcernPanda:

**Comment by APickledWalrus** [comment]
@Thrasilias wat

**Comment by Thrasilias** [comment]
That was sarcasme. I use <#rrggbb> in my own java code :)

**Pull request merged**
