### PR TITLE
Event value selection improvements

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
The code:
```
every second:
	set {_p} to event-player
	message "test"
```
gives the following errors:
```
There's no world in a periodic event if no world is given in the event (e.g. like 'every hour in "world"') (script.sk, line 8: set {_p} to event-player')
There's no world in a periodic event if no world is given in the event (e.g. like 'every hour in "world"') (script.sk, line 9: message "test"')
```
Which aren't the right errors. This happens because `EventValues.getEventValueGetter` has a fourth check, which goes over all event-values possible, and attempts if they're applicable using converters. It also checks if the event class is excluded for the iterated event-value, printing an error and returning null if so. This is done before checking if there is any converter for the given event-value, which causes the event-value event class exclusion check to take priority, which shouldn't be done, because it prints an error. This error will override the default error, that there's no such event-value for the given event. 
With this PR, the errors are:
```
There's no player in a periodical event (script.sk, line 8: set {_p} to event-player')
There's no player/console in a periodical event (script.sk, line 9: message "test"')
```

One point of concern: should the check for event exclusion always return null if it failed, instead of continuing the event-value iteration? This didn't make much sense to me, but I assumed it was there for a reason.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3499

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
Yes this makes sense, but this could break potential event-values or change their priorities causing more errors.

**Comment by TPGamesNL** [comment]
This PR now also fixes the error in #3499

**Review by APickledWalrus — APPROVED** [review]
This looks okay to me. As for your concern in the description, I think it is okay or return null there as the getter has been found (and I don't think it has caused any noticeable issues yet lol)

If @TheLimeGlass' concerns are addressed in some way, this should be good to go :)

**Comment by TPGamesNL** [comment]
@APickledWalrus While the getter has been found in this case, that doesn't mean there aren't other event values that are able to satisfy the conditions.

@TheLimeGlass Can you take another look? I didn't fully understand your previous review, since all this does (at least, the first commit) is make the loop `continue` earlier if no getter was found, which won't break anything or change the order, it only makes it so it doesn't error and return falsely.

**Comment by TheLimeGlass** [comment]
I can review and test later tomorrow

**Comment by TheLimeGlass** [comment]
I ran into no issues with my tests, for a future test when the EffSpawn syntax becomes a Section we can utilize this
```
test "event-value-converting":
	spawn a pig at spawn of "world":
		assert event-entity is a pig
		set {_test} to event-entity
		assert {_test} is set
		set {_location} to event-location
		assert distance between spawn of "world" and {_location} is less than 2
		delete {_test}
```

**Pull request merged**
