### PR TITLE
caseEquals Function

### PR DESCRIPTION
**Pull request by Wealthyturtle**
### Description
Adds a new caseEquals JavaFunction as per previous discussions. This function will take in a list of Strings, and iterate through the String array to check if each element is strictly equals to the next element, with case sensitivity.

This PR contains both a function test for this new function, and also fixes the previous ExprStringCase expression test since case sensitivity comparisons were not ensured in that test by default.

---
**Target Minecraft Versions:**     Any
**Requirements:**     None
**Related Issues:**     None

### CODE REVIEW

**Comment by Wealthyturtle** [comment]
Please help me check that my test file names are correct :)

**Comment by Blueyescat** [comment]
yes lets move everything to functions

**Comment by bensku** [comment]
@Blueyescat We may revisit this later. Right now, we needed something for test scripts.

@Wealthyturtle Merge master into this branch, I want Github Actions to run tests before merge.

**Comment by Blueyescat** [comment]
please don't include that in releases

**Comment by Wealthyturtle** [comment]
@bensku I merged master into my branch... but I did it in my fork and not the SkriptLang repo for ease of editing.

**Comment by bensku** [comment]
My mistake @Wealthyturtle. Github Actions won't run on PRs unless you explicitly request it to do so.

**Comment by bensku** [comment]
I ended up moving caseEquals() to be only available in tests.

**Comment by bensku** [comment]
Manually merged with some conflicts :)

**Pull request closed without merging**
