### PR TITLE
Rework CondContains

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Includes fixes for CondContains, such as:
- make it not calling expression getters multiple times per execution
- don't make exceptions for variables

This PR should be tested thoroughly, because it's a (almost complete) rewrite of the class, which could definitely break things.
Three syntaxes were removed:
- `[the] list [of] %objects% (doesn't|does not|do not|don't) contain %objects%`
- `[the] list [of] %objects% contain[s] %objects%`
- `(all|1¦any|2¦none) of %strings% contain[s] %strings%`

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #2439, #3014, #3874

### CODE REVIEW

**Review by FranKusmiruk — COMMENTED** [review]
Just marking code style issues

**Comment by FranKusmiruk** [comment]
> * don't make exceptions for variables

the fact that CondContains had exceptions for things such as variables is the fact that it was very slow (see https://github.com/SkriptLang/Skript/issues/1369), do your changes take care of this performance issue?

Also, why were the other syntaxes removed?

**Comment by TPGamesNL** [comment]
> the fact that CondContains had exceptions for things such as variables is the fact that it was very slow (see #1369), do your changes take care of this performance issue?

I tried the code from #1369, but could not replicate their results even on 2.5.3, so I presume that was fixed already. 
Code: https://pastebin.com/1SXMESn3
Result (PR build):
image
Result (2.5.3):
image

> Also, why were the other syntaxes removed?

The other syntaxes were removed because there no longer had a purpose to me:
`[the] list [of] %objects% (doesn't|does not|do not|don't) contain %objects%` and `[the] list [of] %objects% contain[s] %objects%` are only here to force an `OBJECTS` contains check, but this should already be properly handled by the rest of the code. The `(all|1¦any|2¦none) of %strings% contain[s] %strings%` did serve some purpose, but it has been replaced with other code as well, except for the `any` check: the code `"ab" or "cd" contain "c"` is supposed to work, but an `ExpressionList` where `ExpressionList#getAnd()` returns false is considered single, so it selects a random value to return. If I should edit 
`CondContains` to work around this behaviour, tell me.

**Review by FranKusmiruk — APPROVED** [review]

**Comment by startree236** [comment]
```
if mid contain "_" or "기본공격" or "비약" or "기타-도약" or "피버" or "신의$축복":
		stop
```
This syntax doesn't work well.
Is there any workaround?

**Comment by TPGamesNL** [comment]
> ```
> (1)
> if mid contain "_":
> 		stop
> ```
> 
> ```
> (2)
> if mid contain "_" or "기본공격" or "비약" or "기타-도약" or "피버" or "신의$축복":
> 		stop
> ```
> 
> The second syntax doesn't work very well.
> Is there any workaround?

Did you try the PR build, or a release?

**Comment by startree236** [comment]
> > ```
> > (1)
> > if mid contain "_":
> > 		stop
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > (2)
> > if mid contain "_" or "기본공격" or "비약" or "기타-도약" or "피버" or "신의$축복":
> > 		stop
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The second syntax doesn't work very well.
> > Is there any workaround?
> 
> Did you try the PR build, or a release?

I am using PR build.

**Comment by TPGamesNL** [comment]
> > > ```
> > > (1)
> > > if mid contain "_":
> > > 		stop
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > (2)
> > > if mid contain "_" or "기본공격" or "비약" or "기타-도약" or "피버" or "신의$축복":
> > > 		stop
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The second syntax doesn't work very well.
> > > Is there any workaround?
> > 
> > 
> > Did you try the PR build, or a release?
> 
> I am using PR build.

Since this is merged, this conversation should belong in an issue (#4046)

**Pull request merged**
