### PR TITLE
Fix BlockIgniteEvent 

### PR DESCRIPTION
**Pull request by kyoshuske**
### Description

(edited)
`event-block` in event `BlockIgniteEvent` (`on ignite`) should return `getBlock()` instead of `getIgnitingBlock()`

issue occurred on:
- skript: 2.9.2
- engine:  paper-1.21.1-122

---
**Target Minecraft Versions:** any
**Requirements:** none 
**Related Issues:** none

### CODE REVIEW

**Comment by Efnilite** [comment]
you should add a CI test for this. feel free to ask if you're not sure how to do this in the discord

**Comment by TheAbsolutionism** [comment]
I'm a bit curious as to why it was made like that in the first place. The `getIgnitingBlock()` returns the block that caused the event-block to catch on fire. So obviously, if it was caught on fire by flint and steel it would be null.
If anything, a custom expression should've been made to use the `getIgnitingBlock()`.
Also, there's no reason to have this event value anymore, since the super class `BlockEvent` has the `getBlock()`

**Comment by TheAbsolutionism** [comment]
It was added 7 years ago by LimeGlass, so maybe back then, that's how it used to be? Not sure

**Comment by kyoshuske** [comment]
> I'm a bit curious as to why it was made like that in the first place. The `getIgnitingBlock()` returns the block that caused the event-block to catch on fire. So obviously, if it was caught on fire by flint and steel it would be null. If anything, a custom expression should've been made to use the `getIgnitingBlock()`. Also, there's no reason to have this event value anymore, since the super class `BlockEvent` has the `getBlock()`
my bad i didnt notice that `getIgnitingBlock()` returns something different than `getBlock()`
but still in my opinion the event-block should return the block that is getting ignited, not the block that is causing it

**Review by Moderocky — APPROVED** [review]

**Review by sovdeeth — APPROVED** [review]

**Pull request merged**
