### PR TITLE
Suppress bed colour setting exception on newer server versions

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Suppresses the exception, unless verbosity is set to 'very high', in which case it re-throws it.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #2931

### CODE REVIEW

**Comment by APickledWalrus** [comment]
My only worry is that users will be confused why they can't set the color of a bed this way. Do you think it be difficult to change the actual block but preserve its block states?

**Comment by TPGamesNL** [comment]
> My only worry is that users will be confused why they can't set the color of a bed this way. Do you think it be difficult to change the actual block but preserve its block states?

That would also be possible, but I personally preferred Shane's way, disallowing it completely because Bukkit doesn't allow it either. However, I also see that because this used to work on lower MC versions, we should make this backwards compatible by setting the material of the block, so I'll make the change anyway.

**Comment by TPGamesNL** [comment]
> That would also be possible, but I personally preferred Shane's way, disallowing it completely because Bukkit doesn't allow it either. However, I also see that because this used to work on lower MC versions, we should make this backwards compatible by setting the material of the block, so I'll make the change anyway.

Nvm, too much blockdata trouble (direction, both halves etc) for backwards compat

**Review by APickledWalrus — APPROVED** [review]
Should be fine 😎

**Pull request merged**
