### PR TITLE
Adds new spawn reasons for 1.21

### PR DESCRIPTION
**Pull request by EquipableMC**
### Description
This simply adds support for ominous item spawner for spawn reasons, which was approved very recently in [#10897](https://github.com/PaperMC/Paper/pull/10897) in paper.

Edit:
This also adds support for potion effects, which was approved the day before paper 1.21 became stable in [#11102](https://github.com/PaperMC/Paper/pull/11102)

---
**Target Minecraft Versions:** 1.21
**Requirements:** 1.21 paper
**Related Issues:** image

### CODE REVIEW

**Review by sovdeeth — APPROVED** [review]

**Review by TheLimeGlass — APPROVED** [review]

**Review by TheLimeGlass — CHANGES_REQUESTED** [review]
There is now also `potion effect` as a spawn reason as of Yesterday, the day before Paper released 1.21. Can that be added here?

**Comment by EquipableMC** [comment]
> There is now also `potion effect` as a spawn reason as of Yesterday, the day before Paper released 1.21. Can that be added here?

yeah, I'll add it now

**Review by TheLimeGlass — APPROVED** [review]

**Comment by APickledWalrus** [comment]
might be worth testing how this interacts with like:
```
set {_var} to some potion effect
if {_var} is a potion effect:
```

**Comment by EquipableMC** [comment]
> might be worth testing how this interacts with like:
> 
> ```
> set {_var} to some potion effect
> if {_var} is a potion effect:
> ```

oh yeah good call let me test now

**Comment by APickledWalrus** [comment]
some quick testing indicates that for:
```
set {_var} to some potion effect
if {_var} is a potion effect:
```
it works fine for `a potion effect`, not for `potion effect`. i don't imagine this would have a major impact (and this is already likely an issue with other types).

**Pull request merged**
