### PR TITLE
ExprTarget - Fix not being able to delete target entity

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
This PR is to fix an issue with deleting a target entity.
When running the code:
```vb
delete target entity of player
```
nothing happens. This fixes that, win win for everyone 👍 

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #2695

### CODE REVIEW

**Comment by ShaneBeee** [comment]
Closing this for now, needs a re-work

**Comment by bensku** [comment]
What does deleting targets of other entities do? Does it delete them, or just make the targeting entity target something else?

**Comment by ShaneBeee** [comment]
> What does deleting targets of other entities do? Does it delete them, or just make the targeting entity target something else?

It just sets their target as null, and Im thinking they must just randomly pick another target.
I tested with the a zombie, something like:
```vb
on target:
    if entity is a zombie:
        if target of entity is a player:
            delete target of entity
```
the zombie just stood there and ignored me.

**Comment by bensku** [comment]
The issue with this PR is that it will cause remove effect to do different things depending on whose target is removed. If a code (e.g. function) accidentally got a player as parameter, unexpected entity removal could happen.

**Comment by ShaneBeee** [comment]
> The issue with this PR is that it will cause remove effect to do different things depending on whose target is removed. If a code (e.g. function) accidentally got a player as parameter, unexpected entity removal could happen.

Very good point. I'm going to close this for now and try think of a new way to go about doing this.

**Pull request closed without merging**
