### PR TITLE
Update contributing.md

### PR DESCRIPTION
**Pull request by Moderocky**
### Description
Improvements to the code of conduct.

Adds details about what to expect during the review phase, and clears up some old information.

### CODE REVIEW

**Review by AyhamAl-Ali — APPROVED** [review]
Nice.

**Review by TPGamesNL — APPROVED** [review]

**Comment by TheLimeGlass** [comment]
I think you should keep the notice stating that two or more team reviews needs to pass in order for the pull request to be merged.

**Comment by Moderocky** [comment]
> I think you should keep the notice stating that two or more team reviews needs to pass in order for the pull request to be merged.

That may have been removed by mistake, I was intending to move it to the end section on merging - I'll check the file itself.

**Comment by TheLimeGlass** [comment]
I think you should include a note stating that they don't have to keep the pull request up to date with the master unless it has conflicts. We'll update to master before merging. This helps the developer cherry-picking if we have to port it to other versions to avoid commit searching.

**Comment by Moderocky** [comment]
Would you prefer that here or in the code conventions file?

**Comment by TheLimeGlass** [comment]
> Would you prefer that here or in the code conventions file?

Here, it's this discussion.

**Review by TheLimeGlass — APPROVED** [review]

**Pull request merged**
