### PR TITLE
1.21 Support

### PR DESCRIPTION
**Pull request by APickledWalrus**
### Description
This PR intends to add support for Minecraft 1.21.

I have added a new testing environment for Paper 1.21. Skript compiled without issue (at the time of writing this).

However, without this PR, Skript fails to load on Paper 1.21 (and presumably any further new releases) due to ItemStack changes. ItemStacks can no longer represent block-only materials (that is, materials such that `!Material#isItem`). This is only more of a push for us to make strong changes regarding the ItemType/ItemStack/BlockData trio, but an ideal fix would likely require a significant time investment to completely rework the alias/ItemType system.

Fortunately, I have managed to get Skript loading and tests passing without *too* many changes. One significant change is that `ItemStack#getRandom` is now nullable. There is no way to avoid this. There are now likely instances of unsafe getRandom usage that need fixed (I have not taken the time to resolve this yet). Internally, it is now the case that an ItemData *may not* have an ItemStack. This item stack was likely unused in many cases as these datas represented blocks. With all of these changes, this PR needs extensive testing to determine how

---
**Target Minecraft Versions:** 1.21+, though these ItemType/ItemData changes apply to all versions (which we may want to discuss)
**Requirements:** none 
**Related Issues:**
- https://github.com/SkriptLang/Skript/issues/6796

### CODE REVIEW

**Review by Moderocky — APPROVED** [review]

**Review by ShaneBeee — APPROVED** [review]
I know my approval doesn't count, but I'm throwing my 2 cents in.
I've been using this PR since you put it up, and I've yet to see any issues.

While my testing may not have been extensive, I have done a fair bit of fiddling with items/blocks and I haven't noticed anything weird nor have I had any errors.

**Comment by PetyXbron** [comment]
Yeah! This works perfectly for me. Great work! Big up

**Comment by Moderocky** [comment]
> Works perfectly for me aswell, please merge it, so auto update works instead of using a custom version

The next public beta is scheduled for the 1st of July (in 3 days) where you'll be able to download it from the GitHub. There'll be about 15 days for people to review and give feedback before the next stable version is released after that. You can find more information in our release document and readme :)

**Review by sovdeeth — APPROVED** [review]

**Comment by sovdeeth** [comment]
related? #6830

**Comment by APickledWalrus** [comment]
Likely, ill take a look

**Comment by itfoldy** [comment]
Can any of you build this version and link it as a .jar, so we don't have to do it ourselves, thank you

**Comment by APickledWalrus** [comment]
> Can any of you build this version and link it as a .jar, so we don't have to do it ourselves, thank you

This is automatically done 🙂 You can download the nightly build artifact from here: https://github.com/SkriptLang/Skript/actions/runs/9702144977

**Comment by sovdeeth** [comment]
The exp orb merge regression test is failing in a novel way, which seems unrelated to the changes here. Perhaps Paper 1.21 doesn't merge xp as aggressively?

**Comment by sovdeeth** [comment]
> FYI @sovdeeth regarding this:
> 
> > The exp orb merge regression test is failing in a novel way, which seems unrelated to the changes here. Perhaps Paper 1.21 doesn't merge xp as aggressively?
> 
> The defaults were reduced in a recent Paper commit [here](https://github.com/PaperMC/paper/commit/1f5db504244fe6563ab32cee646dad0c53360e01).
> 
> I've used this branch in my 1.21 testing with no issues so far -- thanks/great work team!

yeah, we (I) couldn't figure out how to edit the configs in the test servers so i just disabled it for now.

**Pull request merged**
