### PR TITLE
🛠 Support multiple players in `CondPlayedBefore`

### PR DESCRIPTION
**Pull request by AyhamAl-Ali**
### Description

Just another Skript Moment \:D
This PR makes CondPlayedBefore support multiple players

---
**Target Minecraft Versions:** All
**Requirements:** None
**Related Issues:** None

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
I have a suggestion to switch this over to a PropertyCondition which has support for PropertyType.HAVE

**Review by TheLimeGlass — CHANGES_REQUESTED** [review]
I have a suggestion to switch this over to a PropertyCondition which has support for PropertyType.HAVE

**Comment by AyhamAl-Ali** [comment]
> I have a suggestion to switch this over to a PropertyCondition which has support for PropertyType.HAVE

It's a good suggestion but unfortunately we can't use it on this condition because it has  these words `did, did not, didn't` and removing them would be an unnecessary breaking change

**Review by TheLimeGlass — APPROVED** [review]
Alright then, I would vote to remove the did and didn't change and reflect apon it in the changelog, as it's not entirely proper grammar.

**Comment by TPGamesNL** [comment]
`if the player did not player on this server yet` sounds fine to me, especially if we need to make a breaking change if we think otherwise

**Review by APickledWalrus — APPROVED** [review]

**Pull request merged**
