### PR TITLE
Add Vector-Number Arithmetic back

### PR DESCRIPTION
**Pull request by UnderscoreTud**
### Description
This PR readds vector-number arithmetic back to Skript

---
**Target Minecraft Versions:** any
**Requirements** none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/4253

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
The original reason vector arithmetic was removed was because it was destroying performance. We're going to need to have performance timings and I suggest adding tests.

**Comment by AyhamAl-Ali** [comment]
If this feature impacts the performance in any kind I wouldn't support implementing it.
IMO users should use the vector function instead to return a proper vector to be used in vector arithmetics.

**Comment by bluelhf** [comment]
> If this feature impacts the performance in any kind I wouldn't support implementing it.
> IMO users should use the vector function instead to return a proper vector to be used in vector arithmetics.

I imagine the performance degradation issues were specifically with the number—vector converter, and not with number support in the syntax itself.

**Comment by UnderscoreTud** [comment]
Closed in favor of #5203

**Pull request closed without merging**
