### PR TITLE
Update Paper API

### PR DESCRIPTION
**Pull request by Burbulinis**
### Description
Update Paper API to 1.21.4

---
**Target Minecraft Versions:** 1.21.4 
**Requirements:** none 
**Related Issues:** none

### CODE REVIEW

**Comment by Fusezion** [comment]
Wanna do test environment while you're doing this

**Comment by NotSoDelayed** [comment]
Should we really be updating it this soon? The only thing Skript will be missing is the new features where it might take a bit to be added into Skript, especially the next expected release is in less than a month from now.

**Comment by sovdeeth** [comment]
> Should we really be updating it this soon? The only thing Skript will be missing is the new features where it might take a bit to be added into Skript, especially the next expected release is in less than a month from now.

well the whole point of updating the dependency is so that new features are available to add

**Review by sovdeeth — APPROVED** [review]

**Review by APickledWalrus — APPROVED** [review]

**Review by Moderocky — APPROVED** [review]

**Comment by ShaneBeee** [comment]
Correct me if Im wrong, but you updated Paper API, created a new test, but never implemented the test anywhere??!?

**Comment by sovdeeth** [comment]
> Correct me if Im wrong, but you updated Paper API, created a new test environment, but never implemented the environment anywhere??!?

The tests automatically run on any environments within their folder. Given minecraft's larger releases, it might be worth keeping minor update test environments around.
But the latestEnv should def be updated.

**Comment by ShaneBeee** [comment]
> The tests automatically run on any environments within their folder.

yeah I realized that shortly after I hit send, silly me.

> Given minecraft's larger releases, it might be worth keeping minor update test environments around. But the latestEnv should def be updated.

Thats probably a good idea yeah.

**Pull request merged**
