### PR TITLE
Change world parsing

### PR DESCRIPTION
**Pull request by TheLimeGlass**
### Description
Change world parsing to disallow what https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprWorldFromName.java should be doing. We cannot have a classinfo doing the same functionality as an expression. A classinfo is called first, and way more frequent than an expression.

In my opinion, you should not be able to parse a World. A World is basically a String input which is what ExprWorldFromName handles.

This will improve performance and solve a conflict issue Skript has of picking which one to use.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** https://github.com/SkriptLang/Skript/issues/5827

### CODE REVIEW

**Comment by AyhamAl-Ali** [comment]
wouldn't this break events like `every 2 seconds in the world "world"` or `on at 12:00 in the world "world"`?
Also, the syntax only allows `world "world"` not `world world` I am not sure how it was working before!

**Comment by Mr-Darth** [comment]
What exactly does this fix? Issue #5827, which this PR claims to solve, is not fixed by this. I've already described what the actual problem (if we can even call it that) is in the linked issue; there is nothing wrong with world parsing.

All this PR does is remove, for no apparent reason, literal world parsing in scripts (which is needed in places like events).

> We cannot have a classinfo doing the same functionality as an expression. 

Why? There is nothing wrong with this.

> A classinfo is called first, and way more frequent than an expression.

Classinfo literals are generally attempted last.

> This will improve performance and solve a conflict issue Skript has of picking which one to use.

I don't really see where the performance improvement would come from. I also don't see any conflict, since type literals are tried last.

**Comment by TheLimeGlass** [comment]
> All this PR does is remove, for no apparent reason, literal world parsing in scripts (which is needed in places like events).
Events are addressed and unchanged.

> Classinfo literals are generally attempted last.
ClassInfos are the first to get parse checked. The parse method of ClassInfos has a mass amount of attempts.

> I don't really see where the performance improvement would come from. I also don't see any conflict, since type literals are tried last.
Less frequent calling and sending into the ClassInfo as stated in my last statement.

**Comment by UnderscoreTud** [comment]
As has been stated already, this does not fix the actual issue. It literally accomplishes nothing.

Classinfo literals are attempted last, so ExprWorldFromName will take precedence when it is the case.

**Comment by TheLimeGlass** [comment]
> As has been stated already, this does not fix the actual issue. It literally accomplishes nothing.
> 
> Classinfo literals are attempted last, so ExprWorldFromName will take precedence when it is the case.

Incorrect. ClassInfo's are always parsed first. Skript needs to understand the type being placed into the expression. Debugging any classinfo parse method will show that literally everything goes through this method.

**Comment by Moderocky** [comment]
So I've done a bit of testing with this,

> wouldn't this break events like `every 2 seconds in the world "world"` or on `at 12:00 in the world "world"`?

these both appear to still work and

> Also, the syntax only allows world "world" not world world I am not sure how it was working before!

something like `every 2 seconds in the world world` doesn't work on either this branch or the current master build.

However, it also doesn't seem to fix the behaviour that was written in the mentioned issue.

Honestly, at this point, I'm not sure whether it does what it's supposed to but the behaviour isn't described accurately, or whether it doesn't do what it's supposed to (in which case I don't really know what it does do) either way, I think we would all appreciate some clarification about:
1. What does this fix? (I'd love a before/after example!)
2. Is it a breaking change? (If so, what does it break?)

**Comment by sovdeeth** [comment]
Closing due to 6+ months of inactivity

**Pull request closed without merging**
