### PR TITLE
Make event values return item stacks instead of item types if possible

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Makes some event values return ItemStacks instead of ItemTypes, since that is more direct. 
The issue in #4109 was caused by the event-value getter first converting the ItemStack to an ItemType, and after that it got converted back to an ItemStack, where the reference got lost, as the converter called ItemType#getRandom, which clones the ItemStack.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #4109

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
Haven't we done this in the past and it caused more issues then we could count?

**Comment by TPGamesNL** [comment]
@Wealthyturtle would you be able to weigh in on this (because of https://github.com/SkriptLang/Skript/pull/2510)?

**Comment by Wealthyturtle** [comment]
> @Wealthyturtle would you be able to weigh in on this (because of #2510)?

I think this change is fine since it fixes conversion between ItemStack and ItemType (so long as it doesn't break other stuff)

**Comment by TPGamesNL** [comment]
> I think this change is fine since it fixes conversion between ItemStack and ItemType (so long as it doesn't break other stuff)

Well this PR itself doesn't fix any conversion, but there is a ItemStack -> ItemType converter which should do this:
https://github.com/SkriptLang/Skript/blob/d8b1d526df67b5e2ee89cb6efccca1780ed8a73f/src/main/java/ch/njol/skript/classes/data/DefaultConverters.java#L206-L218
But I'm not sure if the converters are always checked, so it could still give issues. If this gets tested properly, it should be fine.

**Review by APickledWalrus — APPROVED** [review]
I think we are fine to trial this out for the 2.7 alphas

**Pull request merged**
