### PR TITLE
🚀 Making function param rules stricter for the better

### PR DESCRIPTION
**Pull request by AyhamAl-Ali**
### Description

Today is another day making Skript making more sense 🙃

# Old Behaviour

After playing around with #6358 we found out that function parameters actually have almost zero limitation and @sovdeeth was generous enough to provide the weirdest valid param examples, enjoy it:
```v
function testA(loc): location, previoustype(): text):
    broadcast "a"

function testB(loc(: location, previoustype): text):
    broadcast "b"

function testE(loc: location, previoustyp): returns text: object = (")")):
    broadcast "%{_loc}% %{_previoustyp): returns text}%"

function this((function should(not: exist) returns text:) ? object : text) :: text:
    return {_(function should(not: exist) returns text:) ? object }

function never(gonna: give = (you - up)): and function never(gonna: let, you: down) :: text):
    broadcast {@magic}

function testA3(previoustyp): returns text: object = (")")):
	broadcast 2
```

Actually, these all make no sense so we decided to rectify them :)

# New Behaviour
Welcome to the new function param rules

It is correct that variables do accept many forms of names but it's very odd to have those forms in function param and due to the parser limitation we are better off stricting this to make it easier for the parser.

Functions parameters will now only accept Alphanumeric, whitespace, period, underscore and a dash (regex: `[\w .-]`)

[Regex101 playground](https://regex101.com/r/gClXj9/2)

How they error now:
image

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
The test that needs to be fixed, still errors
```
 [23:27:11 INFO]: [Skript] Line 4: (../../../../../../src/test/skript/tests/syntaxes/expressions/ExprStringCase.sk)
[23:27:11 INFO]:     List is missing 'and' or 'or', defaulting to 'and': "Oops!", "OOPS!"
[23:27:11 INFO]:     Line: assert caseEquals(capitalised "Oops!", "OOPS!") is true with "capitalised failed"
```

**Comment by AyhamAl-Ali** [comment]
> The test that needs to be fixed, still errors
> 
> ```
>  [23:27:11 INFO]: [Skript] Line 4: (../../../../../../src/test/skript/tests/syntaxes/expressions/ExprStringCase.sk)
> [23:27:11 INFO]:     List is missing 'and' or 'or', defaulting to 'and': "Oops!", "OOPS!"
> [23:27:11 INFO]:     Line: assert caseEquals(capitalised "Oops!", "OOPS!") is true with "capitalised failed"
> ```

This PR is not meant to fix this issue. Though, I and the team have discussed this case when I was working on this PR and we agreed that this is intentional due to how confusing it may be, especially since skript users are new to programming and its tricks and using extra parentheses won't hurt but rather keeps the code readable.

**Comment by AyhamAl-Ali** [comment]
> The test that needs to be fixed, still errors
> 
> ```
>  [23:27:11 INFO]: [Skript] Line 4: (../../../../../../src/test/skript/tests/syntaxes/expressions/ExprStringCase.sk)
> [23:27:11 INFO]:     List is missing 'and' or 'or', defaulting to 'and': "Oops!", "OOPS!"
> [23:27:11 INFO]:     Line: assert caseEquals(capitalised "Oops!", "OOPS!") is true with "capitalised failed"
> ```

This wasn't within the scope of this PR. Though what's the behaviour expected in that case?

**Review by sovdeeth — APPROVED** [review]

**Review by APickledWalrus — APPROVED** [review]

**Review by sovdeeth — APPROVED** [review]
nice work

**Review by Moderocky — APPROVED** [review]

**Pull request merged**
