### PR TITLE
Pure Functions

### PR DESCRIPTION
**Pull request by kiip1**
### Description
This PR aims to add simplification of pure functions, these functions have no side effects and give their output depending on just the input. The simplification will reduce function calls and later on help with other simplifications.

Examples:
```vb
# pure
function sqrt(x: number) :: number:
  return {_x} ^ 0.5

# not pure
function counter(x: number) :: number:
  add 1 to {counter}
  return {_x} * {counter}
```

For now this only works with Java functions--for Skript functions this is hard as there would need to be a tracker of every syntax element and whether they disturb the purity of a function.

Parameters do not get simplified since it could break a lot of stuff (and it did with the expression & literal list, which is why I removed that), the codebase is not yet ready for general expression simplification.

### CODE REVIEW

**Review by sovdeeth — APPROVED** [review]

**Review by sovdeeth — APPROVED** [review]

**Review by Moderocky — APPROVED** [review]
Looks like a good idea

**Review by Moderocky — CHANGES_REQUESTED** [review]
This will need its conflicts fixing before merge.

**Comment by sovdeeth** [comment]
Do you still intend to work on this?

**Comment by kiip1** [comment]
@sovdeeth I currently don't have the time / willpower to work on this, if anyone wants to take it over feel free to do so.

**Comment by sovdeeth** [comment]
closing due to inactivity, though others are encouraged to revive it.

**Pull request closed without merging**
