### PR TITLE
Fix world difficulty not spawning monsters

### PR DESCRIPTION
**Pull request by AyhamAl-Ali**
### Description

Fix world difficulty not spawning monsters sometimes after changing from peaceful to others

---
**Target Minecraft Versions:**  All
**Requirements:** 
**Related Issues:**  #3834

### CODE REVIEW

**Comment by TPGamesNL** [comment]
I don't think this is an issue with Skript, but rather something with Spigot/Paper

**Comment by AyhamAl-Ali** [comment]
> I don't think this is an issue with Skript, but rather something with Spigot/Paper

It is not Skript's issue, I had to decompile `/difficulty` command class command and found out that they used the same method, and after they change the difficulty they set the `spawnFlag`.

**Comment by TPGamesNL** [comment]
> It is not Skript's issue, I had to decompile `/difficulty` command class command and found out that they used the same method, and after they change the difficulty they set the `spawnFlag`.

Then it should still be fixed in Spigot/Paper instead of Skript, unless they specifically say plugins should do this themselves, but that'd surprise me. I recommend you make a small plugin that calls the difficulty changing method and report it to Spigot/Paper

**Comment by AyhamAl-Ali** [comment]
> > It is not Skript's issue, I had to decompile `/difficulty` command class command and found out that they used the same method, and after they change the difficulty they set the `spawnFlag`.
> 
> Then it should still be fixed in Spigot/Paper instead of Skript, unless they specifically say plugins should do this themselves, but that'd surprise me. I recommend you make a small plugin that calls the difficulty changing method and report it to Spigot/Paper

I agree with you, they should do that in `setDifficulty` method.
I will report that to their issues tracker however, until then I think we better stick with our hotfix what you say?

**Comment by TPGamesNL** [comment]
> I agree with you, they should do that in `setDifficulty` method.
> I will report that to their issues tracker however, until then I think we better stick with our hotfix what you say?

I think it'd be better to wait for the change in Paper/Spigot (if Skript development were faster a hotfix would be fine)

**Comment by AyhamAl-Ali** [comment]
> > I agree with you, they should do that in `setDifficulty` method.
> > I will report that to their issues tracker however, until then I think we better stick with our hotfix what you say?
> 
> I think it'd be better to wait for the change in Paper/Spigot (if Skript development were faster a hotfix would be fine)

Fair enough.

**Comment by AyhamAl-Ali** [comment]
https://github.com/PaperMC/Paper/issues/5546

**Comment by FranKusmiruk** [comment]
surprisingly enough, Paper declared this behavior as intended and deferred it to upstream (Spigot), knowing them they will probably leave it like that. We'll just merge workaround and call it a day.

**Review by FranKusmiruk — APPROVED** [review]

**Pull request merged**
