### PR TITLE
Add testing environment to dev/2.6

### PR DESCRIPTION
**Pull request by TheLimeGlass**
### Description
Add the new testing environment to dev/2.6 so we can build docs, test legacy versions and test regression.

Notes:
- 1.12.2 is in both Java 8 and Legacy tests. 1.12.2 works fine no errors, and is considered a legacy version.
- Legacy workflows currently errors, unsure if we're going to address that, or if I should just remove the Legacy workflow.
- genDocs doesn't work on dev/2.6 branch. That's fine.

### CODE REVIEW

**Comment by APickledWalrus** [comment]
We should definitely get Legacy Java 8 test working for this. I'm not sure if it's due to Skript issues (or just tests not checking the Minecraft version), but we should do what we can to get them working (even if it means disabling some tests IMO)

**Comment by TheLimeGlass** [comment]
> We should definitely get Legacy Java 8 test working for this. I'm not sure if it's due to Skript issues (or just tests not checking the Minecraft version), but we should do what we can to get them working (even if it means disabling some tests IMO)

Well you're the one that worked on Item comparison, do you have a clue why this serialization doesn't match in 1.9.4-1.11.2
```
java.lang.AssertionError: diamond sword named BOB (class ch.njol.skript.aliases.ItemType) != diamond sword named BOB (class ch.njol.skript.aliases.ItemType): [89, 103, 103, 0, 0, 1, -128, 8, 105, 116, 101, 109, 116, 121, 112, 101, -122, 3, 97, 108, 108, 15, 0, 5, 116, 121, 112, 101, 115, -128, 9, 65, 114, 114, 97, 121, 76, 105, 115, 116, -127, 6, 118, 97, 108, 117, 101, 115, 48, -128, 6, 79, 98, 106, 101, 99, 116, -128, 1, -128, 11, 78, 101, 119, 73, 116, 101, 109, 68, 97, 116, 97, -121, 7, 105, 115, 65, 108, 105, 97, 115, 15, 0, 5, 112, 108, 97, 105, 110, 15, 0, 4, 109, 101, 116, 97, -128, 34, 67, 111, 110, 102, 105, 103, 117, 114, 97, 116, 105, 111, 110, 83, 101, 114, 105, 97, 108, 105, 122, 97, 98, 108, 101, 95, 73, 116, 101, 109, 77, 101, 116, 97, -127, 5, 118, 97, 108, 117, 101, 32, -128, 94, 118, 97, 108, 117, 101, 58, 10, 32, 32, 61, 61, 58, 32, 73, 116, 101, 109, 77, 101, 116, 97, 10, 32, 32, 109, 101, 116, 97, 45, 116, 121, 112, 101, 58, 32, 85, 78, 83, 80, 69, 67, 73, 70, 73, 67, 10, 32, 32, 100, 105, 115, 112, 108, 97, 121, 45, 110, 97, 109, 101, 58, 32, 66, 79, 66, 10, 32, 32, 108, 111, 114, 101, 58, 10, 32, 32, 45, 32, 76, 79, 82, 69, 49, 10, 32, 32, 45, 32, 76, 79, 82, 69, 50, 10, 9, 105, 116, 101, 109, 70, 108, 97, 103, 115, 3, 0, 0, 0, 2, 10, 105, 115, 65, 110, 121, 116, 104, 105, 110, 103, 15, 0, 2, 105, 100, 3, 0, 0, 0, -22, 8, 105, 116, 101, 109, 70, 111, 114, 109, 15, 0, 6, 97, 109, 111, 117, 110, 116, 3, 0, 0, 0, 1, 4, 105, 116, 101, 109, 0, 10, 103, 108, 111, 98, 97, 108, 77, 101, 116, 97, 0, 5, 98, 108, 111, 99, 107, 0]
	at ch.njol.skript.registrations.Classes.serialize(Classes.java:735) ~[?:?]
	at ch.njol.skript.variables.Variables.serialize(Variables.java:548) ~[?:?]
	at ch.njol.skript.variables.Variables.serialize(Variables.java:542) ~[?:?]
	at ch.njol.skript.variables.Variables.saveVariableChange(Variables.java:552) ~[?:?]
	at ch.njol.skript.variables.Variables.setVariable(Variables.java:385) ~[?:?]
	at ch.njol.skript.variables.Variables.setVariable(Variables.java:376) ~[?:?]
	at ch.njol.skript.lang.Variable.set(Variable.java:467) ~[?:?]
	at ch.njol.skript.lang.Variable.change(Variable.java:523) ~[?:?]
	at ch.njol.skript.effects.EffChange.execute(EffChange.java:282) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:56) ~[?:?]
	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:142) ~[?:?]
	at ch.njol.skript.SkriptEventHandler.access$000(SkriptEventHandler.java:53) ~[?:?]
	at ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:71) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.4.jar:git-Paper-775]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.4.jar:git-Paper-775]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.9.4.jar:git-Paper-775]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.9.4.jar:git-Paper-775]
	at ch.njol.skript.Skript$1.lambda$run$0(Skript.java:631) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:58) [patched_1.9.4.jar:git-Paper-775]
	at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:795) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-775]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-775]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by TPGamesNL** [comment]
Those aren't the only problems:
image

**Comment by TheLimeGlass** [comment]
> Those aren't the only problems: image

I know, it'll fix the potion aliases.

Do you know why the lingering potion is erroring for 1.11? That was recently a pull request from yourself.

**Comment by TPGamesNL** [comment]
Just tested it, it's a potion alias issue, `lingering potion of healing` gives a lingering water bottle:
image
Metadata gives it an UNCRAFTABLE tag, nothing about healing

**Review by AyhamAl-Ali — APPROVED** [review]

**Pull request merged**
