### PR TITLE
Remove Location -> Chunk Converter

### PR DESCRIPTION
**Pull request by NotSoDelayed**
### Description
The Location -> Chunk converter was introduced in #5447 to make use of event locations as event chunks, which it may cause inaccurate event chunk results, fixed in #5965, but the converter was not removed prior to that PR.
This PR removes it to prevent any further unexpected behaviour, such as using location parameters in expressions accepting chunks.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
Is there any information that this solves anything, what are the related issues?

**Comment by DelayedGaming** [comment]
Adding converters may break anything in Skript as they are sensitive when it comes to allow other expressions which are not meant to be converted.
This converter was only added to allow `event-chunk` to work. Now that the proper event values for those are added, why not undo the converter?

**Review by AyhamAl-Ali — APPROVED** [review]

**Review by sovdeeth — APPROVED** [review]

**Comment by sovdeeth** [comment]
We may want to wait on this until 2.9, though, as it is technically a breaking change, to my knowledge. 
```
all blocks within location(0,0,0)
```

**Comment by Moderocky** [comment]
> We may want to wait on this until 2.9, though, as it is technically a breaking change, to my knowledge.
> 
> ```
> all blocks within location(0,0,0)
> ```

If this currently fetches all the blocks in the chunk, which I'm assuming it does from context, this seems like _extremely_ unintended behaviour and I'm very happy to call that a mistake and allow this in the patch version.

**Comment by sovdeeth** [comment]
> > We may want to wait on this until 2.9, though, as it is technically a breaking change, to my knowledge.
> > ```
> > all blocks within location(0,0,0)
> > ```
> 
> If this currently fetches all the blocks in the chunk, which I'm assuming it does from context, this seems like _extremely_ unintended behaviour and I'm very happy to call that a mistake and allow this in the patch version.

Good point. I'd agree.

**Review by Moderocky — APPROVED** [review]

**Pull request merged**
