### PR TITLE
Better chest inventory syntax

### PR DESCRIPTION
**Pull request by iPlexy**
Adjusted the chest inventory syntax for beeing more user friendly

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
I don't agree with this change. If you're going to use the term `new` it must have `a new` with it. This is proper grammar.

If you want to use a direct static statement like that don't include new
```
set {_chest} to chest inventory with 5 rows
```

**Comment by iPlexy** [comment]
Yes i understand your point. Its just that neither the users nor the helpers know whats wrong when someone's got this "error"

**Comment by AyhamAl-Ali** [comment]
> I don't agree with this change. If you're going to use the term `new` it must have `a new` with it. This is proper grammar.
> 
> If you want to use a direct static statement like that don't include new
> 
> ```
> set {_chest} to chest inventory with 5 rows
> ```

In various places in skript the `a` is optional `[a]` even tho in most places it's not grammatically correct, adding to that, users are used to the `a` as optional so in such case if they get an error they might not really understand it

**Comment by TheLimeGlass** [comment]
> > I don't agree with this change. If you're going to use the term `new` it must have `a new` with it. This is proper grammar.
> > If you want to use a direct static statement like that don't include new
> > ```
> > set {_chest} to chest inventory with 5 rows
> > ```
> 
> In various places in skript the `a` is optional `[a]` even tho in most places it's not grammatically correct, adding to that, users are used to the `a` as optional so in such case if they get an error they might not really understand it

Not combined with the word `new`

**Review by TPGamesNL — APPROVED** [review]

**Review by AyhamAl-Ali — APPROVED** [review]

**Comment by iPlexy** [comment]
Helo :(

**Comment by AyhamAl-Ali** [comment]
> Helo :(

Heilo \:) don't worry a merging wave will begin soon™

**Review by APickledWalrus — COMMENTED** [review]
I don't really like Skript's usage of the word `new` in syntax.

`set {_var} to new chest inventory` is just odd compared to `set {_var} to a chest inventory` I think

Perhaps it would be worth having more discussion on this?

**Pull request merged**
