### PR TITLE
Fix 'no scripts found' warning displaying with a config line

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Before PR:
image
This line in the config is unrelated, and it doesn't need to be displayed with the warning.
After PR:
image

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
Does it still say `All scripts loaded without errors.` before the no scripts found info line? I think that line should be removed too or modified if no scripts were found as it's not loading anything aside from config if that's included.

**Comment by TPGamesNL** [comment]
The config isn't included, but that'd be out of scope for this PR

**Review by Moderocky — APPROVED** [review]

**Comment by Pikachu920** [comment]
instead of manually overriding the current node by creating a new LogEntry, could we update the config parser so that it resets the current node (SkriptLogger#getNode) to null when it finishes with the last node?

**Comment by TPGamesNL** [comment]
> instead of manually overriding the current node by creating a new LogEntry, could we update the config parser so that it resets the current node (SkriptLogger#getNode) to null when it finishes with the last node?

Good idea, done 👍 

I could've made the change global for all SectionNode iteration, but that seems like a bad idea cause it looks to be deliberately made to set it to the SectionNode itself, so it'd probably break something:
image

**Pull request merged**
