### PR TITLE
UUID string to Entity (#1352)

### PR DESCRIPTION
**Pull request by TheLimeGlass**
**Related issues:** https://github.com/SkriptLang/Skript/issues/1352

**Description:** Bukkit has a method to get the entity from a UUID now. This has been tested and these may now be executed, and no lag when tested:
```
broadcast name of uuid of player
```

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
**Update:** Variables don't work for some reason... Looking into that.

**Comment by Snow-Pyon** [comment]
I don't think this is actually a good way to do this and any object -> string converters oftenly cause more troubles than what they solve. I'd suggest just adding the ability to parse an uuid as entity in the parser of the Entity's classinfo.

**Comment by TheLimeGlass** [comment]
It's string -> entity. I found no problems except this new thing Bensku just added past week.

**Comment by Pikachu920** [comment]
string to whatever converters cause a lot of issues, you should just allow it in the parser if the parse context is command

**Comment by TheLimeGlass** [comment]
Why though? I don't like that idea but what would the difference be. I tested with a few things and I got no errors from those tests. This works pretty good except for this random error which is new.

It's easier to use. You just place the yuid in a string and Skript handles the rest. Pretty simple in my opinion.

**Comment by bensku** [comment]
I attempted to implement this at some point. It broke literally everything. Extensive testing is required before we can merge.

**Comment by TheBentoBox** [comment]
"1.13 shit" shouldn't be in this PR

**Comment by TheLimeGlass** [comment]
Ya I know, talked about it on the Skript developers chat

**Comment by TheLimeGlass** [comment]
I pulled to master forgetting this was active, it's just a converter though
```
	// Entity - String (UUID)
		Converters.registerConverter(String.class, Entity.class, new Converter<String, Entity>() {
			@Override
			@Nullable
			public Entity convert(String input) {
				UUID uuid = UUID.fromString(input);
				Entity entity = uuid != null ? Bukkit.getEntity(uuid) : null;
				return entity != null ? entity : null;
			}	
		});
```

**Comment by Pikachu920** [comment]
closing this, then since it now contains a unrelated commit and a converter is not the right tool for this anyways

**Pull request closed without merging**
