### PR TITLE
EffCancelEvent - update player inventory after cancelling

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
This PR aims to fix an issue when cancelling inventory click and closing inventories... ghost items appearing.
After cancelling an inventory click event, and closing the inventory... the item may visually appear in the player's inventory, and won't update til the player interacts with it.
This forces the inventory to update after cancelling.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #5342

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
You're supposed to use this method when the inventory click event is cancelled, not when closing the inventory. The server already updates the player's inventory when the server closes it.

**Comment by ShaneBeee** [comment]
> You're supposed to use this method when the inventory click event is cancelled, not when closing the inventory. The server already updates the player's inventory when the server closes it.
> 
> The client item is because an inventory close event done by **the player** isn't notified to the server.

that sounds fair, I have now changed this to update the inventory in the cancel event effect!

**Comment by TheLimeGlass** [comment]
I do agree with this change, but this is essentially forcing this practice. When Skript does logic for the scripter, I think there should maybe be a configuration to disable this behavior if needed.

**Comment by AyhamAl-Ali** [comment]
Just a question, could this break anything when a player interacts with any inventory? Just because I don't know what `Player#updateInventory` exactly does internally

**Comment by ShaneBeee** [comment]
> Just a question, could this break anything when a player interacts with any inventory? Just because I don't know what `Player#updateInventory` exactly does internally

That method internally just sends an inventory update packet to the player. This way if there's any ghost items in their inventory (client side), it will sync the inventory up.

**Review by AyhamAl-Ali — APPROVED** [review]

**Review by APickledWalrus — APPROVED** [review]
Should be good

**Review by TheLimeGlass — APPROVED** [review]

**Pull request merged**
