### PR TITLE
Move CondMinecraftVersion from tests.runner -> conditions

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
This PR movies the CondMinecraftVersion condition from the test environment to Skript, allowing anyone to use it.
This could be useful for someone who is creating a script with cross version support

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

### CODE REVIEW

**Comment by APickledWalrus** [comment]
What do you think about changing the pattern? I don't think the current one would fit super well.

Something like:

`[the] [server] [(is|(is not|isn't)] (running|[running] on) [minecraft] [version] %string%`
e.g.
```haskell
if the server is running minecraft "1.15.2":
if the server isn't on version "1.13.2":
```

**Comment by ShaneBeee** [comment]
Probably a good idea yeah. Ill work on a change.

**Comment by FranKusmiruk** [comment]
This really doesn't help considering the code is executed regardless and thus display errors. The only way this would've useful for cross-version support is to make it so any code within the section be only executed on the specified minecraft versions

**Comment by ShaneBeee** [comment]
going to go about this a different way

**Pull request closed without merging**
