### PR TITLE
Add newline literal

### PR DESCRIPTION
**Pull request by JRoy**
### Description
Continuation of #2131 but adds newline support to lores.

Test Script:
New lines work on everything below unless noted otherwise. These features do not support new lines and cannot be retrofitted to accept them.
```
command /test:
  trigger:
    set {_item} to dirt
    set name of {_item} to "line 1%nl%line 2" #This will not work, new lines are not supported here
    set lore of {_item} to "line 1%nl%line 2" and "4"
    add "1%nl%2" and "3" to lore of {_item}
    give player {_item}
    set player's tab list header to "line 1%nl%line 2%nl%line 3"
    set player's tab list footer to "line 1%nl%line 2%nl%line 3"
    set player's display name to "%nl%line 1%nl%line 2%nl%"
    send action bar "line 1%nl%line 2" to player #This will not work, new lines are not supported here
    send title "line 1%nl%line 2" with subtitle "line 1%nl%line 2" to player #This will not work, new lines are not supported here
    broadcast "line 1%nl%line 2"
    make player say "line 1%nl%line 2"
    message "line 1%nl%line 2" to player
    set the display name of the player's target entity to "line 1%nl%line 2" #This will not work, new lines are not supported here
    kick the player due to "line 1%nl%line 2%nl%line 3"
```

Description of #2131:
> Adds a newline expression which has been missing in vanilla skript for way too long.

---
**Target Minecraft Versions:** N/A
**Requirements:** N/A
**Related Issues:** #1424 #2474

### CODE REVIEW

**Comment by Wealthyturtle** [comment]
Related issues are #1424 and #2474 btw :P Have you tried testing this newline literal with ban/kick reasons? Would be nice to have them working in those instances too

**Comment by JRoy** [comment]
Ban and kick reasons uses newlines so they work :p

**Comment by JRoy** [comment]
@Wealthyturtle There you go.

*god I hate line endings*

**Comment by ShaneBeee** [comment]
Thank you for your contribution 👍

**Comment by bensku** [comment]
I forgot to leave a comment, @ShaneBeee and @Nicofisi, did you thoroughly test this? In particular, I'm worried that this could interfere with chat safety features (and make formatting get escaped instead of used). Another potential problem could be with performance, if this makes literal strings expression strings.

**Comment by ShaneBeee** [comment]
@bensku I tested this back around when Jroy first PRd it. I had no issues and everything seems to work as intended.

**Comment by bensku** [comment]
Nice!

**Pull request merged**
