### PR TITLE
Avoid confusing description

### PR DESCRIPTION
**Pull request by TheLimeGlass**
Fix the description to avoid confusion over how the section works.

---
**Target Minecraft Versions:** any
**Requirements:** none

### CODE REVIEW

**Review by DogLoverPink — APPROVED** [review]

**Comment by DogLoverPink** [comment]
wait oops I didn't realize nons could do that, mb

**Review by TPGamesNL — CHANGES_REQUESTED** [review]
What's the current issue with the description (just speaking of the section part)? The task here is to describe when the section is called. The current description is accurate and it does not use the notation of 'spawn' (which can cause confusion in this context). It also notes that the entity is added to the world after the section has been run.

I don't think focusing on the entity object here makes this less confusing

**Comment by TheLimeGlass** [comment]
To avoid confusion. Here was a question asked in the SkUnity discord after reading the description `in this syntax it says the section is run before the entity is spawned, how can i make an effect section that runs the effect first, then the section?`

**Comment by TPGamesNL** [comment]
I know, I read that conversation, was there for part of it too.
The question asks something about how to use the Section API, it doesn't ask for the description to be changed. 
I don't think a change in description is needed, and I think the change you proposed makes the behavior less clear.

**Comment by Pikachu920** [comment]
> I know, I read that conversation, was there for part of it too. The question asks something about how to use the Section API, it doesn't ask for the description to be changed. I don't think a change in description is needed, and I think the change you proposed makes the behavior less clear.

+1 totally agree that the proposed description is less clear. especially since it uses "object". that may be meaningful to us as devs, but to even many experienced skripters that concept is not clear.

**Comment by TheLimeGlass** [comment]
Do those that object to the change have a proposed wording, because we can't keep the current implementation if it's confusing the users.

**Pull request closed without merging**
