### PR TITLE
Add cloner interface for ClassInfo

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Adds a `Cloner` interfaces to be used for `ClassInfo`s to clone objects before setting variables to those objects, and before passing the objects as function parameters.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3779 #2337 (partially)

### CODE REVIEW

**Comment by FranKusmiruk** [comment]
I think the middleware (the Cloner interface) is not needed here, a boolean like `passedByReference` should be enough, making the clone behaviour the default. You can be sure any class that wants to be cloned will implement Cloneable anyways.

**Comment by TPGamesNL** [comment]
> I think the middleware (the Cloner interface) is not needed here, a boolean like `passedByReference` should be enough, making the clone behaviour the default. You can be sure any class that wants to be cloned will implement Cloneable anyways.

@FranKusmiruk Will making every class that implements/extends `Cloneable` clone by default not cause issues, you think?

**Comment by FranKusmiruk** [comment]
> > I think the middleware (the Cloner interface) is not needed here, a boolean like `passedByReference` should be enough, making the clone behaviour the default. You can be sure any class that wants to be cloned will implement Cloneable anyways.
> 
> @FranKusmiruk Will making every class that implements/extends `Cloneable` clone by default not cause issues, you think?

Yeah, you're right. But I still don't see the usefulness of the Cloner interface, at least in Skript something like this would've been sufficient:
```java

private boolean clone;


/**
* Wether T should be cloned.
* {@code false} by default.
*/
public ClassInfo<T> shouldClone() {
    clone = !clone;
    return this;
}

public ClassInfo<T> shouldClone(boolean clone) {
    this.clone = clone;
    return this;
}

public T clone(T t) {
    return shouldClone == true && t instanceof Cloneable ? ((Cloneable) t).clone : t; // the cast may be unnecessary.
}
```

**Comment by TPGamesNL** [comment]
Another reason I thought an interface for this would be useful, is that a ClassInfo for a class that doesn't belong to the plugin (Skript / addon) that registered it, may not have the Cloneable interface / clone method implemented (e.g. what if ItemStack wasn't Cloneable). The plugin could make a wrapper class for these objects, but I thought it'd be easier to create an interface for this. 

It'll also be easier for the implementation in ClassInfo, since `Object#clone` is protected, and Cloneable doesn't make the method abstract:
image

**Review by FranKusmiruk — APPROVED** [review]

**Pull request merged**
