### PR TITLE
EffTabHead & EffTabFoot (ON HOLD)

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
Added two effects for setting the tablist header and footer for player[s]
Skripters can set 1 string or multiple strings **per** header or footer

---
**Target Minecraft Versions:** 1.13+ due to a new method in the SpigotAPI
**Requirements:** 1.13+
**Related Issues:**  None

### CODE REVIEW

**Comment by Pikachu920** [comment]
why all in one effect? at least do seperate patterns

**Comment by ShaneBeee** [comment]
Which do you think would be better?
Separate effects (Tablist Header / Tablist Footer)
or
Multiple patterns in one effect?

**Comment by Snow-Pyon** [comment]
Didn't Spigot make getters for those too? I'd be better as expression. And in my opinion, it would be better as a single expression with different patterns, and perhaps registering an effect for 1.12 and lower with Paper's Player#setTabHeaderFooter method.

**Comment by TheLimeGlass** [comment]
If Spigot supports getting it should be supported, there is no reason not too, a user might find a usage for it.

I also find this better in one class how you originally had it, there is no need to separate into two classes when it's just a matter of footer and header, they both have the same purpose, and we already have too many effect classes in the effect package, not like that can be changed to be minimalist.

**Comment by ShaneBeee** [comment]
> If Spigot supports getting it should be supported, there is no reason not too, a user might find a usage for it.
> 
> I also find this better in one class how you originally had it, there is no need to separate into two classes when it's just a matter of footer and header, they both have the same purpose, and we already have too many effect classes in the effect package, not like that can be changed to be minimalist. It would be similar to making the changers of expressions into their own effects.

After numerous discussion with Snow and Pikachu and Blue, this has totally been reformatted. 
Im just waiting on them to make one final decision and I will finish it up and push it.
So I guess you could say this is currently on hold. 

Spigot doesnt have anything for this for 1.12.2 and below
Paper has a setter for 1.12.2 and below.
Snow suggested an effect for 1.9+ using paper,
and then an expression for spigot 1.13+ since it has the getter/setter in 1.13+

So thats kind of my plan, just fighting over syntaxes right now ;)

**Comment by ShaneBeee** [comment]
Going to close this for now.
Im going to redo it when I have a chance to delete my fork and re-fork it.
Start with a clean slate

**Pull request closed without merging**
