### PR TITLE
Improve ExprPlayerWeather and add CondHasClientWeather

### PR DESCRIPTION
**Pull request by Nicofisi**
A quick fix for #1408

### CODE REVIEW

**Comment by Nicofisi** [comment]
Wait that's good that it errored, I missed an important part of the code lol

**Comment by Pikachu920** [comment]
do you think it'd make more sense to return the world's weather when there's no client weather?

**Comment by TheBentoBox** [comment]
No, you need to be able to tell if the player has a specific weather that they are being forced to experience. The only way to do so is to have it return `null` if they're not experiencing anything. This also matches the Spigot API (which likely works that way for the same reason -- how do you tell if they have a player-specific weather if `getPlayerWeather()` always returns a weather type?)

**Comment by TheLimeGlass** [comment]
There is a method in Spigot which could be a Skript condition that tests if the player's weather is relative to the servers weather, which should be used instead of this expression for testing the client's weather.

**Comment by Snow-Pyon** [comment]
@TheLimeGlass even if such condition exists, I'd rather leave it in the way it is now. Mainly for convenience and the fact that it'd be pretty confusing the other way around.

Besides, I do agree that this condition should be implemented.

**Comment by TheLimeGlass** [comment]
I never said to remove this, because you still need a way to set the weather. A condition is more standard for checking these kind of things for the user to properly be doing.

**Comment by Pikachu920** [comment]
thanks so!

**Pull request merged**
