### PR TITLE
Fix variable parsing

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
See https://github.com/SkriptLang/Skript/issues/837#issuecomment-739297724

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #837

### CODE REVIEW

**Comment by TPGamesNL** [comment]
The code from this PR will fail in some occasions, example:
`someFunction({_a}, {_b})` -> someFunction with arg: variable `_a} {_b`.

I'll write a simple parser to fix it.

**Comment by ShaneBeee** [comment]
Maybe it would be a good idea to write a detailed regression test for this, to make sure it doesn't break anything.

**Comment by TPGamesNL** [comment]
Is there a testing effect to use that is supposed to fail parsing, so that it fails testing when it does parse correctly?

**Comment by TPGamesNL** [comment]
@ShaneBeee I've added a regression test and I've modified EffAssert so you can make a test that is supposed to fail

**Review by APickledWalrus — APPROVED** [review]
Looks good to me. Another review wouldn't hurt :)

**Pull request closed without merging**
