### PR TITLE
Replace reflective instantiation with supplier

### PR DESCRIPTION
**Pull request by kiip1**
### Description
This PR aims to replace reflective instantiation with suppliers, allowing for constructors to be utilised in syntax elements. There should be no breaking changes, but addon developers will be encouraged to use this.

### Goals
- Get rid of reflection.
- Allow for non-empty constructors in syntax elements.

### Non-Goals
- Force addon developers to use this syntax.

### CODE REVIEW

**Review by Moderocky — COMMENTED** [review]
Looks good. We may be able to find a better alternative for the stack trace call by using the owner of the anonymous supplier class, since that may not have the same issue as SimpleExpression, etc.

I'll check over this again tomorrow before approving it.

**Comment by kiip1** [comment]
Didn't think about that, will try something with that tomorrow.

**Review by Moderocky — CHANGES_REQUESTED** [review]
This will be a good change for the future. :)

I would like you to include `@MarkedForRemoval` for the deprecated versions so that addons have time to update to the new format before we remove the old method.

**Comment by kiip1** [comment]
Wasn't merged yet at the time of making this PR, will deprecate the old versions and add MarkedForRemoval tomorrow, didn't get to it today.

**Review by Moderocky — APPROVED** [review]

**Comment by APickledWalrus** [comment]
Maybe this can be integrated into https://github.com/SkriptLang/Skript/pull/5331 somehow? Large file changes like this are (annoyingly) conflict prone and I'd like to avoid that if possible. Maybe the new methods would take in the supplier and the old deprecated ones could somehow create one (even if it's less efficient, e.g. calling newInstance)

**Comment by kiip1** [comment]
> Maybe this can be integrated into #5331 somehow? Large file changes like this are (annoyingly) conflict prone and I'd like to avoid that if possible. Maybe the new methods would take in the supplier and the old deprecated ones could somehow create one (even if it's less efficient, e.g. calling newInstance)

Will integrate this into #5331. It isn't too much work.

**Pull request closed without merging**
