### PR TITLE
Add tests for vector syntaxes

### PR DESCRIPTION
**Pull request by sovdeeth**
### Description

Adds tests for all vector-related syntaxes. Fixes up some docs/pattern issues with assorted vector syntaxes as well.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #6158

### CODE REVIEW

**Comment by Moderocky** [comment]
Looking good so far, I'm ticking off all the ones you make so that nobody else makes the same.

**Comment by Moderocky** [comment]
As far as I can see, the remaining ones are:
- [ ] ~~ExprLocationFromVector~~ (currently disabled)
- [ ] ExprVectorFromYawAndPitch
- [ ] ExprLocationVectorOffset
- [ ] ExprVectorNormalize
- [ ] ExprVectorSquaredLength
- [ ] ExprVectorOfLocation
- [ ] ExprVectorSpherical
- [ ] ExprVectorXYZ
- [ ] ExprVectorLength

then
- [ ] CondIsVectorNormalized

and
- [ ] EffVectorRotateAroundAnother
- [ ] EffVectorRotateXYZ

**Review by APickledWalrus — APPROVED** [review]
Looks good, just a few minor suggestions

**Review by Moderocky — APPROVED** [review]
Great work.

**Pull request merged**
