### PR TITLE
Delete the src/excluded directory

### PR DESCRIPTION
**Pull request by Nicofisi**
It'll stay in the git history, so why keep it in the normal files?

A pull request to allow discussion

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
Why though... Some of these may be helpful to view. There is no point in removing them other than your fantasy to keep it "clean".

**Comment by Blueyescat** [comment]
https://github.com/Njol/Skript/tree/master/src/excluded

**Comment by Nicofisi** [comment]
> Some of these may be helpful to view. 

> It'll stay in the git history

**Comment by TheLimeGlass** [comment]
That's not a reason to get rid of it.

**Comment by TheLimeGlass** [comment]
There is no point in removing it.

**Comment by TheLimeGlass** [comment]
There is no reason to get rid of it! Like just why would you get rid of it, just to make it look "prettier". Honestly makes no sense.

The LitPi class should be included anyways rather than having to set a variable to Pi Everytime the script starts.

We stray further from Njol everyday meme.

**Comment by Blueyescat** [comment]
We don't need a trash can in this repository.

**Comment by JRoy** [comment]
> There is no reason to get rid of it! Like just why would you get rid of it, just to make it look "prettier". 

There is no reason to keep it, it serves no use currently and hasn't in 2 years. And lime for fuck's sake man, you just arguing for the sake of an argument here. If a file serves no use in a project, you absolutely do get rid of it. Because clean project management is key.

**Comment by Blueyescat** [comment]
Then use Njol's repository... The directory is not used for years and won't be used anymore since there is no reason to use it.

**Comment by JRoy** [comment]
Lime, quit it. You've been using the same excuse every other time and ignoring are "fixes". There is no use for this to be here. You can view Njol's repo if that's what you want. A tidy repository is best practices. Now shut the fuck up

**Comment by JRoy** [comment]
Do you not have any idea of what version control is? The point of git is to store commits so you can view old work and the changes that got to the current code. You'd be defeating the point of version control if we kept fucking everything. Stop bringing up points on how we can "look at the old code," that can already be accomplished by viewing either tag branches or looking through commit history. Projects should be readable, keeping a mess of old files is not readable.

**Comment by Snow-Pyon** [comment]
Please calm down everyone, the PR was made to get input from it. Your opinions are going to be considered at the time of deleting the folder or not but discussing like this isn't going to go anywhere, do yourselves a favor and respect each other opinions on the matter.

**Pull request merged**
