### PR TITLE
Disable watchdog in tests

### PR DESCRIPTION
**Pull request by Pikachu920**
### Description
This PR disables watchdog in the test runner so that watchdog doesn't cause a failure if the tests take too long to run.

---
**Target Minecraft Versions:** any
**Requirements:** a spigot derivative?
**Related Issues:** none

### CODE REVIEW

**Comment by Pikachu920** [comment]
you can see that this works here in this test action: https://github.com/SkriptLang/Skript/actions/runs/7946756004/job/21694839398#step:6:309

instead of being killed by watchdog, the tests continue to run until skript's own test timeout system kills the server

**Comment by TheLimeGlass** [comment]
Watch dog is already disabled https://github.com/SkriptLang/Skript/blob/0bfec0b709cf74bace063d315d0eb501058cac14/src/main/java/ch/njol/skript/test/platform/Environment.java#L249 unless this isn't the path anymore.

**Comment by Pikachu920** [comment]
> Watch dog is already disabled
> 
> https://github.com/SkriptLang/Skript/blob/0bfec0b709cf74bace063d315d0eb501058cac14/src/main/java/ch/njol/skript/test/platform/Environment.java#L249
> 
> unless this isn't the path anymore. Also that's weird, because last time I used the profiler system, I let JProfiler run for 30+ minutes, and the server didn't crash/stop. Are you sure this isn't a GitHub related issue, as GitHub kills runners by default unless it's stated.

hmmm that's interesting. here's an example of watchdog killing the test suite: https://github.com/aabssmc/Skuishy/actions/runs/7852408803/job/21430765810

i'll see if i can find out whats up with that `disable.watchdog` option. it can also supposedly be disabled by setting the timeout to `-1` in the config but neither of these seem to be officially documented.

**Comment by Pikachu920** [comment]
> > Watch dog is already disabled
> > https://github.com/SkriptLang/Skript/blob/0bfec0b709cf74bace063d315d0eb501058cac14/src/main/java/ch/njol/skript/test/platform/Environment.java#L249
> > 
> > unless this isn't the path anymore. Also that's weird, because last time I used the profiler system, I let JProfiler run for 30+ minutes, and the server didn't crash/stop. Are you sure this isn't a GitHub related issue, as GitHub kills runners by default unless it's stated.
> 
> hmmm that's interesting. here's an example of watchdog killing the test suite: https://github.com/aabssmc/Skuishy/actions/runs/7852408803/job/21430765810
> 
> i'll see if i can find out whats up with that `disable.watchdog` option. it can also supposedly be disabled by setting the timeout to `-1` in the config but neither of these seem to be officially documented.

oh i see now, i saw the thread dump and assumed it was watchdog but paper is just printing it because the process was killed

**Pull request closed without merging**
