### PR TITLE
Fix slow variable saving

### PR DESCRIPTION
**Pull request by TheDGOfficial**
#### What it does
Fixes slow variable saving.

#### Why
As per the desearialize method of the OfflinePlayer serializer, it only requires the uuid field when deserializing if the server supports UUIDs. Hence making the save of name field on serialize method useless when UUIDs are supported on the server. As per why this makes variable saving slow, the UUID of every OfflinePlayer is known instantly, but the name data requires getting it from the world data (offline-mode) or Mojang servers (online-mode), and that makes variable saving slow.

#### A small change
This may seem just a small change nothing much but its affect is huge if you have many list variables deeply-nested with player expressions on them, storing serialized OfflinePlayers. My 5 year old server had 730.000+ variables with many of them being like that (don't ask me why i had that many variables, i was writing scripts inexperienced) and it has been shutdowning in 8-10 minutes. After this change, it went to 10 seconds.

#### How I found it
As for how I found this bottleneck, at first I added a variable save tracker like the one that says "Loaded .. variables so far" when loading variables that says "Saved ... variables so far". This confirmed that the freeze when disabling Skript is from variables. And after that I coded a custom implementation of Paper's spike/freeze detector (which also copies Spigot's built-in timeout detector) that also works on shutdown. Paper's and Spigot's timeout/spike/freeze detectors are disabled when plugins are loading or disabling since they all do update checks or saves and the spikes/freezes are expected.

This does not only occur on shutdown since Skript also periodically saves variables to the database on the runtime, too. The runtime saving performance was improved a lot with the commits a30acb9 ,  2b126c7 and bf4abf6 by bensku, however, this will still increase runtime save performance too, i think. The bottleneck may be also cause of many TPS drops or such, but it was only seen on shutdown since it force saves variables and force waits it to end as a primary task, as the runtime save will run when the server is running, i was probably just not noticing it.

#### A final note
Note that, even though I tested this on my server with 730.000+ variables; i didn't test it on production with users. My server was closed long ago, it was just a hobby for me to figure out why it was closing like that when it was still alive. I was thinking this was normal because of high variable amount that I had back in the days. Users should backup their variables before testing this commit/version anyways to be fully safe.

Also note that this change will have no impact on variable save time if you are not using player expressions in variables, or it will not have a seenable improve of variable save performance if your variable save speed is already good.

#### Testing the change
The change can be tested by downloading the nightly build JAR file from here: https://github.com/SkriptLang/Skript/suites/1469761472/artifacts/25277425

Be sure to backup your variables, and keep in mind that this version is only for testing. Provide feedback here if you ran into any issues.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #2100 and maybe others

### CODE REVIEW

**Comment by ShaneBeee** [comment]
Honestly, you could just remove the (uuidSupported) check. UUIDs were added long before 1.9, and this fork of Skript only supports 1.9.4+
So really the check and name stuff could all just be removed from the serializer.

I would keep the name part in the deserializer in the weird random off chance that someone is upgrading their dinosaur server to 1.9.4+

Example of what I would do
```java
@Override
public Fields serialize(final OfflinePlayer p) {
	final Fields f = new Fields();
	f.putObject("uuid", p.getUniqueId());
	return f;
}

@Override
public void deserialize(final OfflinePlayer o, final Fields f) {
	assert false;
}

@Override
public boolean canBeInstantiated() {
	return false;
}

@SuppressWarnings("deprecation")
@Override
protected OfflinePlayer deserialize(final Fields fields) throws StreamCorruptedException {
	if (fields.contains("uuid")) {
		final UUID uuid = fields.getObject("uuid", UUID.class);
		if (uuid == null)
			throw new StreamCorruptedException();
		return Bukkit.getOfflinePlayer(uuid);
	} else {
		final String name = fields.getObject("name", String.class);
		if (name == null)
			throw new StreamCorruptedException();
		return Bukkit.getOfflinePlayer(name);
	}
}
```

**Comment by TheDGOfficial** [comment]
> Honestly, you could just remove the (uuidSupported) check. UUIDs were added long before 1.9, and this fork of Skript only supports 1.9.4+
> So really the check and name stuff could all just be removed from the serializer.
> 
> I would keep the name part in the deserializer in the weird random off chance that someone is upgrading their dinosaur server to 1.9.4+
> 
> Example of what I would do
> 
> ```java
> @Override
> public Fields serialize(final OfflinePlayer p) {
> 	final Fields f = new Fields();
> 	f.putObject("uuid", p.getUniqueId());
> 	return f;
> }
> 
> @Override
> public void deserialize(final OfflinePlayer o, final Fields f) {
> 	assert false;
> }
> 
> @Override
> public boolean canBeInstantiated() {
> 	return false;
> }
> 
> @SuppressWarnings("deprecation")
> @Override
> protected OfflinePlayer deserialize(final Fields fields) throws StreamCorruptedException {
> 	if (fields.contains("uuid")) {
> 		final UUID uuid = fields.getObject("uuid", UUID.class);
> 		if (uuid == null)
> 			throw new StreamCorruptedException();
> 		return Bukkit.getOfflinePlayer(uuid);
> 	} else {
> 		final String name = fields.getObject("name", String.class);
> 		if (name == null)
> 			throw new StreamCorruptedException();
> 		return Bukkit.getOfflinePlayer(name);
> 	}
> }
> ```

Yes, you're right. I didn't remove it for the code consistency (uuidSupported is used in many other places of Skript, too) and to stick to the goal of this PR; but I think that makes sense. I'll commit a change that removes uuid checks in that areas.

**Review by ShaneBeee — APPROVED** [review]
Looks good to me

**Review by ShaneBeee — APPROVED** [review]
I approved this I think 16 days ago. But I changed the branch so my approval got booted. 
Just re-approving.

**Pull request merged**
