### PR TITLE
Fix setting multiple lists in one effect

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Test code:
```
set {_a::*} and {_b::*} to 1, 2 and 3
message "a list: %{_a::*}%"
message "b list: %{_b::*}%"
```

The code in `ExpressionList#change` was originally meant to allow an effect like `set {_a} and {_b} to 1 and 2` (I imagine), but this functionality wasn't reflected by `acceptChange`, so it doesn't work. If this is a feature that is wanted, tell me and I'll add it to this PR.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #1649

### CODE REVIEW

**Comment by FranKusmiruk** [comment]
So this basically makes it so both lists are set to `1, 2, 3` right? As for the question below, I'd rather have a separate effect like `set %objects% to %objects% respectively` for clarity.

**Comment by TPGamesNL** [comment]
> So this basically makes it so both lists are set to `1, 2, 3` right? As for the question below, I'd rather have a separate effect like `set %objects% to %objects% respectively` for clarity.

Yes, without this fix, `{_a::*}` is set to `1` and `{_b::*}` is set to `2`. With the result, both lists are set to `1, 2 and 3`.

**Comment by TPGamesNL** [comment]
The respective setting is outside the scope of this PR, so I've created an issue for it: https://github.com/SkriptLang/Skript/issues/3828

**Review by APickledWalrus — APPROVED** [review]
LGTM

**Pull request merged**
