### PR TITLE
Remove unused repositories from build.gradle

### PR DESCRIPTION
**Pull request by Nicofisi**
Removes 3 commented unneeded maven repos, and one uncommented although it was unneeded too. I'm creating this PR since the uncommented one went down today, making Skript impossible to bulid - https://travis-ci.com/Nicofisi/Skript/builds/78580876 https://i.imgur.com/eRdlFue.png

It'd be best if this was merged ASAP, today

### CODE REVIEW

**Comment by bensku** [comment]
Can someone clear their Maven and Gradle caches and verify that Skript is buildable without this repository? If not, I'll need to dig some jars up.

**Comment by JRoy** [comment]
iirc Travis redownloads every time so if it's successful then it should work

**Comment by Nicofisi** [comment]
@bensku Look at my image linked in OP, Skript is *not* buildable *with* this repository and *is* buildable *without*

**Comment by Nicofisi** [comment]
Let me repeat that this is a rather critical issue since Skript doesn't build with this (unneeded) repo

**Pull request merged**
