### PR TITLE
Ask for player's groups off the main thread.

### PR DESCRIPTION
**Pull request by Moderocky**
### Description

Updates the matched vault version to 1.7.3.

LuckPerms is [a little overzealous and prints a giant error](<https://github.com/SkriptLang/Skript/issues/5692>) when requesting groups on the main thread using the vault hook.
Since `player's group[s]` is an expression Skript doesn't have the option of waiting for it to resolve on a background thread.

My solution was to do the call in a completable future and block while waiting for it to resolve, so it effectively does the same thing as before without triggering the error. \
Obviously this isn't ideal, but it seemed better than trying to disable the LuckPerms check specifically while the server was running.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #5692

### CODE REVIEW

**Review by Pikachu920 — APPROVED** [review]

**Comment by Pikachu920** [comment]
actually, would this cause potential new issues with other APIs that may expect/require the API to be called from the main thread?

**Comment by Moderocky** [comment]
> actually, would this cause potential new issues with other permission plugins that may expect/require the API to be called from the main thread?

No idea, I'm fairly sure PermissionsEx is old enough that it doesn't care but I don't know about any other permissions plugins (if there are any) -- the only report we've had is LuckPerms so we could do it on a different thread iff LuckPerms is present but then that wouldn't fix it if anything else had the same requirement (or if our check didn't catch everything)

**Review by AyhamAl-Ali — APPROVED** [review]
Good work Kenzie ⚡ Let's hope it doesn't break other permission plugins

**Comment by Moderocky** [comment]
If somebody knows what permissions plugins are used currently they could test this.

**Pull request merged**
