### PR TITLE
Make scripts in directories load before rest

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
**Breaking change**

This PR changes the load order of scripts to what you typically see in file explorers: directories first in alphabetical order (recursive), then files in this directory in alphabetical order.

Example:
image

With PR:
image

Without PR:
image

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #466

### CODE REVIEW

**Comment by andrei923** [comment]
seems useful where some scripts might need other scripts to run.
image

**Comment by TheBentoBox** [comment]
Thank god, I can finally fix rename the folders containing my API scripts from `AAPI` to `API` 😅

**Comment by TPGamesNL** [comment]
> This change will break the current script loading logic. Part of working with Skript is working with its 'quirks'. This is one of Skripts quirks. While it's a logical change, this would need to be made aware to users during release because things will likely break.

When this PR is merged, it will be made clear in the release that the loading order of scripts has changed, I was personally thinking of adding a 'breaking changes' section to each release (if it is necessary for that release) that informs users about all of the breaking changes.

**Review by APickledWalrus — APPROVED** [review]

**Review by TheLimeGlass — APPROVED** [review]

**Comment by TheLimeGlass** [comment]
Putting note in releases

**Pull request merged**
