### PR TITLE
Fix chat color stuff with expressions

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Fixed chat color issues by creating ChatMessage.fromParsedString, which only turns color codes with '§' into MessageComponents.
Also copies over color codes from previous components properly.
```
command /test:
	trigger:
		set {_x} to "&bCB"
		message "&aABC %{_x}% AAA"
		message formatted "&aABC %{_x}% AAA"
		message colored "&aABC %{_x}% AAA"
		message "&aABC %{_x}% &eAAA"
		
		message "<##00ff00>A"
		message colored "<##00ff00>A"
		set {_value} to "<##00ff00>A"
		message {_value}
		message formatted {_value}
		message colored {_value}
		message uncolored {_value}
```
image

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #2319, #4276

### CODE REVIEW

**Comment by Moderocky** [comment]
Hello,
Not to renege on what I said earlier, but I think it might be nice if there were some way to preserve the colour of the text with inputs (but as an alternative to the default.)
See the first line:
image
produced from `"&aABC %{_x}% AAA"`.

Do you think it would be viable to have an alternative syntax for this (like we have formatted and uncoloured) ?

**Comment by TPGamesNL** [comment]
> Hello,
> Not to renege on what I said earlier, but I think it might be nice if there were some way to preserve the colour of the text with inputs (but as an alternative to the default.)
> See the first line:
> image
> produced from `"&aABC %{_x}% AAA"`.
> 
> Do you think it would be viable to have an alternative syntax for this (like we have formatted and uncoloured) ?

That's a good idea, but outside the scope of this PR. You should suggest it under #3112

**Review by Moderocky — APPROVED** [review]
LGTM.

> That's a good idea, but outside the scope of this PR. You should suggest it under #3112

Thanks, I will.

**Review by APickledWalrus — APPROVED** [review]

**Comment by vhone** [comment]
```
command /book.test:
	trigger:
		execute command "/give %player% written_book{pages:['["""",{""text"":""message""}, {""text"":""&cmessage""}, {""text"":""<##ff0000>message""}, {""text"":""<##ff000c>message""}]'],title:""book"",author:""""}" by console
```



{""text"":""message""} = good
{""text"":""&cmessage""} = good
{""text"":""<##ff0000>message""} = '§0' is displayed.
{""text"":""<##ff000c>message""} = '§c' is displayed.


The same problem occurs with written book items.
can you fix this too?

**Comment by TPGamesNL** [comment]
No, this is only supposed to work for chat messages, console commands don't even use the same syntax. Check https://minecraft.tools/en/book.php out, you'll see how the hex colour codes works

**Comment by vhone** [comment]
> 아니, 이것은 채팅 메시지에만 사용되도록 되어 있는데, 콘솔 명령어는 심지어 같은 구문조차 사용하지 않는다. https://minecraft.tools/en/book.php를 확인하십시오. 그러면 16진 색 코드가 어떻게 작동하는지 확인하십시오.

Okay. Thank you for answer

**Pull request merged**
