### PR TITLE
Fix false positive 32-bit warning

### PR DESCRIPTION
**Pull request by TheDGOfficial**
### Description
Fixes false positive 32-bit warning on start-up, when using non OracleJDK/OpenJDK JVMs.

To fix this, I reversed the logic to return true when it doesn't contain 32 instead of returning true only when it contains 64 (in java.vm.name property).

Also removes the warning on start-up. Even if user uses 32-bit Java; randomly recommending 64-bit when no stackoverflows happened is useless. It will still recommend when one occurs, though.

Combined with #3798, most StackOverFlowErrors will print their own warning messages and will not call Skript#exception for it; so above point is more correct, printing warning on start-up when no StackOverFlowErrors happened yet is not useful, and if that condition gives false positives, it may annoy users.

Also added JavaDoc to the using64BitJava method since it is public and its behaviour is changed.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3805

### CODE REVIEW

**Comment by TPGamesNL** [comment]
You should probably rename the method to `using32BitJava` (and adjust the code to fit that)

**Comment by TheDGOfficial** [comment]
> You should probably rename the method to `using32BitJava` (and adjust the code to fit that)

Definitely can do that and make the method private too since it is only used on Skript class and wrongly made public in the PR implementing this. Will do and commit.

**Review by Wealthyturtle — APPROVED** [review]
LGTM

**Comment by Pikachu920** [comment]
maybe we can use a more robust method for checking if it's 64 bit like JNA does:
https://github.com/java-native-access/jna/blob/58bc0a00b0789205dca65fe0299e27c5f2f57572/src/com/sun/jna/Platform.java#L187-L202

**Comment by TheDGOfficial** [comment]
That seems a little overkill, in my opinion, except sun and ibm properties, there is bunch of methods, native thingies and such, not sure how to implement it here without adding JNA as a dependency (that is not an option since the library would increase JAR size considerably and I'm sure no one wants to add a dependency just for one thing, which is not the main goal of the project). Plus license and maintainability stuff, better to keep it simple and not just copy-paste code and forget about it.

**Comment by FranKusmiruk** [comment]
> That seems a little overkill, in my opinion, except sun and ibm properties, there is bunch of methods, native thingies and such, not sure how to implement it here without adding JNA as a dependency (that is not an option since the library would increase JAR size considerably and I'm sure no one wants to add a dependency just for one thing, which is not the main goal of the project). Plus license and maintainability stuff, better to keep it simple and not just copy-paste code and forget about it.

I think Pikachu was referring to everything except the Native.POINTER_SIZE check, which can't be done without JNA (it requires usage of C's sizeof to check the pointer size).

**Review by TPGamesNL — APPROVED** [review]

**Pull request merged**
