### PR TITLE
Add inventory update effect

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Adds an effect for updating the player's inventory.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3755

### CODE REVIEW

**Comment by FranKusmiruk** [comment]
I don't like the idea of having users update the inventory, if the inventory needs updating it is mostly because you're doing something wrong and even then, Skript should be handling updating on the syntaxes that need it. That being said, I am not against having this for edge cases but it shouldn't be the standard.

**Comment by TPGamesNL** [comment]
> I don't like the idea of having users update the inventory, if the inventory needs updating it is mostly because you're doing something wrong and even then, Skript should be handling updating on the syntaxes that need it. That being said, I am not against having this for edge cases but it shouldn't be the standard.

I've updated the effects description to reflect this

**Review by FranKusmiruk — APPROVED** [review]

**Comment by TheLimeGlass** [comment]
The Bukkit method basically resends the inventory packet to the player. Newer versions of Minecraft handle desync issues fairly well and this is typically never used anymore.

**Comment by TPGamesNL** [comment]
> The Bukkit method basically resends the inventory packet to the player. Newer versions of Minecraft handle desync issues fairly well and this is typically never used anymore.

We do still support 1.9

**Comment by APickledWalrus** [comment]
While we do support older versions, I think Skript should be handling this internally if needed. If the user is going to do this, they should be doing it through something like skript-reflect IMO.

**Comment by Pikachu920** [comment]
it's been a second, but I think that we may want to reopen this @TPGamesNL @APickledWalrus  Here is my rationale:
1. `Player#updateInventory` has been undeprecated by both Spigot and Paper, so the pattern is (maybe unfortunately) here to stay
2. Skript can't cover all the edge cases perfectly, and having to install skript-reflect to call `updateInventory` is probably a worse experience for a scripter than having to manually write `update player's inventory` 
3. Not having this might lead to scripters adopting weird hacky workarounds instead of installing an addon (e.g. `equip player with player's helmet` will force an inventory update, but makes no sense)

**Comment by TPGamesNL** [comment]
I don't think `Player#updateInventory` has ever been deprecated (at least, not at the time of closing).

Skript has an entire system especially to properly update player's inventory:
https://github.com/SkriptLang/Skript/blob/31bc6c4d5b73fd055535b937e2698c10a086f37d/src/main/java/ch/njol/skript/bukkitutil/PlayerUtils.java#L48-L68
So I don't think we should add this effect; it gives the impression to users that this is a task they should do themselves, and if it's not done automatically by Skript / an addon, they won't report it, even though these are actual issues.

**Comment by Pikachu920** [comment]
that's true, looks like it's been undeprecated since 2016
https://github.com/wysohn/Spigot/blob/e0e1771a6d74ca46433feb0235053eee6f792578/Bukkit-Patches/0026-Undeprecate-Player-updateInventory-V.patch#L19

I still think this would be worth having in Skript, but maybe some other devs can chime in with their opinion

**Pull request closed without merging**
