### PR TITLE
Fix changing to <none> not functional

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Changes `EffChange` so that setting one value to another, where the second value evaluates to `null` (`<none>`), actually deletes the first value instead of not having any effect (I asked on in skript-talk in Discord if this should be the expected behaviour, [this](https://discord.com/channels/135877399391764480/836220457433956362/836962266901118976) was the result).

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3049 (partial)

### CODE REVIEW

**Comment by yhdev7935** [comment]
I wrote the code using these grammatical characteristics, but after this patch, everything needs to be fixed. That's sad.
I used this grammar when I set the default value.
```
command /test [<text>]:
  trigger:
    set {_arg1} to "Hi" # The code length is shorter than "if arg 1 is not set" :D
    set {_arg1} to arg-1
```

**Comment by FranKusmiruk** [comment]
> I wrote the code using these grammatical characteristics, but after this commit, everything needs to be fixed. That's sad. 😢
> I used this grammar when I set the default value.
> However, this commit seems to prevent many unexpected errors. ( Especially in code that uses loop frequently. )
> 
> ```
> command /test [<text>]:
>   trigger:
>     set {_arg1} to "Hi" # The code length is shorter than "if arg 1 is not set" :D
>     set {_arg1} to arg-1
> ```

I am honestly surprised someone managed to take advantage of this, however it is broken behaviour and it should be fixed accordingly.

**Comment by TPGamesNL** [comment]
@yhdev7935  Also take a look at the default value expression: https://skriptlang.github.io/Skript/expressions.html#ExprDefaultValue

**Comment by yhdev7935** [comment]
@TPGamesNL Oh, Thanks. However, the difficulty of debugging will inevitably increase slightly.

**Review by FranKusmiruk — APPROVED** [review]

**Pull request merged**
