### PR TITLE
Make log handler system thread safe

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
This change gives each thread its own `HandlerList`, making it so that two log systems on separate threads won't interfere with each other. 

I see two ways this can break:
1. A log system started on one thread is stopped on another.
   - I don't think this happens anywhere in vanilla Skript and I don't see why an addon would do this, but I can't be sure.

2. A log system is started on one thread, any relies on log entries from another thread.
   - This doesn't happen often in Skript, there's only one instance I can think of: async script loading.
     - _What should happen with async loading_: Skript should create a `RedirectingLogHandler` when the reload command is ran, and stop this log handler when the loading is done. 
     - _What actually happens with async loading_: Because the log handler is started and stopped in the `SkriptCommand` class, the log handler is often stopped before the loading is done, causing the error count to be wrong, and the log to be redirected to console, instead of the command executor. 
     - _What happens with async loading after this change_: Since the log handler is created on a different thread, none of the errors will be redirected to the command executor, and the message will always say it's successful. 
     - See #3743 for more about this

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3453 #1002

### CODE REVIEW

**Comment by TheDGOfficial** [comment]
Any reason why not to use `java.lang.ThreadLocal`?

**Comment by TPGamesNL** [comment]
AFAIK `ThreadLocal` is for a variable for one specific thread, not for a separate variable per thread.
The issue with the RedirectingLogHandler with reload commands should be fixed in another PR (could be yours), since it's already broken without this PR, this PR just makes the behaviour more predictable.

**Comment by TPGamesNL** [comment]
If you want to test the Skript from #3453, use this version of skript-reflect: [skript-reflect-2.2.2-dev.jar.zip](https://github.com/SkriptLang/Skript/files/6103272/skript-reflect-2.2.2-dev.jar.zip)

**Comment by TPGamesNL** [comment]
I've also removed the `ParserInstance` class, since it wasn't used for anything (it was supposed to be used for logging but never implemented)

**Comment by TPGamesNL** [comment]
Closing as https://github.com/SkriptLang/Skript/pull/3924 has been merged, fixing the same issues

**Pull request closed without merging**
