### PR TITLE
Add non-living entity support to CondIsAlive

### PR DESCRIPTION
**Pull request by Blueyescat**
### Description
Adds non-living entity support to the Is Alive condition and improves its code, docs and syntax.

Using "alive" or "dead" on a non-living entity looks weird, even if this is fine since we use `kill` to delete non-living entities in Minecraft and Skript, i still wanted to add some alternative words: "available" and "valid"

---
**Target Minecraft Versions:** Any
**Requirements:** None
**Related Issues:** None

### CODE REVIEW

**Comment by bensku** [comment]
I don't like the idea of calling entities available or not available. Valid and invalid kind of make sense.

**Comment by Blueyescat** [comment]
Really? I'm surprised to hear that o.O

**Comment by bensku** [comment]
Maybe you could clarify when exactly you would use those two in your scripts? Might be that I'm missing the context.

**Comment by NanoDankster** [comment]
"available" and "unavailable" options don't make sense really. This checks whether the entity is ALIVE or not. If you're still going to insist, I'd like you to complete this sentence:
> The entity is available for...

Finish this or agree that "available" and "unavailable" don't make sense for a life condition.

Other than that, the PR is fine. I'd love to see this in the master branch ASAP.

**Comment by Pikachu920** [comment]
I don't like valid or invalid either since those words have a separate meaning in the api: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html#isValid--

**Comment by Blueyescat** [comment]
The wrong thing is name of that method and its wrong description. You can probably find a good syntax with better naming if you figure out what is isValid and want to add it to Skript...

**Comment by FranKusmiruk** [comment]
I'd just remove the additional option to be honest, if we or an addon developer adds a condition that makes use of that method linked by Pikachu, it'd just be troublesome. Alive/dead seems good enough to me.

**Pull request merged**
