### PR TITLE
Add warnings for using %player% without using the UUID config setting.

### PR DESCRIPTION
**Pull request by sovdeeth**
### Description

As a precursor to #5676, we need to add warnings to users to warn them of the incoming changes. This PR adds a warning whenever an expression with a `Player` return type is used in a VariableString, if the `use UUIDs in variable names` config option is false.

It directs users to https://github.com/SkriptLang/Skript/discussions/6270 to learn more about how to address the warning.

Ideally, this prompts players to switch to UUIDs through the config, but forcing them to use `player's name` is also an acceptable outcome. 

Critique on the warning's content and the explanatory discussion post is welcome.

image

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #5676

### CODE REVIEW

**Comment by Fusezion** [comment]
Is this on local variables and anyway to disable it without swapping to uuid? I have global temp vars I don't need a uuid for

**Comment by BaeFell** [comment]
> Is this on local variables and anyway to disable it without swapping to uuid? I have global temp vars I don't need a uuid for

Doesn't changing the config option also change it in local variables?

**Comment by sovdeeth** [comment]
> Is this on local variables and anyway to disable it without swapping to uuid? I have global temp vars I don't need a uuid for

Yes, this does apply to local variables too. We could disable the warning for those, but you really should be using `player's name` if you intend to use the player's name specifically.

**Comment by BaeFell** [comment]
Should there be a config option to disable this warning? Similar to the variable conflict warning?

**Comment by Fusezion** [comment]
I'll agree on using players name but I also prefer being lazy

**Comment by sovdeeth** [comment]
> Should there be a config option to disable this warning? Similar to the variable conflict warning?

I considered that, but I fear users would just disable the warning and get slapped in the face when we do change it.

**Comment by BaeFell** [comment]
> > Should there be a config option to disable this warning? Similar to the variable conflict warning?
> 
> I considered that, but I fear users would just disable the warning and get slapped in the face when we do change it.

Fair point. It's not gonna be forever to be fair, so makes sense not to have an option to turn it off.

**Review by BaeFell — APPROVED** [review]
I like this error message and the linked article about migrating.

**Comment by AyhamAl-Ali** [comment]
I read the discussion and all good but I wonder about offlineplayer usage in variables as well, is it also affected by the change? if so the warning should account for that as well

**Comment by sovdeeth** [comment]
> I read the discussion and all good but I wonder about offlineplayer usage in variables as well, is it also affected by the change? if so the warning should account for that as well

Good catch, thanks! They're affected in the exact same way as Players, so I'll include them in the warning.

**Review by AyhamAl-Ali — APPROVED** [review]

**Review by APickledWalrus — APPROVED** [review]

**Pull request merged**
