### PR TITLE
Fix issue with Nexus repo + PreciousStones

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
So it appears the nexus repo has gone down, which is causing builds to fail with PreciousStones.
For funsies, I took it out just to see what would happened, and the build started working. Goes to show this repo is not needed.

This PR is to fix said issue, so builds will start to build again.

Open for discussion :)

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

### CODE REVIEW

**Comment by JRoy** [comment]
Are you sure? It may be cached locally. Try removing your Gradle caches and see if it builds

**Comment by ShaneBeee** [comment]
> Are you sure? It may be cached locally. Try removing your Gradle caches and see if it builds

The issue isn't building on my computer, thats always working, its the Java CI build that stopped working.

**Comment by Wealthyturtle** [comment]
Seems like this PR can be closed since the Nexus repo is back up. I requested a bunch of re-runs on the Java CI for other PRs and they passed.

**Comment by ShaneBeee** [comment]
ah, ok, good to know its back up! I thought it was a goner.

**Comment by Wealthyturtle** [comment]
Uhhh it's back again. @ShaneBeee

**Pull request merged**
