### PR TITLE
Properly name PotionEffectType in lang

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
This PR aims to properly name the PotionEffectType in lang.

A few years back I did a change in the class info, from potion -> potion effect type
I think I forgot to do the lang.

This rename is more precise to the actual name of the class.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

### CODE REVIEW

**Review by APickledWalrus — APPROVED** [review]
This seems okay to me. I think this is only used for toString really?

**Comment by ShaneBeee** [comment]
> This seems okay to me. I think this is only used for toString really?

I believe so ya. The usage for the class info already accepts this, I believe when I did the PR years ago I just forgot to change the lang.
I keep seeing people show errors "cannot compare a potion to a potion" and its super confusing.

**Review by sovdeeth — APPROVED** [review]

**Comment by sovdeeth** [comment]
I think this could be a patch change

**Comment by ShaneBeee** [comment]
> I think this could be a patch change

I put it on the feature branch for a few reasons:
1) Its not a breaking change (next to no one will notice this change)
2) Helps understand errors a bit better
3) Since 2.9 (stable) isn't out yet, I figured now was a good time

But I understand if you guys don't want it in the next update.

**Comment by sovdeeth** [comment]
> > I think this could be a patch change
> 
> I put it on the feature branch for a few reasons:
> 
> 1. Its not a breaking change (next to no one will notice this change)
> 2. Helps understand errors a bit better
> 3. Since 2.9 (stable) isn't out yet, I figured now was a good time
> 
> But I understand if you guys don't want it in the next update.

to clarify i meant patch change as in it could go in 2.9
feature changes could not.

**Comment by ShaneBeee** [comment]
> > > I think this could be a patch change
> > 
> > 
> > I put it on the feature branch for a few reasons:
> > 
> > 1. Its not a breaking change (next to no one will notice this change)
> > 2. Helps understand errors a bit better
> > 3. Since 2.9 (stable) isn't out yet, I figured now was a good time
> > 
> > But I understand if you guys don't want it in the next update.
> 
> to clarify i meant patch change as in it could go in 2.9 feature changes could not.

ohhh gotcha, thanks for the clarification.

**Pull request merged**
