### PR TITLE
Fixes the warnings in the default variable test

### PR DESCRIPTION
**Pull request by TheLimeGlass**
### Description
Fixes the warnings in the default variable test.
Warnings that this pull request removes:
```
[21:52:11 INFO]: [Skript] Line 6: (..\..\..\..\..\..\src\test\skript\tests\misc\default variables.sk)
[21:52:11 INFO]:     It is suggested to use brackets around the name of a variable. Example: {example::%player%} = 5
[21:52:11 INFO]: Excluding brackets is deprecated, meaning this warning will become an error in the future.
[21:52:11 INFO]:     Line: testing::no brackets::%living entity%: "String"
[21:52:11 INFO]:
[21:52:11 INFO]: [Skript] Line 7: (..\..\..\..\..\..\src\test\skript\tests\misc\default variables.sk)
[21:52:11 INFO]:     It is suggested to use brackets around the name of a variable. Example: {example::%player%} = 5
[21:52:11 INFO]: Excluding brackets is deprecated, meaning this warning will become an error in the future.
[21:52:11 INFO]:     Line: testing::variables4: 1.6900000000001
[21:52:11 INFO]:
```

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

### CODE REVIEW

**Comment by AyhamAl-Ali** [comment]
Why tho? Isn't the goal of the code you changed is to test the warning feature? it even says `no brackets` as it's intentional

I would suggest keeping just line 6 and rename the variable to like `no brackets warning test` but keep the change of line 7

**Comment by TheLimeGlass** [comment]
> Why tho? Isn't the goal of the code you changed is to test the warning feature? it even says `no brackets` as it's intentional
> 
> I would suggest keeping just line 6 and rename the variable to like `no brackets warning test` but keep the change of line 7

I added it because when I developed the default variables I needed to make sure that no brackets worked. Then the warning came along where no brackets gets considered a StringMode.MESSAGE so it's encouraged to make sure it's a variable now. The warnings are annoying now when in development mode.

**Comment by sovdeeth** [comment]
> > Why tho? Isn't the goal of the code you changed is to test the warning feature? it even says `no brackets` as it's intentional
> > I would suggest keeping just line 6 and rename the variable to like `no brackets warning test` but keep the change of line 7
> 
> I added it because when I developed the default variables I needed to make sure that no brackets worked. Then the warning came along where no brackets gets considered a StringMode.MESSAGE so it's encouraged to make sure it's a variable now (StringMode.VARIABLE...). The warnings are annoying now when in development mode.

Surely it's still valuable to test that it works, though?

**Comment by TheLimeGlass** [comment]
> > > Why tho? Isn't the goal of the code you changed is to test the warning feature? it even says `no brackets` as it's intentional
> > > I would suggest keeping just line 6 and rename the variable to like `no brackets warning test` but keep the change of line 7
> > 
> > 
> > I added it because when I developed the default variables I needed to make sure that no brackets worked. Then the warning came along where no brackets gets considered a StringMode.MESSAGE so it's encouraged to make sure it's a variable now (StringMode.VARIABLE...). The warnings are annoying now when in development mode.
> 
> Surely it's still valuable to test that it works, though?

Well then we need Pikachu's pull request that adds a test runner feature that acts like a try and catch. It's still pending.

**Comment by sovdeeth** [comment]
I think this change should be done when we do deprecate the brackets. Until then it's still valuable to test.

**Comment by TheLimeGlass** [comment]
> I think this change should be done when we do deprecate the brackets. Until then it's still valuable to test.

They are deprecated. Do you mean remove? Why shouldn't this be merged now? It's just for testing sake?

**Comment by sovdeeth** [comment]
> > I think this change should be done when we do deprecate the brackets. Until then it's still valuable to test.
> 
> They are deprecated. Do you mean remove? Why shouldn't this be merged now? It's just for testing sake? Tired of seeing this error like it's a new error that a branch I made did, when it's not.

yeah, I meant remove. I suppose since it's targeting feature it's fine to merge. I just wanted to make sure we're still testing things that are intended to work in 2.8.

**Comment by TheLimeGlass** [comment]
> > > I think this change should be done when we do deprecate the brackets. Until then it's still valuable to test.
> > 
> > 
> > They are deprecated. Do you mean remove? Why shouldn't this be merged now? It's just for testing sake? Tired of seeing this error like it's a new error that a branch I made did, when it's not.
> 
> yeah, I meant remove. I suppose since it's targeting feature it's fine to merge. I just wanted to make sure we're still testing things that are intended to work in 2.8.

I fixed default variables in 2.7. It is unrelated to 2.8 and can be included in 2.8.

**Review by sovdeeth — APPROVED** [review]

**Review by Moderocky — APPROVED** [review]

**Pull request merged**
