### PR TITLE
added Hopper/Dropper/Dispenser to open inventory effect

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
Added the hopper, dropper and dispenser to the open inventory effect

---
**Target Minecraft Versions:**     any (1.9+_
**Requirements:**     none
**Related Issues:**    none

### Note:
I changed the numbers of the parsing from the 20's down to 2,3,4,5,6
I never really understood why its that way.
I tested it, works fine, has no affect on it.

If anyone feels more inventory types should be added, let me know, and I'll quickly throw them in.

### CODE REVIEW

**Comment by TheBentoBox** [comment]
Just want to note you can already do this with hoppers because the `open inventory` syntax supports providing a custom inventory (the `%-inventory%` in the syntax) which you can pass a `hopper inventory` [inventory type](http://skriptlang.github.io/Skript/classes.html#inventorytype). 

That being said, this change makes sense for consistency and for some reason I can't seem to open dropper or dispenser inventories with vanilla Skript even though the inventory type is registered so this would address that.

**Comment by JRoy** [comment]
@ShaneBeee yes but for completion's sake, you should add them

**Comment by ShaneBeee** [comment]
> @ShaneBeee yes but for completion's sake, you should add them

Will do 👍

**Comment by TheBentoBox** [comment]
Yeah, I think having both seems unnecessary but it would make sense to at least include dispenser as an alias for dropper, but even then the text up top will show the correct inventory name so just doing both makes the most sense. I'd check the other available inventory types while you're at it and see what others make sense to add here (maybe brewing?)

**Comment by ShaneBeee** [comment]
CRAP.... and I just hit push. 
Okay I added dispenser and furnace, I'll do brewing right now.

**Comment by ShaneBeee** [comment]
Okay, I added brewing, and threw in beacon as well, you know, for sport!

**Comment by ShaneBeee** [comment]
Removed furnace, brewing, enchanting and beacon

After much testing, and discussion with Snow, came to realize, these 4 inventories will open to the player, but server no purpose.
On lower versions, for instance 1.9, if an item is put into the enchanting table it runs a ton of errors, in higher versions, you can put the item in the table, but it won't let you enchant it.

I am keeping hopper/dropper/dispenser as they can be used for unique GUI's but that is really it, obviously as they are not attached to a block

**Pull request merged**
