### PR TITLE
Add classless syntax registration

### PR DESCRIPTION
**Pull request by JRoy**
### Description
Add API methods to register effects, expressions, and conditions without specifying the class you're registering from assuming you're using static initialization. This pull request maintains backward compatibility with add-ons and shades a new dependency into Skript, [WhoCalled](https://github.com/nallar/WhoCalled). In addition to adding these API elements, I updated all of the syntaxes within Skript to use those new API methods (where possible).

I understand there are line ending issues but tbh is it that bad of a thing lmao? Skript has had mixed line ending for a while and should just be CRLF at this point so this is for the greater good. If it's that big of an issue, I can fix it ig. 

---
**Target Minecraft Versions:** N/A
**Requirements:** N/A
**Related Issues:** N/A

### CODE REVIEW

**Comment by JRoy** [comment]
To reviewers: you can safely ignore every syntax file as I'll I've changed is their registration lines (and I've properly verified every one of them).

To see a diff of the Skript class which is all that matters see: https://www.diffchecker.com/K1oPJU9p

**Comment by Pikachu920** [comment]
I don't really see this as an improvement, having to put the class isn't really a bad thing

**Comment by bensku** [comment]
Shading third-party code for a minor change like this is not acceptable. Besides that, I do not think this is really beneficial; caller-sensitive methods can be rather *fun* to debug.

@SkriptLang/developers your thoughts on this?

**Comment by Pikachu920** [comment]
I agree it's more trouble than it is useful

**Comment by JRoy** [comment]
TBH this was more something to keep me busy while I was bored if this gets rejected no biggie.

**Comment by bensku** [comment]
Based on personal preference and (lack of) team comments, I'm closing this. Sorry for trouble!

**Pull request closed without merging**
