### PR TITLE
Fix line endings

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
This PR aims to force all CRLF line endings -> LF

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

### CODE REVIEW

**Review by bensku — CHANGES_REQUESTED** [review]
Let's add any other big (automated) changes to this PR. No need to clutter Git history more than once.

**Comment by DeltaRays** [comment]
Then in my opinion we should remove all unused imports and format all files in this pull request, too

**Review by bensku — APPROVED** [review]
Nevermind, this is going to be squashed.

**Comment by bensku** [comment]
@DeltaRays Having changes other than whitespace in this PR would be bad for transparency.

**Pull request merged**
