### PR TITLE
Add Block Data support to ExprTypeOf

### PR DESCRIPTION
**Pull request by UnderscoreTud**
### Description
This PR adds support to blockdatas in the TypeOf expression

---
**Target Minecraft Versions:** 1.13+
**Requirements:** any
**Related Issues:** none

### CODE REVIEW

**Review by AyhamAl-Ali — APPROVED** [review]

**Comment by TheLimeGlass** [comment]
Can't you just add a BlockData to ItemType converter? This will help in other parts of Skript. You're using the ItemType constructor, so why not just register a converter in the DefaultConverters?

**Comment by APickledWalrus** [comment]
> Can't you just add a BlockData to ItemType converter? This will help in other parts of Skript. You're using the ItemType constructor, so why not just register a converter in the DefaultConverters?

+1 on this

Btw, was there a specific issue that led you to make this PR?

**Comment by DelayedGaming** [comment]
> +1 on this
> 
> 
> 
> Btw, was there a specific issue that led you to make this PR?
This was originally my suggestion given to tud. ExprTypeOf supports inventories, entities, blocks, items etc, but not BlockData.
We are able to get Material from a BlockData via `BlockData#getMaterial()`, hence I don't see why not to implement this into Skript. 🚀

**Review by Moderocky — APPROVED** [review]
LGTM

**Pull request merged**
