### PR TITLE
Add decrease to EffChange

### PR DESCRIPTION
**Pull request by Fusezion**
### Description
Adds `decrease` to `reduce` changer

*ignore that issue's close pull request, I did it for wrong branch*

---
**Target Minecraft Versions:** 'any'
**Requirements:** 'none'
**Related Issues:** #5595

### CODE REVIEW

**Review by sovdeeth — APPROVED** [review]
revolutionary

**Review by AyhamAl-Ali — APPROVED** [review]
Took long time to finish reviewing such a complicated PR. Well done Fuse!

**Comment by ahmadMsaleem** [comment]
This is a **game-changing pull**, I think we should reread it before we do anything, We need to make sure we understand the implications of what we're doing.

**Comment by AyhamAl-Ali** [comment]
I would say it must be followed by at least 5 JUnit tests and goes under our Skript test discord server.

**Review by Moderocky — APPROVED** [review]

**Review by TheLimeGlass — APPROVED** [review]

**Pull request merged**
