### PR TITLE
PlayerArmorChangeEvent

### PR DESCRIPTION
**Pull request by Wealthyturtle**
### Description
Adds a Paper-only event that allows players to listen onto the PlayerArmorChangeEvent, and also get the event-item (new item that replaces the slot)

---
**Target Minecraft Versions:**     Idk which version this event was added, so I just used the class check function
**Requirements:**     Paper
**Related Issues:**     #2595

### CODE REVIEW

**Comment by Blueyescat** [comment]
"change" is not equal to "equip".

Also according to the javadoc of the event, the Skript event descriptiption actually lies. Already i'm totally against adding that event to Skript until it gets actually useful.

https://papermc.io/javadocs/paper/1.14/com/destroystokyo/paper/event/player/PlayerArmorChangeEvent.html

**Comment by bensku** [comment]
@Wealthyturtle Are there some cases where one inventory click event doesn't do this?

**Comment by Wealthyturtle** [comment]
I did a quick test, with the following scripts:
```
on inventory click:
	broadcast "%event-item%"
```

```
on armor equip:
	broadcast "%event-item%"
```

And right clicked a helmet in survival mode (to equip it), the ``inventory click`` event didn't fire, but the ``armor equip`` event fired. @bensku

**Comment by bensku** [comment]
Manually merged with minor syntax changes.

**Pull request closed without merging**
