### PR TITLE
Add cow aliases to mooshrooms

### PR DESCRIPTION
**Pull request by TheLimeGlass**
### Description
Add aliases for the word `cow` on mooshrooms

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

### CODE REVIEW

**Comment by ShaneBeee** [comment]
No where in Minecraft are these guys referred to as "Moohsroom Cows".... so other than fixing an issue in an example in your other PR where I spotted this.... what is the point of making stuff up in Skript?
In my opinion, Skript should try its best to match Minecraft when it can, I do not think its in Skript's best interest to make up aliases for things that just really don't fit.

**Comment by TheLimeGlass** [comment]
> No where in Minecraft are these guys referred to as "Moohsroom Cows".... so other than fixing an issue in an example in your other PR where I spotted this.... what is the point of making stuff up in Skript? In my opinion, Skript should try its best to match Minecraft when it can, I do not think its in Skript's best interest to make up aliases for things that just really don't fit.

Please keep the conversation professional.

It's an aliases which is an optional addition, so I find it to make sense. It is a cow and people refer to them when talking a mooshroom cow, I can remember my friends refering it like that and Captain Sparklez.

**Comment by ShaneBeee** [comment]
> Please keep the conversation professional.

Please indicate where I'm not?
While I understand you dislike me, and you enjoy personally attacking people... If you have personal issues with someone reviewing your code, I suggest keeping it off GitHub. This isn't the place for your attitude LimeGlass.

I was simply pointing out that this change does not have anything to do with Minecraft, and Skript should try to keep in line with Minecraft, rather than making up random syntaxes.

**Comment by APickledWalrus** [comment]
The debate here is whether Skript should stick strictly to the mob names used by Minecraft, or take some additional liberty in supporting other names used within the community.

I would say that if we are to add "aliases" like this, something like `mushroom cow` would be better (IIRC Minecraft itself used to refer to them as this internally). Definitely up for debate :)

**Review by sovdeeth — CHANGES_REQUESTED** [review]
I'm fine with this change. I think mushroom cow is a perfectly fine name to use and I've been tripped up by this before.

However, this change makes `mushroom` a valid alias for mooshrooms which is not acceptable.

**Review by sovdeeth — APPROVED** [review]

**Review by Moderocky — APPROVED** [review]

**Pull request merged**
