### PR TITLE
EffDrop - Fixes

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
- Fix issue with not being able to drop from a list variable
- Based on what I could see and my testing, the issue came from `"%itemtypes/experience%"`, it looks like the issue was the fact we have 2 types, one which is plural (item types) and one which is singular (experience). My guess the reason its denying the list variable, is because the variable could be either a list of items or a single experience, and at the time of init, the variable's contents are unknown. By allowing multiple experiences this issue is fixed.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #1917

### CODE REVIEW

**Comment by Blueyescat** [comment]
Add support for multiple experiences instead of that

**Comment by ShaneBeee** [comment]
> You can add support for multiple experiences instead of that

I don't understand a point when a person would use multiple experiences, but if you truly feel that's better than this I can change it.

**Comment by FranKusmiruk** [comment]
@Blueyescat the experience type allows you to spawn more than a single experience at time (i.e.: `drop 15 exp`), so, I don't really see an use for that.

**Comment by Blueyescat** [comment]
You can disable merge of exp orbs and spawn multiple at the same location, so would be useful

**Pull request merged**
