### PR TITLE
Ignore folders that begins with a dot

### PR DESCRIPTION
**Pull request by AyhamAl-Ali**
### Description

This only makes Skript ignore folders that begins with a dot when:
- Loading scripts folder at startup.
- Reloading a parent folder that doesn't begin with a dot but has a child folder that begins with a dot.
- Reloading all scripts.

But doesn't work when:
- Reloading specific file inside a folder that begins with a dot (that means the script file will load)
- Reloading specific folder that begins with a dot (that means all the scripts inside that folder will load except folders inside it that begins with a dot)

Therefor, SkriptCommand.class needs a rework to prevent reloading folders that begins with a dot or files that any of their parents begin with a dot and support them with enable and disable args.

**So far I have reworked on reload arg to not allow cases stated above, I will try to finish enable and disable args and make another PR probably.**

**Also**, file/folder permissions should also be worked on but since it is not a high priority due to the low chances of it happening (and probably caused by the user side) but I have found that `Files#walk` causes this issue due to it reading attributes of the files regardless of their permissions, I have tried to fix it but seems that it isn't as easy as I thought due to `walk` method not having an easy way to check for perms before reading it.

---
**Target Minecraft Versions:** 
**Requirements:** 
**Related Issues:** #3910 #3866

### CODE REVIEW

**Review by ShaneBeee — APPROVED** [review]
I fully support this idea... since on Mac, folders that start with a dot aren't even shown (hidden by default, can't be shown with a combo of key presses)
Looks good to me

**Comment by FranKusmiruk** [comment]
> I fully support this idea... since on Mac, folders that start with a dot aren't even shown (hidden by default, can be shown with a combo of key presses)
> Looks good to me

On windows they

**Comment by Pikachu920** [comment]
maybe it's also worth checking if `!f.isHidden()`

**Comment by AyhamAl-Ali** [comment]
This will actually prevent loading **files** and **folders** that are marked hidden (in Windows) and/or begins with a dot in (UNIX systems).
Not sure if `f.getName().beginsWith(".")` is still usable in some cases but I left it as an extra protection layer.

**Comment by AyhamAl-Ali** [comment]
Closing due to #4135

**Pull request closed without merging**
