### PR TITLE
ExprAttribute

### PR DESCRIPTION
**Pull request by Wealthyturtle**
### Description
This PR adds in a new Attribute expression that will allow users to directly modify entities' attributes, such as attack speed, max health, etc.

~~Note: At the moment, this expression only supports modifying a single attribute of a single entity.~~

---
**Target Minecraft Versions:**     Any
**Requirements:**     None
**Related Issues:**     None

### CODE REVIEW

**Comment by ShaneBeee** [comment]
I’ll be honest I’m not a fan of using strings for attributes.

**Comment by Wealthyturtle** [comment]
I could use it's own type but then there would be the issue of type comparison, serialization, etc. Plus, some other effects like EffPlaySound also use strings instead of the actual sound object. :/

**Comment by ShaneBeee** [comment]
> I could use it's own type but then there would be the issue of type comparison, serialization, etc. Plus, some other effects like EffPlaySound also use strings instead of the actual sound object. :/

I think sounds uses strings more so because it also supports custom sounds from resource packs. (not to mention sound enums change dramatically all the time, especially the fact that a handful of new sounds are added each MC update)
I mean, the strings will work obviously, I just think it seems a little odd to be done this way.

**Comment by bensku** [comment]
It would be ideal to register the type properly. If serious problems arise from that, we might have to go back to using strings.

**Comment by Blueyescat** [comment]
Please follow syntax standards.

**Comment by Wealthyturtle** [comment]
Sorry for the delay, I have addressed the concerns here on my side - I will re-open a separate PR once I'm done with the changes. Will close this PR for now.

**Pull request closed without merging**
