### PR TITLE
Removed some redundant exists checks and formatting stuff

### PR DESCRIPTION
**Pull request by cheeezburga**
### Description
This PR removes some redundant exists checks for BukkitClasses, SimpleEvents and BukkitEventValues.

- BukkitEventValues: just the AoE cloud handles were removed. The behaviour should (I think) be the same, but reflection is no longer needed.
- BukkitClasses: removes the getEntity exists check, as it should always exist in 1.13+
- SimpleEvents: initially didn't plan on including this in this PR, but saw some exists checks that could be removed. Then I saw that the formatting was a bit random at times, so I made it a bit more consistent. Happy to revert this file to what it was before if the formatting stuff is out of the scope of this housekeeping stuff.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #6676 #6641

### CODE REVIEW

**Comment by APickledWalrus** [comment]
I don't think it's safe to remove the AoE cloud handles. They were just added for 1.20.5.

**Comment by APickledWalrus** [comment]
It may be a mistake, I'll check with Sovde

**Comment by cheeezburga** [comment]
> It may be a mistake, I'll check with Sovde

Too easy, appreciate it. If I just put the stuff I removed back in and then push it here, will it like, cancel out and remove the file from this PR?

**Comment by sovdeeth** [comment]
> It may be a mistake, I'll check with Sovde

yes this was a mistake, I read it backwards, thinking the method was for newer versions rather than older versions, I'll remove it from the issue checklist

**Comment by Moderocky** [comment]
> Oh true. Sorry, I didn't give it much thought honestly coz it was listed in #6641 under the 1.13 bit. 

Yes don't worry Sovde put some things in the list that shouldn't have been 😔 he got me too

We can go through it all again at the end anyway in case something was missed

**Review by Moderocky — APPROVED** [review]

**Comment by sovdeeth** [comment]
> > Oh true. Sorry, I didn't give it much thought honestly coz it was listed in #6641 under the 1.13 bit.
> 
> Yes don't worry Sovde put some things in the list that shouldn't have been 😔 he got me too
> 
> We can go through it all again at the end anyway in case something was missed

the ones you crossed off were just for docs updates, not removing checks

**Review by sovdeeth — APPROVED** [review]

**Review by Moderocky — APPROVED** [review]

**Pull request merged**
