### PR TITLE
Add delete changer to ExprMessage

### PR DESCRIPTION
**Pull request by Phill310**
### Description

Adds the delete changer to message expression (so you can do stuff like `clear death message`)

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #5919

### CODE REVIEW

**Comment by Phill310** [comment]
Are there already tests for this because I can't seem to find them? Also I am not fully sure how I would trigger an event like join to test this

**Comment by sovdeeth** [comment]
> Are there already tests for this because I can't seem to find them? Also I am not fully sure how I would trigger an event like join to test this

It'd need something like a JUnit where you manually call a message event

**Comment by Phill310** [comment]
Is 1 test for set and clear good enough or should I try to make a test for each event

**Comment by sovdeeth** [comment]
> Is 1 test for set and clear good enough or should I try to make a test for each event

I think this is fine, but if you're willing, it can't hurt.

**Review by sovdeeth — APPROVED** [review]

**Review by UnderscoreTud — APPROVED** [review]

**Review by Pikachu920 — APPROVED** [review]

**Pull request merged**
