### PR TITLE
Remove travis.yml

### PR DESCRIPTION
**Pull request by TheLimeGlass**
### Description
Remove travis.yml

We don't use travis ci anymore, and with the recent token database leak they had, it's best to remove all ties to travis ci.

Also if an Admin can confirm that it's not linked with the organization and each repository.

### CODE REVIEW

**Review by TPGamesNL — APPROVED** [review]
Seems to have previously been used by bensku (probs private) to check PRs, but we have GH Actions now

https://github.com/SkriptLang/Skript/commit/72e94d558c9068485c7d776c9d57c1d644bd61b9
https://github.com/SkriptLang/Skript/pull/1119

**Review by AyhamAl-Ali — APPROVED** [review]

**Comment by TheLimeGlass** [comment]
> Seems to have previously been used by bensku (probs private) to check PRs, but we have GH Actions now
> 
> [72e94d5](https://github.com/SkriptLang/Skript/commit/72e94d558c9068485c7d776c9d57c1d644bd61b9) #1119

It used to be our CI

Did you also check that Travis CI is not in the integrations of the repository and organization, because again it did have a database leak and we don't want any potential hackers (not really hackers) using any exposed tokens we may have given Travis CI

**Comment by TPGamesNL** [comment]
> Did you also check that Travis CI is not in the integrations of the repository and organization, because again it did have a database leak and we don't want any potential hackers (not really hackers) using any exposed tokens we may have given Travis CI

I can't check for the SkriptLang org, ask Kenzie or pickle for that. 

The Skript repo has a webhook (delivering to `https://notify.travis-ci.org`, no tokens or sth as far as I can see). I don't have access to the Travis CI stuff either, you should ask bensku if you want to be sure we can remove it.

**Comment by APickledWalrus** [comment]
I'll try to take a look at this soon when I am able to take a good luck at the org settings

**Review by APickledWalrus — APPROVED** [review]
Okay, I've removed all ties to travis ci and made sure their third-party to the organization is disabled.

**Pull request merged**
