### PR TITLE
Fix rounding accuracy

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
- Removed unused methods
- Cleaned up file
- Adjust rounding methods with `Skript.EPSILON` before handling (lines 169, 184, 199, 206, 216, 226)

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #4235

### CODE REVIEW

**Comment by Matocolotoe** [comment]
```
function floor_test():
	set {_a} to 3.9999999999
	set {_b} to floor({_a})
	broadcast {_a}.toString()
	broadcast {_b}.toString()
```

image

**Comment by TPGamesNL** [comment]
While you could call that behaviour a bug, `3.9999999999 = 4` according to Skript (as seen in Javadoc of Skript.EPSILON), so this is to be expected. We have to draw the line somewhere, and Njol (probs) decided `10^-10` was the width of that line

**Comment by Matocolotoe** [comment]
Right, I guess it's still better than having inconsistencies occurring at 2 decimal places.

**Review by APickledWalrus — CHANGES_REQUESTED** [review]
Could you add a test for this?

**Review by APickledWalrus — APPROVED** [review]

**Review by TheLimeGlass — CHANGES_REQUESTED** [review]
I suggest adding some floor function tests

**Review by TheLimeGlass — APPROVED** [review]

**Pull request merged**
