### PR TITLE
Define import sorting rule

### PR DESCRIPTION
**Pull request by TheLimeGlass**
### Description
Define import sorting rule. This is to avoid having different people update the import list every pull request ultimately making rebasing of pull requests that much harder. This is due to different IDE's having different rules. Most popular IDE's have a configuration option to allow for these rules.

### Preview

Untitled

### CODE REVIEW

**Comment by Fusezion** [comment]
> (Intellij is currently not capable of automatic line breaks)

Technically it does but what does `ch.njol.skript.another` entail?

**Comment by TheLimeGlass** [comment]
> > (Intellij is currently not capable of automatic line breaks)
> 
> Technically it does but what does `ch.njol.skript.another` entail? image

Ya but that's not automatic, it depends on the package. The another.package example is to explain the grouping of the imports. It only has the line break after a new grouping.

**Review by AyhamAl-Ali — COMMENTED** [review]
I don't think the 2 line breaks should be a rule, no one manually sort/import imports, it's all automatic and I don't prefer to be forced to use specific line breaks for that.

As for the rest as long as it's configurable it's fine.

**Comment by TheLimeGlass** [comment]
> I don't think the 2 line breaks should be a rule, no one manually sort/import imports, it's all automatic and I don't prefer to be forced to use specific line breaks for that.
> 
> As for the rest as long as it's configurable it's fine.

It says optional

**Review by Moderocky — CHANGES_REQUESTED** [review]
I like this as a guideline but I don't know if this should be a requirement, it seems like a major brake on a lot of PRs from external contributors if we have to back-and-forth for a week while they change their IDE settings to match whatever we want.

I'm not sure about the line breaks, but I like having some kind of order.

**Comment by TheLimeGlass** [comment]
> I like this as a guideline but I don't know if this should be a requirement, it seems like a major brake on a lot of PRs from external contributors if we have to back-and-forth for a week while they change their IDE settings to match whatever we want.
> 
> I'm not sure about the line breaks, but I like having some kind of order.

So aside from the line break, the sorting rule is valid? I don't mind no line break rule.

**Comment by Fusezion** [comment]
Since lime brought it up I never actually noticed until now, but could someone mention the placement of java imports or are we in agreement that it should be placed first? 

Nearly all of the newer classes in skript *excluding ones by lime* for the most part follow 

- imports
- blank
- java imports

This includes all newer and current contributors with the only classes with them placed first are those made years and years ago. I personally am against java imports being first, as it just seems weird to me.

**Comment by TheLimeGlass** [comment]
> Since lime brought it up I never actually noticed until now, but could someone mention the placement of java imports or are we in agreement that it should be placed first?
> 
> Nearly all of the newer classes in skript _excluding ones by lime_ for the most part follow
> 
>     * imports
> 
>     * blank
> 
>     * java imports
> 
> 
> This includes all newer and current contributors with the only classes with them placed first are those made years and years ago. I personally am against java imports being first, as it just seems weird to me.

Java comes first by standards https://stackoverflow.com/questions/7735671/order-of-import-statements-in-java

**Comment by Moderocky** [comment]
> https://stackoverflow.com/questions/7735671/order-of-import-statements-in-java

What's actually quoted in that stackoverflow answer is a company style guide from a company called 'Geotechnical Software Services'

Oracle's style guide does not mention any specific ordering of imports. Google's style guide recommends line breaks between groups but does not mention any specific ordering of imports.

It seems to be an eclipse standard to sort with Java and star packages last, but other IDEs don't seem to copy this.

**Comment by Fusezion** [comment]
> It seems to be an eclipse standard to sort with Java and star packages ~~last~~ first, but other IDEs don't seem to copy this.

With Kenzie's response pointing out what I could find and saw, with the highest majority if team members using IntelliJ/Jetbrains I do not believe it's appropriate to follow Eclipse's import guidelines let alone coding guidelines, this just shows that SkriptLang as a whole needs to decide what IDE and guidelines should be picked and what shouldn't be. It's not helping to say any annotation or must use this import style that majority of people don't use.

**Comment by Moderocky** [comment]
We've decided to relax the import and other sorting rules going forward, so this is no longer needed.

**Pull request closed without merging**
