### PR TITLE
Fix EffReplace

### PR DESCRIPTION
**Pull request by Wealthyturtle**
### Description
This PR should fix the CCE caused by the updated EffReplace class. I think I should be able to call setItem() with a null ItemStack? Correct me if I'm wrong here.

---
**Target Minecraft Versions:**     Any
**Requirements:**     None
**Related Issues:**     #2763

### CODE REVIEW

**Comment by bensku** [comment]
Regression test would be nice.

**Comment by Wealthyturtle** [comment]
Technically this is already covered in https://github.com/SkriptLang/Skript/blob/45eaaae5c7049575cef72069b6cbf5d0d210f126/src/test/skript/tests/syntaxes/effects/EffReplace.sk#L7, not sure why it didn't fail... Perhaps because OP was replacing 2 items? Or because it was a player inventory? Need to check.

**Comment by bensku** [comment]
We need a test that fails without this fix.

**Comment by Wealthyturtle** [comment]
I am unable to get a test that fails without this fix for some reason...

```
command /t:
	trigger:
		send "f"
		replace all stone and dirt in player's inventory and player's top inventory with diamond
		send "f2"

```
Test code ^

I can confirm that the above code does not replace any stone/dirt with diamonds without my code fix, but I cannot get the exception to be thrown for some reason? Using Skript 2.5-alpha1 on Spigot 1.14.4

**Comment by bensku** [comment]
Alright, I'll just merge this since it fixes the issue.

**Pull request merged**
