### PR TITLE
Arithmetic Private Methods Changed to Public

### PR DESCRIPTION
**Pull request by TheAbsolutionism**
### Description
This PR aims to change the `exactOperationExists` method within the `Arithmetic` class allowing skript-addons to ensure an operation does or does not already exist if registered by another addon.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #7206

### CODE REVIEW

**Review by Fusezion — APPROVED** [review]

**Comment by Moderocky** [comment]
Please put a little more effort into writing your PR name/description: these are auto-exported in change history & difference logs and it won't be very clear when searching through the contribution history what "thingy" is or what this is "fixing"

**Comment by UnderscoreTud** [comment]
Make `exactDifferenceExists` public as well

**Review by UnderscoreTud — APPROVED** [review]

**Review by Pikachu920 — DISMISSED** [review]
I think making these public is not the right way for addon devs to accomplish this. if registration fails, a skriptapiexception is thrown and can be caught by the caller

**Review by sovdeeth — APPROVED** [review]

**Review by Asleeepp — APPROVED** [review]

**Review by Romitou — APPROVED** [review]

**Comment by sovdeeth** [comment]
> I think making these public is not the right way for addon devs to accomplish this. if registration fails, a skriptapiexception is thrown and can be caught by the caller

I think it'd be nicer to know whether it will works or not prior to doing all the work to make the arithmetic. Do you foresee a reason that exposing these methods would be negative?

**Review by APickledWalrus — APPROVED** [review]

**Comment by APickledWalrus** [comment]
> I think making these public is not the right way for addon devs to accomplish this. if registration fails, a skriptapiexception is thrown and can be caught by the caller

The same (similar in practice) methods are public for developers. Exception handling is unnecessarily heavy when this exists as a safe option we can provide. I will merge this in for now, but we can revisit this practice across all registries where it exists.

**Comment by Pikachu920** [comment]
> > I think making these public is not the right way for addon devs to accomplish this. if registration fails, a skriptapiexception is thrown and can be caught by the caller
> 
> The same (similar in practice) methods are public for developers. Exception handling is unnecessarily heavy when this exists as a safe option we can provide. I will merge this in for now, but we can revisit this practice across all registries where it exists.

Yeah, but the problem is that this is exposing implementation details. The caller doesn't want to know whether an exact operation already exists, they want to know whether it is acceptable to register the operation. Calling `exactOperationExists` isn't sufficient for that goal, because there may be other exceptional conditions (i.e. calling register after registration closes, or some change in the future).

If the intent is to allow addon devs to check if a registration is acceptable, I think we should add a method specifically intended for that instead of exposing the utility methods that power the existing check.

**Pull request merged**
