### PR TITLE
Fix NPE when loadStructure fails

### PR DESCRIPTION
**Pull request by TheDGOfficial**
### Description
Fixes NPE when loadStructure fails.

The NPE is not from loadScript returning null or not from info.commandNames actually, it is from cfg.getFileName. So this PR makes fileName default to "" (does not matter anyway since loadStructure failed, we do not want to sync commands or such)

Maybe just continue on empty script info or null cfg but that may change behaviour. I've tested this and it correctly sends permission denied errors.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #3804

### CODE REVIEW

**Comment by TPGamesNL** [comment]
IMO it would be better to make sure every method that returns one or more `Config`s can't return `null` values (as value or list element). Some methods already do this:
https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/ScriptLoader.java#L823-L825
but not all:
https://github.com/SkriptLang/Skript/blob/885a4b65cd41253e076a8230c007480362586e79/src/main/java/ch/njol/skript/ScriptLoader.java#L797-L803

**Comment by TheDGOfficial** [comment]
Yes, that would be better. Looking now.

**Comment by TheDGOfficial** [comment]
I just added the null check to the method you've mentioned and the one that causes this error. Don't have time to look into all methods to find all ones that can return arrays/lists with null values though, so let me know if I've missed any.

**Comment by TPGamesNL** [comment]
You should look at the usages of `ScriptLoader.loadStructure(File)`, since that's the method that's used everywhere (`ScriptLoader`, `EffScriptFile` and `SkriptCommand`). 
PS I said it wrong in my last message, since a method returning a single `Config` should return null sometimes. I meant to say that all other methods using this should account for that, which they don't.

**Comment by TPGamesNL** [comment]
Closing as https://github.com/SkriptLang/Skript/pull/3924 has been merged, fixing the same issues

**Pull request closed without merging**
