### PR TITLE
Color changes to the docs (fixed)

### PR DESCRIPTION
**Pull request by MrScopes**
### Description
Colors changed on the docs to be less depressing, you can view it: https://mrscopes.github.io/Skript/

### CODE REVIEW

**Comment by ShaneBeee** [comment]
I like the blue over the tan for sure, but one note to make is that you should be using a few shades of blue.

As you can see in yours, the top bar, side bar and each section is all the same blue:
Screen Shot 2019-10-14 at 12 03 55 PM

But in the original its 3 different shades of tan:
Screen Shot 2019-10-14 at 12 03 57 PM

**Comment by MrScopes** [comment]
> I like the blue over the tan for sure, but one note to make is that you should be using a few shades of blue.

I was thinking about something like this, but the page looked pretty fine to me. Got any suggestions for what shade of blue I should use? I tried a lot of different shades but couldn't find any that flowed well.

**Comment by ShaneBeee** [comment]
> I was thinking about something like this, but the page looked pretty fine to me. Got any suggestions for what shade of blue I should use? I tried a lot of different shades but couldn't find any that flowed well.

I just realized the top bar, and the elements area are the same tan so ignore my "3 shades of tan", I think its just 2.
That said, maybe for the top bar / elements, a slightly darker shade, and for the side bar, maybe a tiny bit lighter?!?

**Comment by MrScopes** [comment]
> That said, maybe for the top bar / elements, a slightly darker shade, and for the side bar, maybe a tiny bit lighter?!?

what about now?

**Comment by ShaneBeee** [comment]
> what about now?

I like it 👍

**Comment by Olyno** [comment]
Colors changed, it's a good news, but the responsive issue (that's the main issue of the website) is not solved, without forget a lot of stuff. That's the reason why I currently work on the doc to make it more usefull (#2561)

**Comment by MrScopes** [comment]
> Colors changed, it's a good news, but the responsive issue (that's the main issue of the website) is not solved, without forget a lot of stuff. That's the reason why I currently work on the doc to make it more usefull (#2561)

definitely, I was thinking about this but when I started working on improvements it was just a huge mess

**Comment by MrScopes** [comment]
guess this wont be merged

**Pull request closed without merging**
