### PR TITLE
SimpleEntityData - Display should be super entity

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
This PR aims to fix an issue with display entities.
Spawning 1 of each display entity type, then doing 
`send size of all displays` returns 0.
This is due to Display.class incorrectly being registered as a simple entity, which it should have been a super type.

---
**Target Minecraft Versions:** 1.19.4+
**Requirements:** none
**Related Issues:** none

### CODE REVIEW

**Review by AyhamAl-Ali — APPROVED** [review]

**Review by APickledWalrus — APPROVED** [review]

**Review by TheLimeGlass — CHANGES_REQUESTED** [review]
This is done so in https://github.com/SkriptLang/Skript/pull/5601

Duplicate closing soon after team review

**Comment by AyhamAl-Ali** [comment]
> This is done so in #5601
> 
> Duplicate closing soon after team review

Since that is in draft and this is a simple fix maybe we can merge this for time sake, what do you think?

**Comment by ShaneBeee** [comment]
> > This is done so in #5601
> > Duplicate closing soon after team review
> 
> Since that is in draft and this is a simple fix maybe we can merge this for time sake, what do you think?

^
I agree with this, also on the level of THIS pr is aimed towards fixing a bug in 2.7, Limes PR is geared towards adding new features in 2.8.
Considering 2.7 isn't even out yet, this should clearly be merged.

**Review by Moderocky — APPROVED** [review]

**Review by TheLimeGlass — CHANGES_REQUESTED** [review]
If it's to be a superclass entity data, you have to register a ClassInfo with it. See my pull request at https://github.com/SkriptLang/Skript/pull/5601 for how it's done. Aswell as see Projectile from Skript.

**Comment by ShaneBeee** [comment]
> If it's to be a superclass entity data, you have to register a ClassInfo with it. See my pull request at #5601 for how it's done. Aswell as see Projectile from Skript.

no you don't, see SimpleEntity for how its already been done... for years!
Screenshot 2023-08-09 at 4 03 13 PM

**Comment by TheLimeGlass** [comment]
> > If it's to be a superclass entity data, you have to register a ClassInfo with it. See my pull request at #5601 for how it's done. Aswell as see Projectile from Skript.
> 
> no you don't, see SimpleEntity for how its already been done... for years! Screenshot 2023-08-09 at 4 03 13 PM

It makes sense for Displays, does it not? We're going to be doing multiple expressions supporting Displays. If anything Skbee would benefit the most from a mandatory classinfo for this.

**Comment by ShaneBeee** [comment]
> > > If it's to be a superclass entity data, you have to register a ClassInfo with it. See my pull request at #5601 for how it's done. Aswell as see Projectile from Skript.
> > 
> > 
> > no you don't, see SimpleEntity for how its already been done... for years!
> 
> It makes sense for Displays, does it not? We're going to be doing multiple expressions supporting Displays. If anything Skbee would benefit the most from a mandatory classinfo for this. Other super entities don't provide nearly as much as Projectile, Player, Entity and Displays would being as their own ClassInfo.

SkBee wouldn't benefit at all from a ClassInfo, and Im not worried about that.
The goal of this PR was to fix a bug/oversight.

That said, while I understand you have a big PR for this aimed at 2.8, my hope here was just to fix the bug.

I do hope that you merge this PR as is, so hopefully the team can get 2.7 out soon with minimal bugs, and focus on a ClassInfo or the such in the future (as your PR already does). 
No need to do major changes now, just focus on fixing the bug.

**Review by TheLimeGlass — APPROVED** [review]

**Pull request merged**
