### PR TITLE
InventoryClickEvent Hotbar Button

### PR DESCRIPTION
**Pull request by Wealthyturtle**
### Description
Adds an ``event-integer`` to the InventoryClickEvent that returns the clicked hotbar button.

---
**Target Minecraft Versions:**     Any
**Requirements:**     None
**Related Issues:**     #2643

### CODE REVIEW

**Comment by FranKusmiruk** [comment]
This would be confusing, people would expect the event-integer or event-number to be the clicked slot. I'd rather see an EventExpression like `[the] hotbar button` instead of this.

Also, since when does this method exist? I do not remember seeing it before but I may have overlooked it.

**Comment by ShaneBeee** [comment]
> This would be confusing, people would expect the event-integer or event-number to be the clicked slot. I'd rather see an EventExpression like `[the] hotbar button` instead of this.
> 
> Also, since when does this method exist? I do not remember seeing it before but I may have overlooked it.

I agree with you, event-integer doesnt really state what the integer is for, so I agree that expression would be best.

I did a double check, and it appears that method is in 1.9.x.

**Comment by Wealthyturtle** [comment]
Ok, will replace it with an expression instead.

**Comment by Blueyescat** [comment]
return Number

**Comment by Wealthyturtle** [comment]
Alright, I've moved this over to a new expression, and made it return a Number now!

**Pull request merged**
