### PR TITLE
Add setTime to the code-conventions

### PR DESCRIPTION
**Pull request by TheLimeGlass**
### Description
Add setTime to the code-conventions as it's missing.

Also removed the braces as some methods had them and some didn't. They looked weird so I formalized those.

### CODE REVIEW

**Comment by Fusezion** [comment]
were the braces not used as a means to showcase what's optional in said usage?

**Comment by TheLimeGlass** [comment]
> were the braces not used as a means to showcase what's optional in said usage?

I don't know, get method is mandatory so I don't think so.

@Moderocky will know

**Comment by Pikachu920** [comment]
> > were the braces not used as a means to showcase what's optional in said usage?
> 
> I don't know, get method is mandatory so I don't think so.
> 
> @Moderocky will know

if so, maybe we can use [] like patterns

**Comment by Moderocky** [comment]
I don't know why the brackets were there - feel free to style this as you like as long as you do it consistently.

**Review by Moderocky — APPROVED** [review]

**Review by AyhamAl-Ali — APPROVED** [review]

**Pull request merged**
