### PR TITLE
Add world null check

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
Fixes EffTeleport throwing NPE when a world's location is null:
image

NPEs: https://pastebin.com/u48v5Fjt (Paper async), https://pastebin.com/gj8rqxsW (sync)

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** none

### CODE REVIEW

**Comment by APickledWalrus** [comment]
Do you think we should instead fallback to the entity's world if the location's world is null?

**Comment by APickledWalrus** [comment]
@TPGamesNL I can handle this change if you would like 🙂

**Review by APickledWalrus — APPROVED** [review]

**Comment by TheLimeGlass** [comment]
@TPGamesNL did this have a related issue or did you or someone on Discord find the NPE?

**Comment by TPGamesNL** [comment]
I don't remember, but probably no related issues otherwise I would've referred them

**Pull request merged**
