### PR TITLE
Update License Header

### PR DESCRIPTION
**Pull request by APickledWalrus**
### Description
This PR updates the license headers. There may be some mistakes, so please let me know if you find any, although I don't expect you to look through all 800 files haha. I am aware that a change to the classpath file was accidentally added, I forgot to ignore it before committing, but will commit soon with to fix it along with any other additional errors. 

~~EDIT: Will fix the license violations. Forgot to change it some parts... woops.~~

---
**Target Minecraft Versions:**     Any
**Requirements:**     No
**Related Issues:**     No

### CODE REVIEW

**Comment by JRoy** [comment]
Rip commit history part 2

**Comment by APickledWalrus** [comment]
> 
> 
> Rip commit history part 2

:(

**Comment by Pikachu920** [comment]
this was done last year and I believe it had been decided it wasn't worth the hassle of killing commit history, but we need @bensku's opinion to be sure

**Comment by APickledWalrus** [comment]
Of course. This did not take me super long to do so no worries about anything.

**Comment by bensku** [comment]
Should we want to update the license headers, I or another core team member will probably do it. Reviewing these changes would take a *very* long time.

**Comment by APickledWalrus** [comment]
Fair enough, don’t want to cause any issues in case they appeared.

**Pull request closed without merging**
