### PR TITLE
Parse entity by UUID

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
Add an option to parse an entity by their UUID

---
**Target Minecraft Versions:** all versions
**Requirements:** none
**Related Issues:** #1352

### CODE REVIEW

**Comment by FranKusmiruk** [comment]
I am concerned by the lag this could generate, seeing people already abuse of parsing offline player UUIDs, it might be worth considering a class like UnresolvedOfflinePlayer for entities.

**Comment by ShaneBeee** [comment]
> I am concerned by the lag this could generate, seeing people already abuse of parsing offline player UUIDs, it might be worth considering a class like UnresolvedOfflinePlayer for entities.

I can see your worry with this, but one thing to keep in mind, is when a Skripter is getting an offline player from a uuid, theres a chance (probably a high chance) they're getting an offline player from the MC servers where the player has never joined the server.
This method would be quite the opposite, as these methods would only check entities which are currently in the world. Meaning there wouldn't be lag checking any of Mojang's servers for an Offline Player.

**Comment by Matocolotoe** [comment]
What if there are a lot of entities in a lot of worlds ?

**Comment by ShaneBeee** [comment]
> What if there are a lot of entities in a lot of worlds ?

From my understanding the Bukkit#getEntity(uuid) method was adding in 1.11 (I see it in 1.11.2) which retrieves the entity from a map on the server (not actually internally looping), that said, this method should not lag a server if using 1.11+

As for 1.9.4 and 1.10.2, according to bStats, less than 2% of servers running Skript are on these versions. Personally I would rather just not have this available for this versions, but Blueyescat suggested I add it to have it available for all versions (if you see my previous commits It was only available for 1.11+).
In my opinion, it seems redundant to create another class to deal with entities in 1.9/1.10 when less than 2% of Skripters are using this versions. I would rather just remove the loop and have this only work on 1.11+

**Comment by Matocolotoe** [comment]
Yeah I think the last solution is better

**Comment by Blueyescat** [comment]
The current code is fine for the purpose, but a note like *"you should store the returned entity instead of parsing it repeatedly"* can be added. Other ways would be an effect to get the entity and store in variable and loading entity variables by getting entities by the stored uuid.

**Pull request merged**
