### PR TITLE
Add PropertyType to PropertyExpression

### PR DESCRIPTION
**Pull request by aabssmc**
### Description

Added PropertyTypes to PropertyExpressions, kinda like the PropertyTypes in a PropertyCondition just for expressions.
---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

### CODE REVIEW

**Review by AyhamAl-Ali — COMMENTED** [review]
Is there a real usage of this addition currently? can you share some examples

**Comment by aabssmc** [comment]
> Is there a real usage of this addition currently? can you share some examples

just in case you want to make a quick expression using 'in' or 'on' instead of 'of', maybe even 'at', right now the only option for an property expression is `%property% of %type%`, have multiple optional options would be better.

**Comment by AyhamAl-Ali** [comment]
> > Is there a real usage of this addition currently? can you share some examples
> 
> just in case you want to make a quick expression using 'in' or 'on' instead of 'of', maybe even 'at', right now the only option for an property expression is `%property% of %type%`, have multiple optional options would be better.

I do know of that but I couldn't find any current usage of those new properties in Skript which is why I asked if you have actual real examples of their usage.

**Comment by aabssmc** [comment]
> > > Is there a real usage of this addition currently? can you share some examples
> > 
> > 
> > just in case you want to make a quick expression using 'in' or 'on' instead of 'of', maybe even 'at', right now the only option for an property expression is `%property% of %type%`, have multiple optional options would be better.
> 
> I do know of that but I couldn't find any current usage of those new properties in Skript which is why I asked if you have actual real examples of their usage.

maybe in the future with this pr lol

**Comment by Fusezion** [comment]
Based off what Ayham said, is there any example you could give that showcases `on` or `in` over `of` as I don't view either of those two as something of a property

**Comment by Moderocky** [comment]
I can't really see a situation where this would help.

**Comment by Moderocky** [comment]
We are in agreement that we can't see a reasonable use case for this and so will be closing the pull request. If, in future, you think that you are able to provide a better rationale for this then you're welcome to reopen it.

**Pull request closed without merging**
