### PR TITLE
Make function parameters respect the case-insensitive-variables setting. 

### PR DESCRIPTION
**Pull request by sovdeeth**
### Description

Changes Parameter#parse() to only compare lowercase parameter names if caseInsensitive is true.
Changes Parameter to store the original string, rather than the lowercased string.

Manual testing indicates this fixes the issue.

Technically breaking changes in a very niche scenario, but only because it's reverting to intended behavior, so as previously established, not marking as breaking changes.

---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** #6379

### CODE REVIEW

**Review by AyhamAl-Ali — APPROVED** [review]
As you mentioned it's not _really_ a breaking change but in a scenario where a user had a similar variable usage to the code below
```v
function test(TEST: text):
    broadcast {_test}
```
their code will sadly not work if they had `case-insensitive-variables` as `false`. Though it might be rare to happen but I highly recommend making a statement about this in the next release just in case.

**Comment by sovdeeth** [comment]
> As you mentioned it's not _really_ a breaking change but in a scenario where a user had a similar variable usage to the code below
> 
> ```v
> function test(TEST: text):
>     broadcast {_test}
> ```
> 
> their code will sadly not work if they had `case-insensitive-variables` as `false`. Though it might be rare to happen but I highly recommend making a statement about this in the next release just in case.

yeah good idea, should definitely mention it.

**Review by APickledWalrus — APPROVED** [review]
Is a test for this possible? Maybe could do something like

```
test "parameter test":
  assert parameterTest("test") is "test" with "did not return correct value"
function parameterTest(text: text) :: text:
    return {_text}
```

**Comment by sovdeeth** [comment]
> Is a test for this possible? Maybe could do something like
> 
> ```
> test "parameter test":
>   assert parameterTest("test") is "test" with "did not return correct value"
> function parameterTest(text: text) :: text:
>     return {_text}
> ```

I suppose, but we can't really test the actual point of the change, which requires the config option to be set to false

**Comment by APickledWalrus** [comment]
> > Is a test for this possible? Maybe could do something like
> > ```
> > test "parameter test":
> >   assert parameterTest("test") is "test" with "did not return correct value"
> > function parameterTest(text: text) :: text:
> >     return {_text}
> > ```
> 
> I suppose, but we can't really test the actual point of the change, which requires the config option to be set to false. Such an example wouldn't really help test anything but normal function behavior.

lol i just realized

**Comment by Pikachu920** [comment]
> > Is a test for this possible? Maybe could do something like
> > ```
> > test "parameter test":
> >   assert parameterTest("test") is "test" with "did not return correct value"
> > function parameterTest(text: text) :: text:
> >     return {_text}
> > ```
> 
> I suppose, but we can't really test the actual point of the change, which requires the config option to be set to false. Such an example wouldn't really help test anything but normal function behavior.

would it be possible to do so by changing the config option through a junit test?

**Review by Moderocky — APPROVED** [review]

**Pull request merged**
