### PR TITLE
Removal of ExprIdOf

### PR DESCRIPTION
**Pull request by Fusezion**
### Description
With the first beta release of `2.7.0` skript became 1.13+ as such, this expression no longer needs to be supported within skript.
this could be labled a breaking change, as it might still have been possible to use on 1.13 at least based off the fact it would return a warning.

---
**Target Minecraft Versions:** 1.13+
**Requirements:** None
**Related Issues:** None

### CODE REVIEW

**Review by AyhamAl-Ali — APPROVED** [review]

**Comment by Fusezion** [comment]
> I’d prefer a PR which removes all pre-1.13 elements instead.

What's the other ones?

**Comment by DelayedGaming** [comment]
I’m unsure whether there are bit of pre-1.13 elements retained, apart from ExprName which involves reflections for legacy inventory title getter. So I believe it is best to do so in a single PR.

**Comment by Fusezion** [comment]
As far as I'm aware there's very little expressions that worked exclusively for pre 1.13 as such those are the only ones I'd want to include in this pr, however I'm unable to think of find any of them with the fact majority were given backwards compatibility unlike this

**Comment by TheLimeGlass** [comment]
Delete https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/aliases/MaterialRegistry.java while you're at it. It's not used.

**Comment by Moderocky** [comment]
It might be better to remove features separately in case something has to be reverted in future for some reason.

**Comment by Fusezion** [comment]
> Delete https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/aliases/MaterialRegistry.java while you're at it. It's not used.

outside of removing most other pre-1.13 only syntax is this still an okay thing to remove within this pr?

**Comment by TheLimeGlass** [comment]
> > Delete https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/aliases/MaterialRegistry.java while you're at it. It's not used.
> 
> outside of removing most other pre-1.13 only syntax in their own prs is this still an okay thing to remove within this pr?

Yes it's ID related

**Review by TheLimeGlass — APPROVED** [review]

**Pull request merged**
