### PR TITLE
Return correct block for placing water in slabs, ...

### PR DESCRIPTION
**Pull request by Vulcano771**

### CODE REVIEW

**Comment by Vulcano771** [comment]
This pr should fix that bug: `https://discord.com/channels/135877399391764480/836220422223036467/1210159979193966685`

> I noticed that when you place water into a slab or leaves than it says the wrong location too
> (broadcast "%event.getBlockClicked().getLocation()% vs %event-location%")

**Review by Fusezion — CHANGES_REQUESTED** [review]
I believe this pr should change a bit more than currently changed. 
image

The image above is from this code here
```
on bucket empty:
    broadcast ""
    broadcast "R-Block: %event.getBlock()%"
    broadcast "R-BlockClicked: %event.getBlockClicked()%"
    broadcast "S-Block: %event-block%"
```
    
the prefix `S` is to identify as a skript method
and `R` as a reflect method. 
    
I believe the `event-block` should default to `event.getBlock()` and edit the expression `clicked block` to support the `event.getBlockClicked()` as there's two possible blocks within this event and this should help tell them about even if by a little

**Comment by Vulcano771** [comment]
Yes, I tested too a bit, .getBlock() seems to get the right block - I changed it to return the block where the bucket will be placed on
(if we place water on a slab it returns the slab)
(if we place lava on a slab it returns the block where the lava will come)

**Comment by Fusezion** [comment]
looking over this it appears we only changed `past event-block` the `event-block` doesn't seem changed or skript just has a weird handle on it, the little bit of code below it should be the base `event-block`

**Pull request closed without merging**
