### PR TITLE
Remove useless code

### PR DESCRIPTION
**Pull request by Matocolotoe**
### Description

Just removes some useless code and documentation

---
**Target Minecraft Versions:** any    
**Requirements:** none    
**Related Issues:** none

### CODE REVIEW

**Comment by bensku** [comment]
Magic numbers in code are bad, and the more information we preserve in docs, the better. As such, I'm closing this PR.

**Comment by Matocolotoe** [comment]
cos(pi/4) is strictly equal to 0.5 and will always be so storing its value in a variable is kinda useless

**Comment by TPGamesNL** [comment]
> cos(pi/4) is strictly equal to 0.5 and will always be so storing its value in a variable is kinda useless

It's `0.5 * sqrt(2)`, not 0.5

**Comment by Matocolotoe** [comment]
oops, that's right, but i don't understand the point of storing it anyways xd

**Comment by Pikachu920** [comment]
Read more here: https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad

it could be improved by being a static final somewhere but.... meh

**Comment by Matocolotoe** [comment]
Got it 👍

**Pull request closed without merging**
