### PR TITLE
Merge conditions and expressions

### PR DESCRIPTION
**Pull request by TPGamesNL**
### Description
This PR makes all conditions boolean expressions, and all boolean expressions can be used as conditions (mostly).
<details>
<summary>Examples</summary>

```
set {_a} to true
if {_a}: # passes
```

Boolean operations:
```
set {_a} to true
set {_b} to true
if {_a} and {_b}: # passes
```
```
set {_a} to true
set {_b} to false
if {_a} and {_b}: # fails
```
```
set {_a} to true
set {_b} to false
if {_a} or {_b}: # passes
```
`if player can fly and player is alive:`

But:
```
set {_a} to 1
# set {_b} to 1
if {_a} is set and {_b} is not set: 
```
does not pass, because it is parsed as `if (({_a} is set) and {_b}) is not set`, where `({_a} is set) and {_b}` is a boolean 'and' operation with the condition and the variable. If you use parentheses, `if ({_a} is set) and ({_b} is not set):`

Also
`set {_a} to {_b} is set`
`set {_x} to player is online`
</details>

Only limitation is that inline conditions can't be expressions, for example:
```
set {_b} to false
{_b} # would exit the current section
```
doesn't parse, but I'm not even sure if having that would be beneficial.

---
**Target Minecraft Versions:** any
**Requirements:** none
**Related Issues:** #2207

### CODE REVIEW

**Comment by Mwexim** [comment]
Lovely changes! Something that had to be done, possibly way earlier.

I’ll give you [this](https://github.com/SkriptLang/skript-parser/pull/83) link. It is a PR of line where I fix the parsing issue that still remains (the fact that boolean operators and list literals clash with each other).

Do what you want with it, I’ll leave it here for convenience.

**Comment by Nicofisi** [comment]
Hey! What's the status of this?

**Comment by TPGamesNL** [comment]
@Nicofisi There's no progress on this, I've been busy with other stuff and this has lost my attention. I'm also still unsure over the design, for example if all %boolean% (or %object%) should allow conditions by default (and without extra syntax) and if all conditions should be expressions by default. But that is for if I ever pick this up again.

**Comment by APickledWalrus** [comment]
Closing in favor of https://github.com/SkriptLang/Skript/pull/6748

**Pull request closed without merging**
