### PR TITLE
Add tropical fish support

### PR DESCRIPTION
**Pull request by Snow-Pyon**
Target Minecraft versions: 1.13+
Requirements: N/A
Related issues: #1385 
Description:
Adds support for tropical fish, which should add support for every entity once #1486 is merged.

This wasn't tested yet (I bet it doesn't even compile, I'll fix that later), I've made it just to receive input about how it is handled as soon as possible.

### CODE REVIEW

**Comment by ShaneBeee** [comment]
Hey snow.. Just wanted to suggest the plural of blockfish and clayfish should be ¦es instead of ¦s

**Comment by Snow-Pyon** [comment]
@ShaneBeee good catch. To be honest, I automatized it with a python script since I didn't want to manually write the pattern for every type so that's why it's that way.

**Comment by Nicofisi** [comment]
@ShaneBeee ... the outcome was an empty page on a paste service that deletes the pastes after some time - could you please repost it on https://gist.github.com and use it next time 👀 <3

**Comment by Blueyescat** [comment]
I applied the changes to 2.3-beta1 because i had issues with 2.3-alpha1, and the code @ShaneBeee send just works as expected. It spawns tropical fishes with random colors.

I will add more info i see here

**Pull request merged**
