### PR TITLE
Add an entity based syntax system

### PR DESCRIPTION
**Pull request by TheLimeGlass**
### Description
I talked to Bensku about this a month ago for the idea and brainstormed a game plan, so here is my first alpha commit of Entity based Syntax. I plan on adding entity based syntax after I get some opinions on this current implementation, also I have done a bunch of testing with this so far, and I have found no conflicts or issues, good sign.

Information: This pull at the moment is a base alpha implementation for entity based syntax, basically what that means is having syntax designed around an entity, so for example being able to set the rotation of armour stands, being able to set the shoulder a parrot sits on, the way a skulker box attaches etc. My first implementation was adjusting the parser to read entity based syntax and classes, but that got way too complex and wasn't worth the time, so Bensku told me, why don't you just implement it through classinfos, so this is that version, I scrapped the old version as it was too much to do.

I also had syntax planned like EntityPropertyExpression (name could be changed) and such to account for making it easier to choose entities of the syntax, it may not be needed as this classinfo would work better.

I also have a question after working with EntityData so much, why are some entities registered in SimpleEntityData but they already have their own EntityData implementation? I placed them as superTypes like what Njol did when he had duplicates.

Let me know your thoughts on this before I go any further. Thanks.

### CODE REVIEW

**Comment by TheLimeGlass** [comment]
I plan on doing a thoural test on this soon. I have only tested 1.13 and 1.12 (loading)

**Comment by JRoy** [comment]
@TheLimeGlass llamas were added in 1.11 an since skript supports 1.9 and 1.10 it should work on their too

**Comment by TheLimeGlass** [comment]
Tested on 1.9.4 and it did error, it doesn't anymore, couldn't test 1.8 as Skript doesn't support 1.8 yet, it crashes with unknown aliases.

Llama's work in 1.11+, in 1.10 and lower it summons a horse.

**Comment by TheLimeGlass** [comment]
First implementation and API design successful. Next issue is looking into passing Entity through the EntityData's classinfo.

**Comment by TheLimeGlass** [comment]
@Snow-Pyon What happened? It shows the whole file is different now?

**Comment by Snow-Pyon** [comment]
@TheLimeGlass the difference is messed up, I didn't change the whole file. This normally happens when the line separator is changed (e.g: changing it from CR to LF), even though I don't know why it changed in first place.

**Comment by bensku** [comment]
Sorry for long wait, but is this PR really ready to be reviewed? Your last comment seems to indicate that there is still work to be done.

**Comment by TheLimeGlass** [comment]
I have a lot of work done that's not committed, I will message you on Discord about some parser info.

**Comment by bensku** [comment]
@TheLimeGlass Are you still interested in finishing this PR?

**Comment by TheLimeGlass** [comment]
Yes and maybe some should be split into it's own pull like the entity data clean up and additions of 1.12, 1.13 entities there.

**Comment by TheLimeGlass** [comment]
I'll close this until I got time to work on it again

**Pull request closed without merging**
