### PR TITLE
EffPotion - fix potion effects duration

### PR DESCRIPTION
**Pull request by ShaneBeee**
### Description
This PR aims to fix the potion effects duration bug in 2.7

---
**Target Minecraft Versions:** none
**Requirements:** none
**Related Issues:** #5987

### CODE REVIEW

**Review by Fusezion — APPROVED** [review]
10/10 would break again

**Comment by APickledWalrus** [comment]
Could you rebase this to target master? We can do another PR for cherry-picking to dev/2.7

**Comment by Fusezion** [comment]
Should it not target master where the issue exists and Cherry pick from that?

**Comment by ShaneBeee** [comment]
closing due to conflict issues

**Pull request closed without merging**
