### PR TITLE
Fix Item Comparison Issues

### PR DESCRIPTION
**Pull request by APickledWalrus**
### Description
This PR fixes an issue with item meta comparisons. Essentially, we were checking "our" values for nullness / emptyness but not "their" values. This resulted in the following comparison issue:

image
"null" and "Diamond" are definitely not the same. Instead, the following scenario now results in a `SAME_MATERIAL` quality result.

This actually used to work right before 2.5 alpha 2. At that point in time, we were just checking "their" values which essentially caused this issue but in reverse.

It also fixes issues with skull comparisons and default aliases.

This PR needs more testing before being merged. Input from others is also appreciated.
---
**Target Minecraft Versions:** Any
**Requirements:** Any
**Related Issues:** #3405 (maybe others too)

### CODE REVIEW

**Comment by APickledWalrus** [comment]
Okay, so the latest commit tries to fix more comparison issues by changing the way ItemTypes are compared. I think this way of comparing should work well. I wrote a somewhat extensive test to make sure there aren't any issues, but it's always possible that there could be some.

**Comment by Leonardo-Fiori** [comment]
> "null" and "Diamond" are definitely not the same. Instead, the following scenario now results in a SAME_MATERIAL quality result.
> 
> This actually used to work right before 2.5 alpha 2. At that point in time, we were just checking "their" values will essentially caused this issue but in reverse.

Interesting stuff! Infact this started happening after updating to 2.5, the issue was not there in 2.4

**Comment by TheLimeGlass** [comment]
@APickledWalrus I suggest posting a built jar in this conversation, as most Skript users don't know how to compile and would help with the testing.

Does this pull essentially fix `if event-item is light green stained glass named "&aLimeGlass":`

**Comment by Leonardo-Fiori** [comment]
I just tried the last nightly build (74fd002) and nope, the issue is still there...

```
		if arg-player has arg-number of diamonds named "":
			remove arg-number of diamonds named "" from arg-player's inventory
			add {_worth} to arg-player's money
			play sound "block.metal.step" with volume 1 and pitch 2 for arg-player
```

this piece of code counts also renamed diamonds, and removes them from player's inventory... as usual, it used to work before 2.5 came out

**Comment by APickledWalrus** [comment]
> I just tried the last nightly build ([74fd002](https://github.com/SkriptLang/Skript/commit/74fd002638087f98acbc81d46ff7cbf18e9d6bd8)) and nope, the issue is still there...
> 
> ```
> 		if arg-player has arg-number of diamonds named "":
> 			remove arg-number of diamonds named "" from arg-player's inventory
> 			add {_worth} to arg-player's money
> 			play sound "block.metal.step" with volume 1 and pitch 2 for arg-player
> ```
> 
> this piece of code counts also renamed diamonds, and removes them from player's inventory... as usual, it used to work before 2.5 came out

You will need to try the latest build of this PR. You can try downloading it here: https://github.com/SkriptLang/Skript/suites/1272558230/artifacts/19615437

If that doesn’t work, let me know and I can upload a jar here

**Comment by APickledWalrus** [comment]
> 
> 
> @APickledWalrus I suggest posting a built jar in this conversation, as most Skript users don't know how to compile and it would help with the testing.
> 
> Does this pull essentially fix `if event-item is light green stained glass named "&aLimeGlass":` which has been a long time known bug where the condition is always false. That's probably the main cause.

I meant to reply to this earlier... whoops. In the case you give, if I use the `right click` event it does successfully compare, so yes I suppose. The main goal of this PR is to try and fix many, if not all, of the comparison issues with items.

**Comment by Leonardo-Fiori** [comment]
This. Is. Finally. Fixed. Thank you! Merge this damn fix 😆

**Comment by Leonardo-Fiori** [comment]
This isn't probably realted to your build but maybe you know what is causing this error in the console, it happens sometimes:

[err.txt](https://github.com/SkriptLang/Skript/files/5324038/err.txt)

**Comment by Leonardo-Fiori** [comment]
Also, is this fix included in the last release? The official skript 2.5

**Comment by APickledWalrus** [comment]
> 
> 
> Also, is this fix included in the last release? The official skript 2.5

It is not. However, the Skript jar I linked above is Skript 2.5 + this fix.
This fix *should* be included in Skript 2.5.1

**Comment by APickledWalrus** [comment]
> 
> 
> This isn't probably realted to your build but maybe you know what is causing this error in the console, it happens sometimes:
> 
> [err.txt](https://github.com/SkriptLang/Skript/files/5324038/err.txt)

You can open a separate issue report for this.

**Review by ShaneBeee — APPROVED** [review]
As long as this all works, and doesn't cause issue, it looks good to me 👍

**Pull request merged**
