### PR TITLE
Shouldn't check length of Material

### PR DESCRIPTION
**Pull request by 0XPYEX0**
### Description

We shouldn't check ID length while getting a material.
Bukkit checked it:
bc5e232100eac8b56d9931d8d80a829e

If we check it, Skript cannot parse aliases of mod items  (In Hybrid Server)
---
**Target Minecraft Versions:** any 
**Requirements:** none 
**Related Issues:** none

### CODE REVIEW

**Review by Efnilite — APPROVED** [review]

**Comment by BredyAK** [comment]
I strongly recommend to approve this PR because:
1. in future minecraft versions, maybe there will be a way to directly add blocks/items to minecraft by datapack. then the nameplace may not be `minecraft`. but currently Skript doesn't support to create aliases for items which do not use `minecraft` as their nameplace.
2. as the 1st opinion said, if this PR is approved, then Hybird servers will also benefit from this, which could let modded items being added to Skript aliases.
3. this PR doesn't break any Skript's current core things, but increased scalability.
4. there are a lot of people want this too, such as [https://forums.skunity.com/threads/14952/](https://forums.skunity.com/threads/14952/), [https://forums.skunity.com/threads/9848/](https://forums.skunity.com/threads/9848/), [https://forums.skunity.com/threads/14457/](https://forums.skunity.com/threads/14457/), etc. if you google "Skript Mod Item" or something similiar, you could find a lot more.

i know that Skript doesn't support Hybird servers, but this PR is intended to improve the scalability of Skript, not just for Hybird servers.

**Review by APickledWalrus — APPROVED** [review]
Seems fine to me

**Comment by 0XPYEX0** [comment]
@Efnilite 
May I ask your permission again?
I merged the branch and it seems invalid🥺

**Comment by Efnilite** [comment]
> @Efnilite May I ask your permission again? I merged the branch and it seems invalid🥺

Wdym?

**Comment by 0XPYEX0** [comment]
> > @Efnilite May I ask your permission again? I merged the branch and it seems invalid🥺
> 
> Wdym?

sorry I made a mistake..

**Comment by BredyAK** [comment]
> > @Efnilite May I ask your permission again? I merged the branch and it seems invalid🥺
> 
> Wdym?

maybe he means to ask you to review the PR again, because he updated his codes after your last review.

**Review by sovdeeth — APPROVED** [review]

**Review by UnderscoreTud — APPROVED** [review]

**Comment by BredyAK** [comment]
> If we check it, Skript cannot parse aliases of mod items (In Hybrid Server)

@0XPYEX0 it looks like the PR doesn't work as your expect, please check it again

**Review by Moderocky — APPROVED** [review]

**Comment by APickledWalrus** [comment]
If any other changes need to be made, feel free to open another PR

**Pull request merged**
