### PR TITLE
No Damage Ticks Expression

### PR DESCRIPTION
**Pull request by Wealthyturtle**
### Description
This PR will allow users to get / modify the "no damage ticks" (aka invulnerability ticks) of living entities. Could be useful in scripts for inducing a cooldown on mob hits or for removing naturally occurring invulnerability ticks.

---
**Target Minecraft Versions:**     Any
**Requirements:**     None
**Related Issues:**     None

### CODE REVIEW

**Comment by APickledWalrus** [comment]
Might be nice to be able to use remove in this. Not a necessity though.

**Comment by Wealthyturtle** [comment]
Remove having the subtract effect?

**Comment by APickledWalrus** [comment]
yeah

**Comment by Wealthyturtle** [comment]
Added the Remove ChangeMode, with proper handling for negative addition/negative removes.

**Pull request merged**
